ludwig/explain/util.py
When generating explanations, a call to `prepare_data()` is made which filters out all columns except for input features. This leads to a key error during data preprocessing when Ludwig looks for a split column if a non-random type of splitting has been specified. The proposed fix makes sure that split column is not removed from the df that is sent for preprocessing from the explanations generation.
=> Include split column in explanation df

.pre-commit-config.yaml, ludwig/contribs/aim.py
Starting from `3.13` version Aim SDK rejects `Run.hash` values other than auto-generated ones. Implementation of AimCallback sets the `model_name` as `aim.Run.hash`, which started to fail with an exception.
Fix includes the following changes:
- set `model_name` as `aim.Run.name`
- when the callback is initialized, check the `aim.Repo` for the Run with name == "model_name" and use it for tracking, otherwise, create a new `aim.Run`.
=> Fix AimCallback to model_name as Run.name

ludwig/hyperopt/run.py, tests/ludwig/hyperopt/test_hyperopt.py
After the encoder/decoder refactor, we need to make sure we're checking if an encoder/decoder is specified first before checking if the type of the encoder or decoder is a default encoder or default decoder. This PR makes sure we're checking this with the right level of nesting and also refactors the function to make it simpler. It also adds unit tests for the `get_features_eligible_for_shared_params` function.
=> Hotfix: features eligible for shared params hyperopt

ludwig/hyperopt/run.py, ludwig/utils/backward_compatibility.py, tests/integration_tests/test_hyperopt.py
Since @dantreiman's changes to backwards compatibility, hyperopt flow wasn't calling back compat logic. I added that in. There was also an issue where the back compat logic uses the global ludwig version to determine which updates to make, but the ludwig version may contain a 'dev' or an 'rc' so added a regex pattern to grab that. Only change in predibase needed is a Ludwig version corresponding to that config.
=> Hyperopt Backwards Compatibility

ludwig/utils/backward_compatibility.py
This column is missing in the output feature schema, which causes the wrong proc_column to be used occasionally during model load/prediction which causes further downstream failures.
=> Hotfix: Proc column missing in output feature schema

ludwig/models/gbm.py, tests/integration_tests/test_gbm.py
Adds previously failing test + fix by casting inputs to float
=> Bugfix: non-number inputs to GBM

ludwig/schema/trainer.py, ludwig/trainers/trainer_lightgbm.py
Makes GBM training iterative to log intermediate progress + add test set eval metrics if available
=> GBM: log intermediate progress

ludwig/schema/__init__.py, ludwig/schema/decoders/utils.py, ludwig/schema/encoders/utils.py, ludwig/utils/backward_compatibility.py, tests/ludwig/utils/test_backward_compatibility.py, tests/ludwig/utils/test_validate_config_combiner.py
This fix adds a backwards compatibility step into the validate config step for the schema. The issue we we're dealing with was the frontend validating for 0.5 configs and Ludwig for 0.6. The solution in this PR is to update the configs in the validation step which will allow the frontend to validate old valid configs. These will get converted by backwards compatibility upon training anyways so we are just updating them before validation so that the frontend can validate without conflicting with Ludwig validation.
Note: the reason for importing `upgrade_to_latest_version` in the `validate_config` function is because circular imports start occurring if we import it at the top. This is something I will fix in the future, but may take a bit longer. If everyones ok with it, I will leave it …
=> Fix: Upgrade ludwig config before schema validation

ludwig/api.py, ludwig/constants.py
If the validation set has only one row (which may occur in some of our tests) then calibration will fail with nan metrics.
=> Log warning for calibration if validation set is trivially small

examples/calibration/README.md, examples/calibration/train_forest_cover_calibrated.py, examples/calibration/train_mushroom_edibility_calibrated.py, ludwig/features/base_feature.py, ludwig/features/binary_feature.py, ludwig/features/category_feature.py, ludwig/schema/features/binary_feature.py, ludwig/schema/features/category_feature.py, ludwig/utils/backward_compatibility.py, ludwig/utils/visualization_utils.py
- Adds calibration to binary and category output feature schemas
- Fixes bug in brier plot which causes class probabilities plot to overshadow brier score
- Adds forest cover and mushroom edibility calibration examples
Brier plot:
=> Fixes calibration and adds example scripts

ludwig/utils/visualization_utils.py
seaborn 0.12 got released 9hr ago. keyword arguments are now required for plotting functions:
https://seaborn.pydata.org/whatsnew/v0.12.0.html#keyword-only-arguments
=> Fix: explicit keyword args for seaborn plot fn

ludwig/export.py, ludwig/models/inference.py, tests/integration_tests/test_api.py, tests/integration_tests/test_cli.py
This PR implements small improvements for the `export_torchscript` CLI command. Notable behavior changes are the following:
- `--output_path` is now an optional command line argument. If none, then the `output_path` defaults to being the same as `model_path`. This is in contrast to its initial implementation, which placed models in some `torchscript/` directory. The downside of using `torchscript/` as the default was that artifacts could be overridden if multiple torchscript arguments were passed in.
- `model_hyperparameters.json` and `training_set_metadata.json` are now copied into the resulting torchscript export directory. This makes it possible to use the `InferenceModule.predict` function– which requires `model_hyperparameters.json`– regardless of where the inference modules are …
=> Enh: quality-of-life improvements for `export_torchscript`

ludwig/constants.py, ludwig/schema/trainer.py, ludwig/trainers/trainer.py, tests/integration_tests/test_ray.py
If batch_size is set to `auto`, this PR implements a change that (1) detects whether or not the device is CPU, (2) logs a warning if it is, then (3) sets the batch size to the default 128.
Before this change, the batch size tuner would never OOM or hit any other runtime Exception on CPU-only machines, leading to arbitrarily high batch sizes– often, the batch size would be the max possible batch size, which was some value `0.5 * len(training_dataset) < batch_size < len(training_dataset)`. Such a large batch size would lead to OOMs downstream, particularly when training using a Ray cluster.
Future work includes re-enabling batch size tuning for CPU-only machines, possibly by using some memory limit values introduced by either Ray or the system itself.
=> Disables `batch_size: auto` for CPU-only training

ludwig/utils/automl/type_inference.py, tests/ludwig/automl/test_data_source.py, tests/ludwig/utils/automl/test_type_inference.py
This fixes an issue where we were seeing that columns with single distinct values (say all 1s) were being inferred as a binary value which caused downstream problems when trying to precompute the fille value with the following error:
```
Unable to determine False value for column X with distinct values: [1].
```
This fix changes these types of features to be inferred as categorical features, and also for them to be excluded from the dataset since a categorical feature with the same value doesn't add anything to a machine learning model.
=> Infer single distinct value columns as category instead of binary

ludwig/models/predictor.py
dask 2022.6+ changes the schema behavior to `schema="infer"`, which mistakenly infers that `<Output_feature>_probabilities` is a string (since it's an object) instead of a list of numbers. To fix, change back to `schema=None`, which was the behavior in 2022.5 and before
alternatively, we can enforce the schema only on this column, but we would need custom logic to do something like
```
import pyarrow as pa
postprocessed_output.to_parquet(os.path.join(output_directory, PREDICTIONS_PARQUET_FILE_NAME),
schema={probabilities_col: pa.list_(pa.int64())})
```
but that could get messy since the expected schema types are different based on the parquet engine (pyarrow vs fastparquet etc...)
https://github.com/dask/dask/issues/9211
=> fix: Add explicit schema in to_parquet() during saving predictions

ludwig/utils/backward_compatibility.py, ludwig/utils/trainer_utils.py, tests/ludwig/utils/test_backward_compatibility.py
* Convert epoch-based stats into steps-based stats for compatibility with #1803. Epoch to steps conversion is approximate, as we don't have access to the full history of any batch size increases.
* Reformat train/test/validation metrics into `TrainerMetric` tuples, also with estimated epoch and step values.
=> Add backwards-compatibility logic for model progress tracker

ludwig/api.py, ludwig/data/dataset_synthesizer.py, ludwig/data/preprocessing.py, ludwig/utils/backward_compatibility.py, tests/regression_tests/model/test_old_models.py
Also adds new tests for old model versions.
We should, very soon, find a way to decouple the config from the training set metadata to avoid these sorts of situations in the future.
=> Fixed backwards compatibility for training_set_metadata and bfill

ludwig/utils/backward_compatibility.py, tests/regression_tests/model/test_old_models.py
Following #1859, some older models (pre-v0.5 official release) could contain these invalid params, which are no longer part of the valid preprocessing schema.
=> Fixed backwards compatibility for models with level metadata in saved configs

ludwig/schema/utils.py, tests/ludwig/marshmallow/test_fields_misc.py
Fixes a bug for existing fields like `learning_rate` which currently end up with a top-level title of 'tmp' and no option-specific titles.
=> fix: Automatically assign title to OneOfOptionsField

ludwig/data/split.py, tests/integration_tests/test_ray.py, tests/ludwig/data/test_split.py
Assumes every partition fits in memory
Given $P$ the set of partitions of dataset $D$, and $S$ the set of unique values in the stratify column. When stratified splitting every partition individually, $\forall s \in S:$
$$
\begin{align}
&\sum_{p \in P} \\%\_{train} \times | p\_{S = s} | & \\%\_{train} \texttt{ of every partition's } s
\texttt{ values will be in that partition's train} \\
= &\\%\_{train} \times \sum_{p \in P} | p\_{S = s} | & \texttt{which is } \\%\_{train} \texttt{ of the sum of all } s \texttt{ value counts over all partitions} \\
= &\\%\_{train} \times | D\_{S = s} | & \texttt{which is } \\%\_{train} \texttt{ of the total number of } s \texttt{ values} \\
\end{align}
$$
$\\%\_{train}$ of records in $D$ with value $s$ in the stratify column will land in the training set. …
=> [cherry-pick] Fixed stratified splitting with Dask (#1883)

ludwig/features/image_feature.py, requirements.txt, tests/integration_tests/test_ray.py
When we create a tensor directly from a numpy array instead of from a copy, it creates unpredictable behavior and results in the creation of ragged tensors downstream which causes weird type mismatch issues that Ray doesn't like. This change ensures we create the tensor from a copy of the numpy array so that we don't run into this issue.
=> Fix flaky ray nightly image test

ludwig/models/base.py, ludwig/models/ecd.py, ludwig/models/gbm.py, ludwig/schema/trainer.py, ludwig/trainers/trainer.py, ludwig/trainers/trainer_lightgbm.py, ludwig/utils/trainer_utils.py, tests/conftest.py, tests/integration_tests/test_gbm.py, tests/integration_tests/test_model_training_options.py
Runs evaluation after every `boosting_rounds_per_checkpoint` to populate training/validation metrics as required by hyperopt
Mimics as much as possible the ECD train loop logic
=> GBM: support hyperopt

ludwig/automl/auto_tune_config.py, ludwig/automl/automl.py, ludwig/automl/base_config.py, ludwig/utils/automl/data_source.py, ludwig/utils/automl/type_inference.py, ludwig/utils/misc_utils.py, tests/integration_tests/test_automl.py, tests/ludwig/utils/automl/test_type_inference.py
Fixes #2499.
Related #2497.
Also changes exclusion logic to be less restrictive for index-looking fields.
=> Fixed support for distributed datasets in create_auto_config

ludwig/api.py, ludwig/hyperopt/run.py, ludwig/utils/dataset_utils.py
Follow up from https://github.com/ludwig-ai/ludwig/commit/39ba54197820e0a33645dc7ccb36a0809ae1a6e8
This ensures that we can see dataset statistics for hyperopt and it also fixes the current issues with the dataloader on master
=> Surfacing dataset statistics in hyperopt

ludwig/api.py, ludwig/data/dataset/base.py, ludwig/data/dataset/pandas.py, ludwig/data/dataset/ray.py, ludwig/hyperopt/run.py, ludwig/utils/dataset_utils.py, tests/integration_tests/test_preprocessing.py
Resolves merge conflicts from failed cherry-pick
=> Add in-memory dataset size calculation to dataset statistics and hyperopt (#2509)

ludwig/datasets/loaders/mnist.py
Image files were not being exported when running:
```python
from ludwig.datasets import mnist
mnist.export(".")
```
Fixed by generating image files for mnist in `transform_files `(so that preserve_paths mechanism can pick them up for export).  Image files are now stored in processed_dataset_dir, and export works.
=> Fixes mnist dataset image files not exporting

ludwig/features/number_feature.py, tests/integration_tests/test_number_feature.py
This PR raises a warning when a number feature is being used that has a constant value across all rows of the dataset, along with preprocessing being set to `zscore`. This results in a std deviation of 0 and a divide by zero error. This results in the feature being processed as NaNs, the downstream metrics to be NaNs, etc. which isn't a good outcome. 
Questions:
- Is this a good enough reason to raise a RuntimeError and cause the model execution to stop?
- Would it instead make sense to:
- Log a warning stating the reason why zscore normalization failed
- Just return the same value back, i.e., `self.mu` which is the average of the column == the value itself?
=> ZScore Normalization Failure When Using Constant Value Number Feature

ludwig/utils/visualization_utils.py, ludwig/visualize.py
This is the result of running `train_mushroom_edibility_calibrated.py`, which generates two models "Uncalibrated" and "Calibrated" for the dataset with two classes "e" and "p" (edible and poisonous)
Before:
---
After:
=> Adds class names to calibration plot title, reformats Brier scores as grouped bar chart

.github/workflows/pytest.yml
We started seeing a lot of test failures related to TensorDType in Ray nightly on September 22nd. It seems like this is related to changes made on September 21st. This pins Ray nightly to the last commit made on September 20th so that we don't see these failures.
It appears that there's been stronger conditions added for type inference, specifically related to ragged tensors.
=> Pin ray nightly version to avoid new test failures

ludwig/automl/automl.py, ludwig/automl/base_config.py, ludwig/backend/base.py, ludwig/backend/horovod.py, ludwig/backend/ray.py, ludwig/utils/system_utils.py, tests/integration_tests/test_cli.py, tests/integration_tests/test_ray.py
Adds tests to check `init_config` and `render_config` CLI commands are working correctly.
See #2448.
Also fixes `init_config` to work without a running Ray cluster.
=> Added tests for init_config and render_config CLI commands

ludwig/data/preprocessing.py, ludwig/utils/dataframe_utils.py, tests/integration_tests/test_ray.py, tests/integration_tests/utils.py
If the dataset has the first few rows or last few rows as NaNs (especially the first row in the case of ffill, or last row in case of bfill), it can result in a dataset where there are NaNs even after we try to handle the missing value strategy. This causes ragged tensors downstream (particularly in the case of image or audio features) where the missing value strategy is `bfill` by default.
This fix adds a conditional check to see if there are still rows with NaNs, and then applies a secondary missing value strategy to fix it. For e.g., if `bfill` doesn't get rid of all of the NaNs, we're going also apply `ffill` since this will guarantee all rows are non-None. The same is true if the primary missing_value_strategy is `ffill` and there are NaNs left over, which will then create a …
=> Ensure bfill/ffill leave no residual NaNs in the dataset during preprocessing

ludwig/utils/dataset_utils.py
Fixes the following warning
```
ludwig/ludwig/utils/dataset_utils.py:91: SettingWithCopyWarning:  A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
```
when running
```
from ludwig.datasets import ames_housing
from ludwig.utils.dataset_utils import get_repeatable_train_val_test_split
dataset = ames_housing.load(split=False)
get_repeatable_train_val_test_split(dataset)
```
=> Fixing SettingWithCopyWarning when using `get_repeatable_train_val_test_split`

ludwig/utils/visualization_utils.py, requirements_viz.txt
This fixes an issue where the violinplots produced in the hyperopt_report were occasionally "flat lines" / "squashed violins" because there was only 1 trial associated with each parameter (violinplots are used to show a distribution which doesn't make sense when there's only 1 point). This happens in the case of parameters sampled from `choice` or `grid_search` spaces and the number of trials is very small (for e.g., < 5).
This PR makes two changes:
1. Create `stripplots` when all parameter values for the parameter have < 2 trials associated with them. This is because these will end up looking very awkward in a plot that's meant to show distributions. 
2. In the case that all sampled parameters have at least 2 trials associated with them, create a [RainCloud …
=> Migrate to Raincloud plots for hyperopt report

ludwig/features/feature_utils.py, ludwig/features/sequence_feature.py, ludwig/features/set_feature.py, ludwig/features/timeseries_feature.py, ludwig/schema/features/preprocessing/timeseries.py, ludwig/utils/strings_utils.py, ludwig/utils/tokenizers.py
Currently, a tokenizer availability warning is always logged unless `torchtext>=0.13.0` is installed, regardless of what kind of model you have.
Instead, we remove the pan-warning in favor of raising a `KeyError` during tokenizer registry access, with additional help text if the requested tokenizer would be available for a different version of torchtext.
Valid tokenizers are also enforced by the schema.
=> Remove global torchtext version-specific tokenizer availability warnings.

ludwig/utils/visualization_utils.py, tests/conftest.py, tests/integration_tests/test_visualization_api.py
This ensures that hyperopt pair plots are only created if there is > 1 parameter in the hyperopt parameter search space. Otherwise, in the case of only a single parameter, this creates an empty pair plot.
=> Only create hyperopt pair plots when there is more than 1 parameter

ludwig/utils/visualization_utils.py, requirements_viz.txt, tests/conftest.py, tests/integration_tests/test_visualization_api.py
Would be good to get these in since @hungcs and @ohho are actively working on a few other improvements that may require these.
=> Cherry pick hyperopt plots

ludwig/automl/automl.py, ludwig/automl/base_config.py, tests/integration_tests/test_automl.py
Adds stratified splitting to the AutoML generated config if the dataset:
- has a single output feature
- the output feature is categorical or binary
- the output feature's imbalance ratio is below `imbalance_threshold`
=> AutoML: stratify imbalanced datasets

ludwig/visualize.py
forgot to tag original pr (https://github.com/ludwig-ai/ludwig/pull/2565) so merging this manually
=> fix: Limit frequency array to top_n_classes in F1 viz (#2565)

ludwig/models/gbm.py, ludwig/trainers/trainer_lightgbm.py, tests/integration_tests/test_gbm.py, tests/integration_tests/test_model_save_and_load.py
This PR:
1. Fixes a bug where category variable with 2 classes gave wrong predictions
2. Asserts predictions from LightGBM and converted Hummingbird model match
3. Extends test coverage (incl. for the above cases)
4. Uses cleaner sklearn API for LightGBM
There are quite some changes, the PR is best reviewed commit-by-commit
=> GBM bugfix: matching predictions LightGBM, hummingbird

ludwig/trainers/trainer.py
Update logging when `early_stop: -1` to indicate that there isn't an early stopping criteria.
=> update logging message when `early_stop: -1`

tests/integration_tests/test_ray.py
This PR refactors `test_ray.py` to reduce time to test in CI and prevent timeouts. The changes reduce the runtime each distributed test by about 10% (between 4-5 minutes each), cutting down the overall CI time from 60 minutes to 45 minutes.
Old `test_ray.py` GH Action times: https://github.com/ludwig-ai/ludwig/actions/runs/3153188879
New `test_ray.py` GH Action times: https://github.com/ludwig-ai/ludwig/actions/runs/3154504170
=> Refactors test_ray.py to minimize duplicate training jobs

ludwig/api.py, ludwig/models/calibrator.py
The "Calibration uses validation set, but no validation split specified..." warning gets logged even if no output features have calibration enabled, and that is confusing.
This fix checks first to see if any output features are using calibration, and only logs these messages if so.
=> Quick fix: Don't show calibration validation set warnings unless calibration is actually enabled

LICENSE, ludwig/api_annotations.py
This PR introduces `api_annotations.py` that can be used to delineate the boundary of Ludwig APIs that are public, for developers, and those that are deprecated.
Co-authored-by: Daniel Treiman <daniel@predibase.com> (@dantreiman)
=> Add API Annotations to Ludwig

tests/integration_tests/test_preprocessing.py, tests/ludwig/utils/automl/test_type_inference.py
Tests for non-conventional binary feature that 
1. true/false labels are inferred correctly when `fallback_true_label` is provided
2. a warning is logged in case no `fallback_true_label` is provided
3. AutoML treats them as `CATEGORY`
=> Extend test coverage for non-conventional booleans

tests/ludwig/models/test_training_determinism.py
These tests should be comparing the values from both of the runs, rather than to themselves.
=> Fix assertions in training_determinism tests

tests/conftest.py, tests/integration_tests/test_whylogs.py, tests/ludwig/automl/test_data_source.py, tests/ludwig/data/test_split.py, tests/ludwig/models/test_training_determinism.py, tests/ludwig/utils/test_dataframe_utils.py
This PR ensures that tests that use a Ray backend and initialize Ray always call `ray.shutdown()` so that there are no ghost ray instances running in subsequent tests. This causes a problem for downstream tests that want to either initialize ray manually or through a test fixture, because they try to re-initialize ray. 
The fix is just as simple as adding this text fixture to tests, so that Ray isn't initialized by the test (only by the fixture) and it is calls the teardown function automatically at the end of each module
=> Ensure no ghost ray instances are running in tests

.github/workflows/pytest.yml, ludwig/backend/ray.py, tests/conftest.py, tests/ludwig/backend/test_ray.py
Allows us to circumvent the `detect_nics` step, which is not necessary in all environments.
=> Allow explicitly plumbing through nics

tests/integration_tests/utils.py
Seeing some flakiness in some tests I added, so relaxing constraints (to a reasonable amount) to make sure they're no longer flaky.
=> Relax test constraint to reduce flakiness in test_ray

ludwig/data/split.py, ludwig/schema/split.py, tests/ludwig/data/test_split.py
This is useful for deterministically splitting on a unique ID. Even when additional rows are added to the dataset in the future, each ID will retain its original split assignment.
This approach does not guarantee that the split proportions will be assigned exactly, but the larger the dataset, the more closely the assignment should match the given proportions.
This approach can be used on a column with duplicates, but it will further skew the assignments of rows to splits. However, this may be useful if you need to ensure that the particular ID only appears in a single split (for example, a user ID with multiple rows, where we want to ensure the user isn't in both train and test sets).
The CRC32 approach was from: https://towardsdatascience.com/improve-the-train-test-split-with-the-hashing- …
=> Add splitter that deterministically splits on an ID column

ludwig/explain/util.py, tests/integration_tests/test_explain.py
Preprocessing config with fixed splitting without explicit column was breaking explanations. Fixed by keeping all columns required by splitter
=> fix(explain): missing columns for fixed split

tests/integration_tests/test_custom_components.py
Factoring out this code change from Config Object PR : https://github.com/ludwig-ai/ludwig/pull/2426/files/3c5936b117ce5c807f119c9504fd872eb5806d38#r991732056
=> Add type to custom combiner

ludwig/train.py
When hyperopt exists in the Ludwig config, it causes a strange interaction with `model.train()` which results in the very large step sizes/epoch sizes. This is unexpected and something that definitely needs to be looked into more deeply.
In the interim, here's a stopgap solution that removes hyperopt from the config if it is present since a majority of users use Ludwig through the CLI.
=> Remove hyperopt from config when running train through cli

ludwig/explain/captum.py, ludwig/explain/explainer.py, ludwig/explain/explanation.py, ludwig/explain/gbm.py
Marks as DeveloperAPI:
- `Explainer`: developers can implement this base class to add a new explanation algorithm
Marks as experimental PublicAPI:
- `Explanation` dataclass stores feature attributions for a single row
- `IntegratedGradientsExplainer`: Implements `Explainer` with Integrated Gradients
- `GBMExplainer`: Implements `Explainer` with GBM feature importance
=> [explain] add API annotations

.github/workflows/pytest.yml, ludwig/backend/base.py, ludwig/backend/utils/storage.py, ludwig/data/cache/manager.py, ludwig/data/preprocessing.py, ludwig/hyperopt/execution.py, ludwig/hyperopt/run.py, ludwig/hyperopt/syncer.py, ludwig/utils/backward_compatibility.py, ludwig/utils/fs_utils.py, requirements.txt, requirements_test.txt, tests/README.md, tests/docker-compose.yml, tests/integration_tests/test_cache_manager.py, tests/integration_tests/test_hyperopt.py, tests/integration_tests/test_remote.py, tests/integration_tests/utils.py, tests/ludwig/utils/test_backward_compatibility.py
This PR adds a basic structure for specifying different cloud credentials for different entities in the system. Currently supported is the cache and artifacts (for hyperopt), but this will be extended to support all artifacts (outputs) and datasets (inputs) in the future.
This also deprecates the `cache_credentials` backend config param and moves it to `credentials.cache`. The structure is:
```
backend:
credentials:
artifacts: ...
cache: ...
```
Also removes s3 as a test dep and uses an internal minio container instead, so forks can still run tests successfully.
=> Added storage backend API to allow injecting dynamic credentials

ludwig/api_annotations.py, ludwig/backend/ray.py, ludwig/benchmarking/profiler_callbacks.py, ludwig/callbacks.py, ludwig/contribs/aim.py, ludwig/contribs/comet.py, ludwig/contribs/mlflow/__init__.py, ludwig/contribs/wandb.py, ludwig/contribs/whylogs/__init__.py, ludwig/hyperopt/execution.py
This PR adds annotations for callbacks in Ludwig. In particular, it adds:
- DeveloperAPI to Callbacks that have changed recently or are exclusively for developers
- PublicAPI to callbacks that have been stable and have not had any recent changes
This ignores annotating callbacks that only exist within the scope of functions (like `UploadOnEpochEndCallback` within `api.py`), as well as those within tests.
=> [Annotations] Callbacks

ludwig/api.py, ludwig/constants.py, ludwig/data/dataset_synthesizer.py, ludwig/data/split.py, tests/ludwig/data/test_split.py
Should fix NaN metrics caused by too-small validation set.
Problem: if the validation set is too small (1 row, for example) some metrics evaluate to NaN, which causes tests to fail.
This situation is mainly encountered in test cases where we use small synthetic datasets with random splits.
The solution here is to add a constant `MIN_DATASET_SPLIT_ROWS`, and ensure that each nonempty split contains at least `MIN_DATASET_SPLIT_ROWS`
=> Adds minimum split size, ensures random split is never smaller than minimum for local backend

ludwig/encoders/category_encoders.py, ludwig/encoders/generic_encoders.py, ludwig/schema/encoders/base.py, ludwig/schema/encoders/category_encoders.py, tests/ludwig/models/test_training_success.py
Fix for ECD training failure when we set
```
defaults:
category:
encoder:
type: passthrough
```
=> Categorical passthrough encoder training failure fix

ludwig/schema/__init__.py
Fixes an issue that occurs when running multiple threads of LudwigModel at a time:
```
Exception in thread Thread-2:
...
model = LudwigModel(config)
File "ludwig/api.py", line 224, in __init__
self.config = merge_with_defaults(upgraded_config)
File "ludwig/utils/defaults.py", line 310, in merge_with_defaults
combiner_registry[config[COMBINER][TYPE]].get_schema_cls(), config[COMBINER]
File "ludwig/schema/utils.py", line 58, in load_config_with_kwargs
assert_is_a_marshmallow_class(cls)
File "ludwig/schema/utils.py", line 101, in assert_is_a_marshmallow_class
), f"Expected marshmallow class, but `{cls}` does not have the necessary `Schema` attribute."
AssertionError: Expected marshmallow class, but `<class …
```
=> Fixed race condition in schema validation

ludwig/api.py, ludwig/collect.py, ludwig/data/dataset/ray.py, ludwig/evaluate.py, ludwig/experiment.py, ludwig/hyperopt/run.py, ludwig/hyperopt_cli.py, ludwig/predict.py, ludwig/preprocess.py, ludwig/train.py, tests/integration_tests/test_cli.py, tests/integration_tests/test_horovod.py
PyTorch expects `gpu_memory_limit` to be given as the fraction `[0, 1]` of GPU memory to use, not the total amount of GPU memory. We were honoring this correctly in the API (and Hyperopt), but not on the CLI, which was rejecting float values:
```
ludwig train: error: argument -gml/--gpu_memory_limit: invalid int value: '0.5'
```
=> Fixed --gpu_memory_limit in CLI to interpret as fraction of GPU memory

.actrc, .github/workflows/pytest.yml
Testing the `act` CLI tool for running pytest locally.  This PR adds configuration to run our github actions using the `ludwigai/ludwig-ray` docker image. 
To try this out:
1. Install act
https://github.com/nektos/act
2. Run tests
From the ludwig project root:
`act -j pytest`
=> Add support for running pytest github action locally with act

ludwig/schema/defaults/utils.py, tests/ludwig/schema/test_validate_config_misc.py
Forgot to switch the registry the defaults is composed of in the [defaults factor PR](https://github.com/ludwig-ai/ludwig/pull/2628). This fixes that mistake and improves the test so it will catch it next time.
=> Switch defaults to use mixins and improve test

tests/regression_tests/benchmark/configs/adult_census_income.gbm.yaml, tests/regression_tests/benchmark/configs/ames_housing.gbm.yaml, tests/regression_tests/benchmark/configs/mercedes_benz_greener.gbm.yaml, tests/regression_tests/benchmark/configs/sarcos.gbm.yaml
Regression test configs for gbm had the `model_type` defined in their configs by the key `type`. Switched that to the proper parameter to fix the CI failures.
=> Fix Regression Test Configs

.github/workflows/pytest.yml
Testing to see if this behaves correctly in github runner, because this fixes a bug in act. 
`always() && ${{ !env.ACT }}` always runs upload in `act`, which fails without an upload url and access token, while
`${{always() && !env.ACT }}` correctly skips upload when running `act`
=> Testing always() inside expansion in condition

ludwig/hyperopt/execution.py, ludwig/hyperopt/run.py, tests/integration_tests/test_hyperopt_ray.py
This update makes three changes to hyperopt in Ludwig:
1.  Adds the `tune_callbacks` parameter to hyperopt to allow passing [Ray Tune Callbacks](https://docs.ray.io/en/latest/tune/api_docs/internals.html#callbacks) into Ray Tune
2. Updates the logic of the RayTuneExecutor to pass the callbacks into Ray Tune
3. Logs user-supplied and rendered model configs to trial logdirs
These changes support error surfacing, as well as #2343 and #2344
=> Allow Ray Tune callbacks to be passed into hyperopt and log model config

ludwig/utils/numerical_test_utils.py, tests/ludwig/models/test_training_determinism.py, tests/ludwig/utils/test_numerical_test_utils.py
If nans appear in metrics, the equality check fails `(nan == nan) == False`, but this gives an error which may be misleading.
This adds checks for nans and infinite values first, and provides an informative error message showing where the nan was encountered
=> Check for nans before testing equality in test_training_determinism

ludwig/schema/trainer.py
validator was set up incorrectly and effectively blocked usage of such parameter.
This reverts the functionality as it was before.
=> Fix validator for reduce_learning_rate_on_plateau

ludwig/error.py, tests/ludwig/utils/test_errors.py
This results in Ray being unable to surface the error to the user when sending it back to the driver from the worker processes.
See https://stackoverflow.com/questions/49715881/how-to-pickle-inherited-exceptions
=> Fix InputDataError to be serializeable

ludwig/backend/ray.py, ludwig/explain/captum.py, ludwig/explain/captum_ray.py, ludwig/explain/explainer.py, ludwig/explain/gbm.py, ludwig/hyperopt/execution.py, tests/integration_tests/test_explain.py
- Adds `RayIntegratedGradientsExplainer` to do label-parallel explanations (as datasets tend not to be the bottleneck in most cases)
- Adds support for doing global explanations, which returns a single explanation in the list: the mean explanation across all rows
- Sets `max_calls=1` for Ray tasks that use GPUs due to https://docs.ray.io/en/latest/ray-core/tasks/using-ray-with-gpus.html?highlight=max_calls#workers-not-releasing-gpu-resources
=> Adds Ray implementation of IntegratedGradientsExplainer that distributes across cluster resources

ludwig/schema/metadata/trainer_metadata.py
=> Fix example values for max_batch_size in trainer parameter metadata

ludwig/schema/metadata/feature_metadata.py
Fix incorrect internal_only flags on audio feature metadata
=> Fix incorrect internal_only flags on audio feature metadata

ludwig/datasets/configs/customer_churn_prediction.yaml, ludwig/datasets/configs/telco_customer_churn.yaml
adds two kaggle datasets
- https://www.kaggle.com/datasets/blastchar/telco-customer-churn
- https://www.kaggle.com/competitions/customer-churn-prediction-2020
=> add customer churn datasets

ludwig/datasets/configs/allstate_claims_severity.yaml, ludwig/datasets/configs/mercedes_benz_greener.yaml, ludwig/datasets/configs/otto_group_product.yaml, ludwig/datasets/configs/porto_seguro_safe_driver.yaml, ludwig/datasets/configs/santander_customer_satisfaction.yaml, ludwig/datasets/configs/santander_customer_transaction.yaml, ludwig/datasets/loaders/allstate_claims_severity.py
Adds missing test splits from a number of Kaggle datasets.
=> Add Kaggle test splits

ludwig/automl/automl.py, ludwig/automl/base_config.py, ludwig/utils/dataset_utils.py
Also adds `dataset_utils.get_repeatable_train_val_test_split` as public API, since it is referenced in the AutoML user guide.  https://ludwig.ai/latest/user_guide/automl/
=> Adds DeveloperAPI and PublicAPI annotations to AutoML

ludwig/benchmarking/utils.py
used in `model_baselines/utils.py` in Predibase.
=> Adds annotation to download_one method in benchmarks

.pre-commit-config.yaml, ludwig/data/dataframe/dask.py
This PR adds a custom implementation of `to_dask()` to ensure forward compatibility with Ray 2.0/Ray 2.1 schema inference. This ensures that Ray 2.1 will work correctly even with image/audio datasets.
=> Add custom to_dask() to infer Dask metadata from Datasets schema.

.github/workflows/pytest.yml, requirements_distributed.txt, requirements_hyperopt.txt
This PR drops support for Ray 1.x and moves Ludwig to Ray 2.0. It also ensures the CI uses Ray 2.0 for all of Ludwig's tests.
=> Bump Ludwig to Ray 2.0

.github/workflows/pytest.yml
Ludwig will upgrade to Ray 2.1 in #2709, and a separate PR will upgrade Ludwig to ray-nightly.
=> Downgrade to Ray 2.0 in CI to get green Ludwig CIs again.

ludwig/modules/recurrent_modules.py
Multiply the `output_size` by two if the RNN is bidirectional
=> Fix https://github.com/ludwig-ai/ludwig/issues/1735

docker/ludwig-ray-gpu/Dockerfile, docker/ludwig-ray/Dockerfile
Existing Ray base image seems to have an invalid version of NCCL for CUDA 11.6:
```
>>> import torch
>>> torch.__version__
'1.13.0+cu116'
>>> torch.cuda.is_available()
True
>>> import horovod.torch as hvd
>>> hvd.init()
>>> torch.tensor([1])
tensor([1])
>>> t = torch.tensor([1])
>>> hvd.allreduce(t)
tensor([1])
>>> t = t.to("cuda")
>>> t
tensor([1], device='cuda:0')
>>> hvd.allreduce(t)
File "/home/ray/anaconda3/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 1253, in synchronize
mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: ncclCommInitRank failed: unhandled cuda error
During handling of the above exception, another exception occurred:
File "<stdin>", line 1, in <module>
File …
```
=> Downgrade to PyTorch 1.12.1 in Docker to due to NCCL + CUDA compatibility

ludwig/schema/trainer.py, ludwig/schema/utils.py
Simplifies impl. and adds optional `allow_none` and default-value validation back to this field.
=> fix: refactor `IntegerOptions` field

ludwig/schema/metadata/parameter_metadata.py, ludwig/schema/utils.py, tests/ludwig/schema/test_validate_config_misc.py
I also removed the `deepcopy` call that occurred when metadata dicts are serialized because it is unnecessary.
=> fix: Fix metadata object-to-JSON serialization for oneOf fields and add full schema serialization test.

ludwig/schema/optimizers.py, ludwig/schema/utils.py
Small QoL enhancement that I think is worth it to cut down on repetitiveness. Currently only used in the optimizer schemas as a POC.
=> refactor: Add `ProtectedString` field (alias of `StringOptions` that only allows one string)

ludwig/contribs/mlflow/__init__.py, ludwig/contribs/mlflow/model.py
Upgrades `_get_or_create_experiment_id`, `log_saved_model` to developer API.
Makes MLFlowCallback Public API, for consistency with other callbacks.
=> Annotate MLFlow callback, and utility functions

ludwig/trainers/base.py, ludwig/trainers/trainer.py
Previously, GBM trainers lacked this property. In the future, we should figure out a way to get this info from the GBM workers, as some of them may be running on the same node, so it would be useful to know which ones are.
=> Add local_rank to BaseTrainer

ludwig/features/binary_feature.py, ludwig/features/category_feature.py, ludwig/features/number_feature.py, ludwig/features/sequence_feature.py, ludwig/features/set_feature.py, ludwig/features/text_feature.py, ludwig/features/vector_feature.py, ludwig/schema/features/base.py, ludwig/schema/features/binary_feature.py, ludwig/schema/features/category_feature.py, ludwig/schema/features/number_feature.py, ludwig/schema/features/sequence_feature.py, ludwig/schema/features/set_feature.py, ludwig/schema/features/text_feature.py, ludwig/schema/features/vector_feature.py
This is part 1 of the broken up hyperopt schema PR (https://github.com/ludwig-ai/ludwig/pull/2346).
It moves the definition of a feature's metric function definitions from that feature's class to its config. This seems to make more sense overall and it is necessary to populate the JSON schema for the output feature metric section of the hyperopt config.
=> feat: Hyperopt schema v0, part 1: Move output feature metrics from feature classes to feature configs.

ludwig/api.py
Previously the callback functions `on_preprocess_start` and `on_preprocess_end` were called only from within `model.train()`. This PR moves these callback invocations to within the `model.preprocess()` call itself.
=> Move preprocess callbacks inside model.preprocess

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_text_encoders.py
This PR fixes an issue where `reduce_output==cls_pooled` was causing index out-of-range errors. This happens because the MT5Encoder doesn't have `pooler_outputs` returned from the Transformer. 
As a part of this PR, I reviewed all of the outputs for each of the text encoders to ensure that we only support `cls_pooled` for compatible text encoders, and log errors in cases where it doesn't work for that particular encoder.
This also adds a test for XLNetEncoder, which was missing.
=> Ensure correct output reduction for text encoders like MT5 and add warning messages when not supported

ludwig/models/base.py
@dantreiman found a bug where we were adding our losses twice by accident. This PR makes sure this doesn't happen anymore. 
As @w4nderlust expressed, this change may warrant a 0.6.5 release.
=> Fix double counting of training loss

ludwig/schema/utils.py
Lets `min` and `max` be optional kwargs on `FloatTupleMarshmallowField` (currently, you are forced to provide them or otherwise except [0,1] as your range).
=> feat: Hyperopt schema v0, part 3: Enable optional min/max support for `FloatTupleMarshmallowField` fields

ludwig/utils/data_utils.py, ludwig/visualize.py
This PR adds two new utility functions:
1. `read_buffer`: Reads data in from a buffer `buf` after writing the data from a buffer to a temporary file, and then processes it based on its format (hdf5, csv, tsv etc)
2. `read_fname`: This function reads data from `fname` using the `df_lib` data processing library (defaults to pandas)
=> Add new data utility functions for buffers and files, and rename registry

ludwig/data/preprocessing.py
Running experiments in parallel, sometimes I run into an error where saving the data as a 
parquet file fails (perhaps there's a duplicate or pre-existing file).
Perhaps it's reasonable to catch the exception and log a warning, simply skipping saving preprocessed data, and continuing to proceed to training, rather than crashing.
=> Proceed with model training even if saving preprocessed data fails.

ludwig/data/preprocessing.py, ludwig/data/utils.py, ludwig/utils/backward_compatibility.py, ludwig/utils/version_transformation.py
Ludwig users can pass pre-split data to `LudwigModel.train()` using via `model.train(training_set=..., valdiation_set=..., test_set=...)`. In preprocessing, we understand this to be the user using a fixed split.
At the moment, all users using `LudwigModel.train()` in this way get a warning about their preprocessing split configuration getting ignored. However, the `split` configuration may be entirely unspecified, set by the schema by default `(0.7, 0.2, 0.1)`.
I've removed this warning entirely, as it seems rare that a user using a fixed split would explicitly specify a different data split policy in their config, or be surprised/confused when that policy is simply ignored (they are using a fixed split).
There are additional internal-only parameters that live at the config feature-level …
=> Improve warnings about backwards compatibility and dataset splitting.

ludwig/api.py, ludwig/trainers/trainer.py, tests/integration_tests/test_experiment.py
If training fails during the first epoch, then `training_progress.json` will be missing and `training_checkpoints` will not have the `latest.ckpt` file. In this case, Ludwig throws errors. However, it might be better to indicate that model resumption failed, and that a fresh model training run is being created.
=> Start fresh training run if files for resuming training are missing

ludwig/data/dataset/ray.py, ludwig/trainers/trainer_lightgbm.py, tests/integration_tests/test_trainer.py
This PR adds a `repartition` method to `RayDataset` and updates `LightGBMRayTrainer` to use `RayDataset.repartition` rather than accessing the underling dataset object. Additionally, it adds tests to ensure `LightGBMRayTrainer` repartitions data only if the number of blocks in the RayDataset is less than the number of actors. This addresses an error that can occur during distributed training (`AttributeError: 'Dataset' object has no attribute 'ds' (type: RayTaskError(AttributeError), retryable: true`).
=> LIghtGBMRayTrainer repartition datasets with fewer blocks than Ray actors

ludwig/features/number_feature.py, ludwig/schema/features/preprocessing/number.py, tests/ludwig/utils/test_normalization.py
This PR adds a new normalization method for numeric features called `InterQuartileTransformer`, which removes the median and scales the data according to the interquartile range. The resulting data has a zero mean and median and a standard deviation of 1, and it is not skewed by outliers (the outliers are still present with the same relative relationships to other values).
This effectively implements https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html, which is useful in cases where numeric features have large outliers that skew the distribution that emerges post min-max normalization.
This can be set in Ludwig by specifying `iq` as the normalization method in number feature preprocessing
=> Add InterQuartileTransformer normalization strategy for Number Features

ludwig/data/negative_sampling.py, tests/ludwig/data/test_negative_sampling.py
Adds Pandas implementation for negative sampling to ludwig.data. This can be used for creating recommendation system datasets from implicit feedback datasets (e.g. customer transactions).
=> Add negative sampling to ludwig.data

ludwig/combiners/combiners.py, ludwig/decoders/registry.py, ludwig/encoders/registry.py, tests/ludwig/combiners/test_combiners.py
This PR creates accessor methods for encoder and decoder registries and uses the DeveloperAPI annotation. This will be the best way to retrieve these registries in the future. 
I've made the original variable paths private because there's no good way to remove them without breaking the logic where we instantiate a registry and incrementally register things.
=> [Annotations] Encoder and Decoder Registries

ludwig/constants.py, ludwig/schema/__init__.py, ludwig/schema/model_config.py, tests/ludwig/schema/test_validate_config_misc.py
By setting `additionalProperties` to `False` at the top level of the schema, a user is prevented from entering erroneous values like `type` instead of `model_type` (or from otherwise making typos for top-level keys).
=> fix: Restrict allowed top-level config keys

ludwig/data/split.py
Stratified splitting requires at least two examples of each split class for each split created. If too few examples exist, sklearn throws `ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.` This exception is somewhat difficult to interpret, so this PR updates the description of the error and offers remediation suggestions.
=> Update stratified split with a more specific exception for underpopulated classes

ludwig/automl/automl.py, ludwig/automl/base_config.py, ludwig/utils/image_utils.py, pytest.ini, tests/integration_tests/test_automl.py
This PR makes the following changes
- Removes `features_metadata` as a returned value from `_create_default_config` and as an argument of `_model_select`
- Merges text feature default config into base config while iterating over features 
- Update docstring for `_create_default_config `
- Remove warnings from image utils's `is_image` function in case of AttributeErrors
- Filter `DeprecationWarning` in pytest
- Add test coverage for `_create_default_config` for small tabular, large tabular, image, text and multi modal datasets.
Fixes MLI-206
=> Fix key error in AutoML model select

ludwig/data/batcher/random_access.py, ludwig/data/dataset/ray.py, ludwig/models/predictor.py, ludwig/trainers/trainer.py
This PR implements logic to drop the last batch for Pandas and Ray dataset batchers to prevent issues when there is only 1 row in a batch. 
A single row in a batch causes issues when computing Batchnorm (such as in FC layers, Tabnet, etc.) because it can't compute the mean/stddev for a single sample. Additionally, Ludwig has some logic for Tabnet that has a conditional check for sample_size == 1 that we can now safely remove.
Skipping adding tests since our current test suite already has tests that use the batcher classes for model training, so if the tests pass, then this logic should work as well. I modified individual tests locally to be sure.
Note: This only drops incomplete training batches if the batch size < total number of rows in the dataset. Additionally, it will always keep …
=> Drop incomplete batches for Ray and Pandas to prevent Batchnorm computation errors

ludwig/api.py, tests/integration_tests/test_preprocessing.py, tests/integration_tests/test_ray.py
In the existing implementation of `model.preprocess`, if there is an error or exception thrown, we never get to see it because  of the way our try-except-finally block is written. 
In particular, when preprocessing fails, the variables returned from `preprocess_for_training` aren't set/don't exist in scope during the finally block, which causes an `UnboundLocalError` for referencing a variable before definition. 
This PR updates the implementation to catch the exception and issue a RuntimeError since model training can never succeed if preprocessing the data itself fails.
=> Catch and surface Runtime exceptions during preprocessing

ludwig/schema/split.py, ludwig/schema/utils.py, tests/ludwig/schema/test_validate_config_misc.py
As far as I can tell this line was too extensive for split configs, and it was responsible for the `column` fields being removed. I changed the function so that it only redacts `type`.
This is what the keys looked like before and after the original call to `remove_duplicate_fields`:
```
odict_keys(['type', 'column', 'probabilities'])
odict_keys(['probabilities'])
```
=> fix: Add back missing split fields

ludwig/schema/encoders/text_encoders.py
Adds the `max_sequence_length` type to the encoder dataclass for the text encoder `RoBERTa`
fixes #2851
The current unit test for this encoder already includes `max_sequence_length` as a parameter so a passing test should indicate whether this is working correctly or not: https://github.com/ludwig-ai/ludwig/blob/master/tests/ludwig/encoders/test_text_encoders.py#L73
=> text_encoder: RoBERTa max_sequence_length

ludwig/schema/metadata/trainer_metadata.py, ludwig/schema/trainer.py, ludwig/trainers/trainer.py, tests/integration_tests/test_trainer.py
Usage:
```
trainer:
use_mixed_precision: true
```
In our tests fine-tuning BERT with 8 Ampere GPUs, we found a 2.2x speedup using mixed precision training with similar convergence properties.
=> Add support for automatic mixed precision (AMP) training

ludwig/models/base.py, ludwig/schema/trainer.py, ludwig/trainers/trainer.py, tests/integration_tests/test_model_save_and_load.py, tests/integration_tests/test_model_training_options.py
This PR dramatically speeds up training for large datasets that take hours to train. In the previous implementation, `evaluate_training_set` defaulted to `True`, which meant that at the start of every evaluation phase (e.g., at the end of each epoch) there would be a pass over the training set again to compute the train metrics. In practice, this ends up being about 30 - 35% of the total training wall clock time. In other words, if your training process took 3 hours to run, you could save an entire hour by disabling this evaluation phase.
Instead of computing training metrics in a separate pass, we can do it during the training loop that updates the model weights, at the end of the forward / backward pass, which is what this PR now does when `evaluate_training_set` is `False` (the new …
=> Evaluate training set in the training loop

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_text_encoders.py
Closes https://github.com/ludwig-ai/ludwig/issues/2851
=> Fixes for the roberta encoder: explicitly set max sequence length, and fix output shape computation

ludwig/data/split.py, tests/ludwig/data/test_split.py
This PR enables using stratified split even when we have a training example with cardinality = 1 in the column we're splitting on. It achieves this by separating out the examples with cardinality = 1, splitting as usual (stratified) then appending these items back to the dataframe.
=> support stratified split with low cardinality features

ludwig/utils/nlp_utils.py, tests/ludwig/utils/test_tokenizers.py
`nlp_pipeline.tokenizer(text)` only loads the spacy tokenizer, not the full model. This causes `EnglishLemmatizeFilterTokenizer` to return a list of empty strings since inferring the lemmas requires the model not just the tokenizer.
=> fix: load spacy model for lemmatization in `EnglishLemmatizeFilterTokenizer` to work

tests/integration_tests/test_class_imbalance_feature.py, tests/integration_tests/test_ray.py, tests/integration_tests/utils.py
This PR sets the number of training workers to 1 (from 2) to speed up our Ray tests.
=> Set RayBackend Config to use single worker for tests

.github/workflows/docker.yml, docker/ludwig-ray-gpu/Dockerfile, docker/ludwig-ray/Dockerfile, requirements.txt
This PR bumps the ludwig-ray and ludwig-ray-gpu images to Torch 1.13.1 and Cuda 11.6.
It also pins `psutil` to `5.9.4`
=> Ray GPU image with Torch 1.13 support

ludwig/models/gbm.py, ludwig/schema/trainer.py, ludwig/trainers/trainer_lightgbm.py, tests/integration_tests/test_gbm.py, tests/integration_tests/test_model_save_and_load.py
During GBM training, we intermittently run an eval step for metrics reporting and early stopping detection. Based on a benchmarking sweep over eval batch sizes using two 1GB datasets (Criteo 1GB and HIggs) it was determined that native LightGBM eval outperformed Hummingbird-compiled pytorch models. This update refactors the in-training eval step to use LightGBM's sklearn interface and updates the default eval batch size to 1,048,576 (which should in many cases encompass the validation and test sets). Additionally, eval on the training set is now disabled by default.
=> Use native LightGBM for intermittent eval during training

ludwig/models/gbm.py, ludwig/trainers/trainer_lightgbm.py
GBM models save during training if one of two conditions is met:
1. [No validation set was provided](https://github.com/ludwig-ai/ludwig/blob/gbm-not-saved/ludwig/trainers/trainer_lightgbm.py#L317-L329)
2. [The model improved since the last evaluation](https://github.com/ludwig-ai/ludwig/blob/gbm-not-saved/ludwig/trainers/trainer_lightgbm.py#L421-L429)
If neither condition is met--no validation set and the model never improved--the GBM will never be saved, and a `FileNotFoundError` is thrown [when loading the best model after training](https://github.com/ludwig-ai/ludwig/blob/gbm-not-saved/ludwig/trainers/trainer_lightgbm.py#L688-L690).
This update adds a method to check whether or not the GBM has been saved, and a post-training check that saves the model if it was never saved.
=> Save GBM after training if not previously saved

ludwig/explain/captum.py
This is a bandaid fix for old models using the token level explanations. Training set metadata from ludwig models 0.5 and older have old keys that need to be swapped out with some backwards compatibility logic:
"pad_idx" --> "word_pad_idx"
"idx2str" --> "word_str2idx"
There are others that should be changed as well to avoid some of these issues in the future. This PR will fix the current failure but the longterm fix should be the addition of some backwards compatibility logic.
=> Fix TLE - Pt. 2

ludwig/contribs/mlflow/__init__.py, tests/integration_tests/test_mlflow.py
Fixes #2891.
With this change, if `mlflow.active_run()` already exists when the `MLFlowCallback` is created, then we will not attempt to create a new run, but rather log all artifacts to the existing active run.
=> Support MLFlowCallback logging to an existing run

ludwig/data/dataset_synthesizer.py, tests/ludwig/utils/test_data_utils.py
Turns out this was just an issue with the dataset synthesizer. The dataset synthesizer groups input and output features together as one group of features and then checks whether there is an encoder or decoder present on each feature. If there is not, then by default it adds an encoder. This causes a problem when there is an output feature without a decoder specified since it creates an encoder entry on the decoder with a structure like this:
`{
'name': 'product', 
'type': 'category', 
'decoder': {'encoder': {'idx2str': ['oXpJUe', 'fmzl', 'xZFbGsbW', 'YlUXGspxB', 'lru', 'wtQppfKBo', 'XgIhvyQg', 'wcvA', 'oVWamB', 'zZJjV'], 'vocab_size': 10}},
'column': 'product', 
'proc_column': 'product_mZFLky'
}`
I created a quick check in the dataset synthesizer that adds a decoder to output features …
=> Fix dataset synthesizer

ludwig/trainers/trainer_lightgbm.py, tests/integration_tests/test_gbm.py
When prepping data for GBM training/eval, column names with invalid characters may cause `lightgbm.Dataset` to throw the following error:
```
lightgbm.basic.LightGBMError: Do not support special JSON characters in feature name.
```
This update catches the `LightGBMError` and provides more descriptive feedback.
=> Add a clear error message about invalid column names in GBM datasets

ludwig/utils/visualization_utils.py
Before:
Now:
Changes:
- Changed cmap from viridis to pastel1 to ensure that annotated text (cm numbers) can always be seen. Pastel has lighter colors only so ensures that this happens.
- Rotate y-axis labels to be consistent with the x-axis
- Adds confusion matrix number annotations inside the confusion matrix plot with a medium font-weight (can change this to normal if it's too much)
=> Annotate Confusion Matrix with updated cmap

ludwig/utils/visualization_utils.py
This PR uses a heuristic to resize confusion matrix and f1 plots to prevent labels getting smushed. 
Before:
Now:
=> Dynamically resize confusion matrix and f1 plots

examples/titanic/simple_model_training.py
I often use the titanic example to test local changes. Making some modifications here to make it a bit more convenient to use and avoid producing vestigial files.
=> Simplify titanic example to read config in-line, and skip saving processed input.

ludwig/models/ecd.py, ludwig/utils/state_dict_backward_compatibility.py, tests/ludwig/utils/test_state_dict_backward_compatibility.py
Quick fix for loading modules with pre-trained encoders which were saved prior to the addition of FreezeModule (https://github.com/ludwig-ai/ludwig/pull/2855).
=> Adds quick fix for pretrained models not loading by modifying state_dict keys on load.

requirements.txt
With https://github.com/ludwig-ai/ludwig/pull/2408 merged in, we now need torchvision at `>=0.14.0` due to some vision models not being available in previous versions. Specifically, there's a model called `maxvit_t` that's being imported on line 349 of `image_torchvision_encoders.py` which isn't available until `0.14.0`. For compatibility sake we may need to pin the other torch dependencies to `>=0.13.0`.
Looks like torch `0.13.0` has a [vulnerability](https://devhub.checkmarx.com/cve-details/CVE-2022-45907/?utm_source=jetbrains&utm_medium=referral&utm_campaign=pycharm&utm_term=python) so I pinned to `0.13.1`.
=> Pin torchvision to 0.14

ludwig/schema/model_config.py, ludwig/schema/trainer.py, ludwig/trainers/trainer_lightgbm.py, tests/integration_tests/test_hyperopt.py, tests/ludwig/hyperopt/test_hyperopt.py
- `_set_hyperopt_defaults` was assuming ECD models (due to setting `epochs`, vs `num_boost_round` for GBM)
- added basic GBM tests to our hyperopt integration test suite
=> Hyperopt invalid GBM config

ludwig/contribs/mlflow/__init__.py, tests/integration_tests/test_mlflow.py
In the previous implementation, we pull the tracking URI from the environment every time we change context, which can result in inconsistent behavior if, for example, the current working directory changes and no external MLFlow service is being used.
=> Store mlflow tracking URI to ensure consistency across processes

ludwig/utils/fs_utils.py, tests/ludwig/utils/test_fs_utils.py
Adds a companion method `safe_move_directory` to fs_utils which is inspired by `safe_move_file`.
=> Adds safe_move_directory to fs_utils

ludwig/utils/visualization_utils.py
**Confusion Matrix:**
1. Set minimum height and width to prevent plot from shrinking beyond a certain size
2. Changed colors to blues with slight alpha gradient so that there's a gradient coloration on the plot
Before:
Now:
Before:
Now:
**Brier Plot**
1. Set minimum height and width to prevent plot from shrinking beyond a certain size
2. Dynamic resize width and height
Before:
Now (it will adjust dynamically, this plot just shows 2 models overlaid on the same chart):
**F1 Score Plot**
1. Set minimum height and width to prevent plot from shrinking beyond a certain size
2. Dynamic resize width and height
Before:
Now (height is also dynamically adjusted):
=> Dynamic resizing for Confusion Matrix, Brier, F1 Plot, etc.

ludwig/models/base.py, ludwig/models/gbm.py, ludwig/schema/trainer.py, ludwig/trainers/trainer_lightgbm.py, ludwig/utils/gbm_utils.py, requirements_tree.txt, tests/integration_tests/test_explain.py, tests/integration_tests/test_gbm.py, tests/integration_tests/test_model_save_and_load.py, tests/integration_tests/test_torchscript.py, tests/integration_tests/test_trainer.py
Complement to https://github.com/ludwig-ai/ludwig/pull/2856
=> Evaluate training set in the training loop (GBM)

ludwig/automl/base_config.py, ludwig/schema/__init__.py, ludwig/utils/automl/type_inference.py, tests/integration_tests/test_automl.py, tests/ludwig/schema/test_validate_config_misc.py, tests/ludwig/utils/automl/test_type_inference.py
Many tabular datasets have text features that aren't particularly informative like "name", which are really just unique identifiers, but tricky to identify as such (as they can contain more than one word).
This PR adds heuristics to filter out such fields under the assumption that they occur primarily when there are many other fields and when the number of average words per field is low.
=> [automl] Exclude text fields with low avg words

ludwig/encoders/text_encoders.py, ludwig/utils/hf_utils.py, ludwig/utils/tokenizers.py, tests/ludwig/utils/test_hf_utils.py
This adds a utility function to download pretrained HuggingFace models with retry on download failure. Calls to from_pretrained in text encoder and tokenizer classes have been replaced with calls to the utility.
=> Retry HuggingFace pretrained model download on failure

ludwig/modules/metric_modules.py
Prior to #2901, ROC metrics weren't registered for category features. This PR un-registers the ROC metric with the category feature, as using the ray backend with them throws a strange error.
=> Disable AUROC for CATEGORY features.

ludwig/schema/trainer.py, tests/integration_tests/test_gbm.py
Training a GBM with `boosting_type=rf` leads to the following error:
`lightgbm.basic.LightGBMError: RF mode do not support custom objective function, please use built-in objectives.`
We currently pass a custom objective function into LGBM training, and this can be deactivated in the code. However, doing so leads to the following error:
`lightgbm.basic.LightGBMError: Check failed: (train_data->metadata().init_score()) == (nullptr) at /private/var/folders/8r/s_bsn5kj3fv6dr7l58slg48r0000gn/T/pip-install-_ygu6ap_/lightgbm_9c96da0ed3b24382834b859f69313149/compile/src/boosting/rf.hpp, line 44 .`
This error occurs because RF GBMs  do not support model reloading, and we rely on model checkpointing for in the loop performance reporting. It can be overcome by setting `num_boost_rounds < …
=> Deactivate GBM random forest boosting type 

ludwig/trainers/trainer_lightgbm.py, tests/integration_tests/test_gbm.py
Bagging is not compatible with LightGBM's GOSS boosting type, and a config with `boosting_type: goss` and `bagging_freq > 0` will throw the following liblightgbm error:
`lightgbm.basic.LightGBMError: Cannot use bagging in GOSS`
This update had the trainer automatically set `bagging_freq: 0` when using GOSS.
=> Disable bagging when using GOSS GBM boosting type

ludwig/utils/backward_compatibility.py
A Ludwig model from before #2408 failed to `preprocess_for_prediction`:
```python-traceback
File /workspaces/ludwig/ludwig/features/image_feature.py:479, in ImageFeatureMixin._finalize_preprocessing_parameters(preprocessing_parameters, encoder_type, column)
475 assert isinstance(num_channels, int), ValueError("Number of image channels needs to be an integer")
477 average_file_size = np.mean(sample_num_bytes) if sample_num_bytes else None
--> 479 standardize_image = preprocessing_parameters["standardize_image"]
480 if standardize_image == "imagenet1k" and num_channels != 3:
481     warnings.warn(
482         f"'standardize_image=imagenet1k' is defined only for 'num_channels=3' but "
483         f"detected 'num_channels={num_channels}'.  For this situation setting …
```
=> Add missing standardize_image key to metadata

ludwig/explain/captum.py
If `model.config_obj.preprocessing.sample_ratio` was set for a model, it was also applied to the explanation input. For small input sizes, this could result in empty explanation inputs.
Resolution: reset sample_ratio to 1.0 before preprocessing explanation inputs.
=> Integrated Gradients: reset sample_ratio to 1.0 if set

.github/workflows/pytest.yml
Increase CI pytest timeout from 60 minutes to 75 minutes and the overall time from 80 to 90 minutes.
=> Increase CI pytest time out to 75 minutes

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_text_encoders.py
The call to `load_pretrained_hf_model` was failing because we didn't use ** so it treated it as a positional argument, which didn't meet the function definition. This change fixes it!
I also double-checked this for all of the other text encoders and it looks like it should work correctly. Just this one has the error.
=> Fixes longformer encoder by passing in pretrained_kwargs correctly

ludwig/trainers/trainer_lightgbm.py, tests/integration_tests/test_gbm.py
Setting `boosting_type: dart` leads to the following error iff an epoch ends with no model improvement:
``` 
File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/trainers/trainer_lightgbm.py", line 456, in check_progress_on_validation
last_improvement_in_steps = progress_tracker.steps - progress_tracker.best_eval_metric_steps
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```
This error is caused by an inconsistency in updating `progress_tracker.best_eval_metric_steps` coupled with DART's incompatibility with the LGBM early stopping callback. LGBM models keep track of the best observed step in `model.best_iteration_`, however this only happens when the early stopping callback is used; otherwise, `best_iteration_` is always `None`. Since DART does not use early …
=> GBM DART boosting type incopatible with early stopping

tests/integration_tests/test_ray.py
This is a flaky test, skipping for now. 
I run into mismatch delayed errors. 
```
ValueError: Metadata mismatch found in `from_delayed`.
Partition type: `pandas.core.frame.DataFrame`
+----------------------------+--------+----------------------------------------+
| Column                     | Found  | Expected                               |
+----------------------------+--------+----------------------------------------+
| 'set_57C49_predictions'    | object | TensorDtype(shape=(4,), dtype=int64)   |
| 'set_57C49_probabilities'  | object | TensorDtype(shape=(4,), dtype=float32) |
| 'vector_C1424_predictions' | object | TensorDtype(shape=(5,), dtype=float32) |
+----------------------------+--------+----------------------------------------+
``` …
=> Skip test_ray_outputs

ludwig/utils/tokenizers.py, tests/ludwig/utils/test_tokenizers.py
Prior to this PR, Ludwig assumed that all custom HuggingFace BERT models have `tokenizer_config.json` in their repository. This is not the case, particularly for these two models:
- https://huggingface.co/bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12
- https://huggingface.co/emilyalsentzer/Bio_ClinicalBERT
We wrap the attempt to get `tokenizer_config.json` in a try-except block and default to an empty configuration if it does not exist.
=> Enable custom HF BERT models with default tokenizer config

ludwig/schema/encoders/text_encoders.py
XLM doesn't support `cls_pooled` as a `reduce_output` strategy
=> Set reduce_output to sum for XLM encoder

ludwig/hyperopt/run.py, ludwig/schema/hyperopt/scheduler.py, ludwig/schema/model_config.py, ludwig/schema/utils.py, tests/integration_tests/test_automl.py, tests/integration_tests/test_hyperopt.py, tests/integration_tests/test_hyperopt_ray.py, tests/integration_tests/test_hyperopt_ray_horovod.py, tests/ludwig/utils/test_defaults.py
This PR adds a new step to ensure that all of the defaults for search algorithm, split, executor etc. are correctly populated using the schema object before accessing them to prevent key errors. All of these parameters are required by hyperopt and expected to be present downstream for config validation, executor creation, and trial execution.
The reason we've not noticed this before in our tests is because all of our tests specify `search_alg` in the hyperopt config. 
Co-authored-by: Kabir Brar <kabir@predibase.com>
Co-authored-by: Travis Addair <tgaddair@gmail.com>
=> Populate hyperopt defaults using schema

ludwig/schema/encoders/text_encoders.py, requirements.txt
This reverts commit 12204ba2361d8b6519aac278528a4adcbc24c8c2.
=> Revert "Add sentencepiece as a requirement for MT5 text encoder (#2967)" and disable MT5 Encoder

ludwig/hyperopt/execution.py, ludwig/hyperopt/run.py, ludwig/hyperopt/utils.py, tests/integration_tests/test_hyperopt.py, tests/ludwig/hyperopt/test_hyperopt.py
This allows us to pipe credentials to _get_best_checkpoint_dir and ensure that we can load/download artifacts from remote URIs where credentials are needed (and don't exist in the environment variables / explicitly passed in through the Ludwig config)
=> [Hyperopt] Modify _get_best_model_path to grab it from the Checkpoint object with ExperimentAnalysis

ludwig/schema/trainer.py, tests/integration_tests/test_gbm.py
Leads to `lightgbm.basic.LightGBMError: Number of class for initial score error`. Disabling until we have capacity to support non-default boosting types
=> GBM: disable goss boosting type

ludwig/hyperopt/utils.py, ludwig/schema/hyperopt/executor.py, ludwig/schema/model_config.py, tests/ludwig/hyperopt/test_hyperopt.py
This PR sets the default `num_samples` to None, and then infers a value for it (either 1 or 10) based on the parameters search space passed into hyperopt. 
In particular, when there are parameters with grid search, we want to prevent duplication of trials because grid search creates all possible combinations of trials using the discrete values in the space, so we set the num_samples to 1 to prevent this duplication. 
If the parameter space doesn't contain any grid search parameters, there is no chance of duplication and we can safely set the default value to 10 (like we were before). 
This will continue to respect user's choices if they are set in the config.
Note: We don't currently have a `hyperopt.yaml` in `ludwig/schema/metadata` so there's nothing else to update. I will follow this …
=> [Hyperopt] Set default num_samples based on parameter space

ludwig/schema/utils.py
This is an interesting little bug related to our marshmallow validation pattern (and marshmallow's looseness). Apologies for the length of this PR description, but I think the full context is helpful.
In @jimthompson5802 's latest attempt to add an `augmentation` parameter to image features that supports both `bool` and `list` values, he defined the parameter roughly as so:
```
augmentation: Union[bool, List[BaseAugmentationConfig]] = schema_utils.OneOfOptionsField(
default=False,
description="Augmentation configuration.",
field_options=[
schema_utils.Boolean(
default=False,
description="Whether to use augmentation or not.",
),
AugmentationContainerDataclassField(
feature_type=IMAGE,
default=[
{"type": "random_horizontal_flip"},
{"type": "random_rotate", "degree": 15},
]
)
]
)
```
Then, …
=> fix: Fix validation and serialization for `Boolean` and `OneOfOptionsField` fields

ludwig/features/audio_feature.py, tests/integration_tests/test_preprocessing.py
If `preprocessing.sample_ratio` is set, it's not guaranteed that the index-0 element will be included in the training data sub-sample.
Use `iloc` instead.
Tested (reproduced and fixed):
```python
import logging
import os
import tempfile
from tests.integration_tests.utils import generate_data, category_feature, audio_feature
with tempfile.TemporaryDirectory() as tmp_dir:
input_features = [audio_feature(folder=tmp_dir)]
output_features = [category_feature(output_feature=True)]
rel_path = generate_data(input_features, output_features, os.path.join(tmp_dir, "data.csv"), 1000)
config = {
"preprocessing": {"sample_ratio": 0.1},
"input_features": input_features,
"output_features": output_features,
"trainer": {"epochs": 2, "batch_size": 64},
}
model = …
```
=> Use iloc to fetch first audio value.

ludwig/hyperopt/execution.py
Always set this to False since it causes race conditions when using other callbacks like the MLFlow callback. It seems largely related to poor GC/actor clean up in Ray when re-using actors.
We can re-enable this in Ray 2.3 when we change the MLFlow callback initialization to use `setup_mlflow` instead of the `mlflow_mixin`.
=> Disable reuse_actors in hyperopt

ludwig/distributed/__init__.py, ludwig/distributed/ddp.py
```
backend:
trainer:
strategy: fsdp
```
=> Added FSDP distributed strategy

ludwig/contribs/mlflow/__init__.py, ludwig/data/dataset/base.py, ludwig/data/dataset/pandas.py, ludwig/data/dataset/ray.py, ludwig/data/sampler.py, ludwig/data/split.py, ludwig/models/predictor.py, ludwig/trainers/trainer.py
When `seed` was used i changed it to `random_seed`.
I also made sure type hints where there in the signature of the affected functions.
Finally i discovered there were two `default_random_seed` parameters in two separate files, I removed one and imported the other.
=> Cleaning up seed / random_seed usage discrepancy

tests/integration_tests/test_hyperopt_ray.py, tests/integration_tests/test_hyperopt_ray_horovod.py
1. Path has moved from `ray.tune.trial` to `ray.tune.experiment.trial` 
2. `pytest` tries to treat the `TestCallback` class as a test that it is unable to load, so I renamed it to `CustomTestCallback` so it doesn't try to treat it as a test.
=> Address some warnings when running hyperopt tests

ludwig/distributed/__init__.py
Because this function gets called many times on the critical path for each metric, it produces a lot of spam, and is not a very informative message.
=> Removed log spam from distributed loader

ludwig/hyperopt/execution.py
Need to yield instead of return since we're inside a context manager
=> [Hyperopt] Fix get_best_model_path

.github/workflows/pytest_benchmarks.yml, docker/README.md, docker/ludwig-ray-gpu/Dockerfile, docker/ludwig-ray/Dockerfile, examples/ray/kubernetes/clusters/ludwig-ray-cpu-cluster.yaml, examples/ray/kubernetes/clusters/ludwig-ray-gpu-cluster.yaml
This reverts commit 5bef6601217dbe0fda106b04e61bbea2ee19bfc2.
Reverting to unblock future Ludwig commits in the interim.
=> Revert "Bump Ludwig images to Ray 2.2.0 (#3023)"

ludwig/explain/captum.py, tests/ludwig/explain/test_captum.py
This PR fixes
1. a bug where token attributions contained NaN values
2. a bug where token attributions were normalized by the norm across the whole batch instead of the per-sequence norm 
and adds a test to avoid these from happening again going forward.
For 1., the cause was a division by zero silently returning NaNs. 
The norm of token attributions is 0 when all attributions are 0. In that case, we now return the original 0 attributions instead of NaNs.
For 2., the cause was a missing `dim` argument in the call to `torch.linalg.norm`.
=> Fix TLE: safe divide by zero + normalize at sequence level

ludwig/data/preprocessing.py, tests/integration_tests/test_preprocessing.py
Dask returns a Dask index structure because of lazy evaluation, so we need to force computation of the `value_counts()` method so we can grab the mode of the column to use as the fill_value.
=> Fix `fill_with_mode` when using Dask

ludwig/schema/encoders/sequence_encoders.py
Using the passthrough encoder with sequence or text features leads to the following error:
```
File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/utils/torch_utils.py", line 211, in _computed_output_shape
dummy_input = torch.rand(2, *self.input_shape, device=self.device)
TypeError: rand() argument after * must be an iterable, not NoneType
```
This update removes the passthrough encoder from the sequence and text features' encoder registries.
=> Remove passthrough encoder from sequence and text features encoder registry

ludwig/encoders/sequence_encoders.py, ludwig/schema/encoders/sequence_encoders.py
The schema currently supports `StackedRNN` and `StackedCNNRNN` cell types that are not in the registry, including `lstm_block`, `ln`, `lstm_cudnn`, `gru_block`, `gru_cudnn`, and `None`. This update removes the invalid cell types from the schema and updates docstrings.
=> Remove RNN invalid cell types from the schema

ludwig/modules/attention_modules.py
A constraint of the `MultiHeadSelfAttention` module is that `hidden_size` must be divisible by `num_heads`. The error message was somewhat unclear on how to address a mismatch, so this updates the message with more concrete instructions.
=> Update transformer `hidden_size / num_heads` error message

ludwig/utils/torch_utils.py
Follow-up to #3072. 
It's been observed in testing that MPS can sometimes hurt performance for small tabular models, and can lead to runtime errors when `PYTORCH_ENABLE_MPS_FALLBACK` is not set.
=> Require env var LUDWIG_USE_MPS to enable MPS

ludwig/data/cache/util.py, ludwig/data/preprocessing.py, ludwig/features/base_feature.py, ludwig/schema/model_types/base.py, ludwig/schema/model_types/utils.py, tests/integration_tests/test_class_imbalance_feature.py, tests/integration_tests/test_trainer.py, tests/ludwig/data/test_cache_util.py
This PR fixes situations where two configs using the same dataset would result in the same checksum, but the underlying feature proc_cols would be different because of different feature-specific preprocessing params.
Namely, it makes two changes:
1. Moves generation of the proc_col at the end of the instantiation of the ModelConfig object.
2. Modifies checksum calculation to account for the proc column name rather than the raw feature column name.
=> Generate proc_column only after all preprocessing parameters are merged in to prevent incorrect cached dataset reads

ludwig/automl/automl.py, ludwig/backend/base.py, ludwig/data/preprocessing.py, ludwig/datasets/__init__.py, ludwig/datasets/loaders/dataset_loader.py, ludwig/datasets/utils.py, tests/ludwig/datasets/test_datasets.py
Example:
```
ludwig train --dataset ludwig://titanic --config config.yaml
```
To use an individual split:
```
ludwig train --training_set ludwig://titanic --test_set ludwig://titanic
```
The latter form will only use the `train` and `test` splits from the dataset and discard the validation set.
=> Allow providing a Ludwig dataset as a URI of the form `ludwig://<dataset>`

ludwig/data/preprocessing.py
Otherwise this always gets printed, which I don't think is very helpful. We should only show it if rows actually end up getting dropped, so I added this gate.
=> Only show drop row logging if rows are dropped

tests/integration_tests/test_model_training_options.py
[Example of flakiness](https://github.com/ludwig-ai/ludwig/actions/runs/4177152055/jobs/7234368909)
Note that I'm not able to reproduce the `nan <= nan` error locally with --count=1000, but empirically the loss values that come from the lower LR seem more tractable. Hopefully the lower LR helps with flakiness.
I'm also not opposed to removing the test altogether for the lbfgs optimizer as we're still testing that we're functionally registering and referencing the torch implementation correctly, which is covered by tests for other optimizers.
=> Deflake the lbgfs optimizer test

ludwig/backend/ray.py, ludwig/data/dataset/ray.py, tests/integration_tests/test_ray.py
This updates `RayDataset`, `RayDatasetManager`, and `RayBackend` to accept `"auto"` as a valid input for `window_size_bytes`, and consolidates `RayDataset` creation logic to handle auto-windowing.
=> Use `window_size_bytes: auto` to specify automatic windowing

ludwig/datasets/configs/ethos_binary.yaml, ludwig/datasets/loaders/ethos_binary.py
According to the paper (https://arxiv.org/pdf/2006.08328v2.pdf), the authors defined `isHate` to be anything with label agreement >= 0.5. In the previous version of our dataset, we were only considering values exactly equal to 1 to be `isHate` leading to many false negatives.
=> Fixed ethos_binary dataset to threshold the label at 0.5

ludwig/utils/strings_utils.py, tests/ludwig/utils/automl/test_type_inference.py
While playing around with automl using the `ivory` dataset in the dataset zoo, I noticed that automl infers the `label` to be `number` since the labels are [-1, 1]. However, this is actually a classification problem, and this should be inferred as binary.
This PR updates the conventional bools to also allow -1 to be a valid negative class so we correctly infer the type as binary.
=> Add -1 as a valid negative class for binary type inference

ludwig/trainers/trainer_lightgbm.py, tests/conftest.py, tests/integration_tests/test_gbm.py
Ray Datasets are distributed by nature, there should be no need to set this to False
=> GBM: remove distributed=False from RayDMatrix

ludwig/schema/encoders/text_encoders.py
I thought we unregistered these - not sure how they got registered again.
=> Unregister CTRL and MT5 encoders since they have tensor placement and sentencepiece segfault issues

.github/workflows/pytest.yml
Only specifying `${{ hashFiles('requirements*.txt') }}` in the pip cache `key` doesn't account for cases where we update the `pytest.yml` workflow (esp. the Install Dependencies part), leading us to get a cache hit based on the key provided instead of reinstalling dependencies even when we update the install steps. This could lead to flakiness in tests as seen [here](https://github.com/ludwig-ai/ludwig/actions/runs/4198687893/jobs/7282653752) (success) and [here](https://github.com/ludwig-ai/ludwig/actions/runs/4199203681/jobs/7283778534) (failure).
This PR adds `'.github/workflows/pytest.yml'` as an input to the hash function.
=> fix: add pytest to hashfiles to be more selective about caching

ludwig/schema/encoders/text_encoders.py
See the associated issue for more information - we can re-enable this in the future. 
Issue: https://github.com/ludwig-ai/ludwig/issues/3107
=> Disable XLM Text Encoder because of host memory pressure issues

ludwig/config_validation/checks.py, tests/ludwig/config_validation/test_validate_config_encoder.py
Followup to #3066 that adds a validation check for `encoder.hidden_size % encoder.num_heads == 0` for transformer encoders.
=> Transformer divisibility error validation

ludwig/schema/lr_scheduler.py
`decay_rate` was using `decay_steps` metadata when generating the JSON Schema. Updated the reference to point to `decay_rate`'s metadata. This was resulting in JSON schemas that had suggested ranges larger than 1.
=> fix: Updated Learning Rate decay_rate to use corresponding Metadata.

ludwig/modules/normalization_modules.py, tests/ludwig/modules/test_normalization_modules.py
Causes the following error otherwise:
```
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 6])
```
=> Skip batch norm when chunk size is 1 in GhostBatchNorm

ludwig/schema/lr_scheduler.py, tests/ludwig/encoders/test_text_encoders.py
This PR adds a quick test to ensure that the schema and the `HF_ENCODERS` constant are in sync
=> Adds non-slow HF unit test to validate constant value

ludwig/config_validation/checks.py, ludwig/models/predictor.py, ludwig/utils/gbm_utils.py
Workaround for #3092 that prevents torch tensors from being placed on GPU when training with a GBM. There is an underlying inconsistency with tensor placement, where different functions place prediction and target tensors on  different devices when a GPU is available. This update moves all tensors to CPU for the time being.
=> Disallow GPU tensors in GBM training and eval

ludwig/schema/utils.py
Factor `allow_none` in whether to allow `None` value or not.
=> Not default to adding `None` as accepted tuple for `FloatRangeTupleDataclassField`

ludwig/globals.py, setup.py
This PR changes the Ludwig version from `0.7.beta` to `0.7`.
I will rebase off of master once #3009's tests finish running and it is merged in.
=> Update Ludwig version to 0.7

ludwig/utils/loss_utils.py, tests/ludwig/modules/test_loss_modules.py
It looks like PyTorch changed the meaning of `torch.maximum` at some point, as setting `confidence_penalty` was causing the function to be called with invalid inputs. Unfortunately, we didn't have any tests using `confidence_penalty` to catch this, so fixed the issue and added some. We should also look to add tests in the future that verify correctness of these params, as the hardcoded expectations here are only based on the observed outputs, not first principles.
=> Fixed confidence_penalty for newer versions of pytorch

ludwig/decoders/sequence_decoders.py
`Predictor` looks for `<output_feature>.predictions` and `<output_feature>.probabilities` in model output, however `SequenceGeneratorDecoder.get_prediction_set` only included logits. Excluding the others led to a KeyError when unflattening output features
``` 
File "/home/ray/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
raise KeyError(key) from err
KeyError: 'title_probabilities' (type: RayTaskError(KeyError), retryable: true)
```
This update adds predictions and probabilities to `get_prediction_set`.
=> Update SequenceGeneratorDecoder to output predictions and probabilities

ludwig/features/image_feature.py, ludwig/utils/image_utils.py, tests/integration_tests/test_preprocessing.py, tests/integration_tests/test_torchscript.py, tests/ludwig/utils/test_image_utils.py
This PR introduces automatic channel resizing for torchvision models to ensure that images fed into torchvision encoders always have 3 channels. Closes #3170.
=> Fix TorchVision channel preprocessing

ludwig/datasets/__init__.py, ludwig/datasets/configs/ames_housing.yaml, ludwig/datasets/configs/mercedes_benz_greener.yaml, ludwig/datasets/configs/sarcos.yaml, ludwig/datasets/dataset_config.py, ludwig/datasets/loaders/dataset_loader.py, tests/ludwig/datasets/test_datasets.py
To mitigate the flakiness of external APIs and downtime from the main mirrors, this PR introduces fallback mirrors to the dataset API. These mirrors are defined in the dataset configs under `ludwig/datasets/configs` by adding
```
fallback_mirrors:
- name: mirror_1
download_paths:
- path/to/dataset/file_1.json
- path/to/dataset/file_2.json
- name: mirror_2
download_paths: 
- ...
```
Only paths to filesystems are supported.
When downloading the dataset, the loader will try to retrieve the dataset from the main source (`download_urls` or `kaggle_competition`). If any exception is encountered, it will attempt to load the dataset from the mirror in the order specified.
=> Add fallback mirrors to dataset API

ludwig/data/cache/manager.py
We log the paths to the cached datasets when there is a cache hit, but when there is a cache miss and we preprocess the data, we don't log where the cached data is being written to. This PR ensures that this info is logged for better observability.
Usually follows the format `cache_dir/<checksum>.<meta/training/test/validation>.<format>`
=> Log cached dataset write paths during cache miss

tests/regression_tests/benchmark/test_model_performance.py
Dataset links seem to be back. https://github.com/ludwig-ai/ludwig/pull/3168 will allow us to retrieve the dataset even if they're down again.
=> Re-enable benchmark tests on `Sarcos` dataset

tests/integration_tests/test_sequence_decoders.py, tests/integration_tests/utils.py
Adds integration tests for SequenceGeneratorDecoder in response to #3152.
=> Add sequence decoder integration tests

ludwig/schema/features/base.py, ludwig/schema/features/utils.py
Redo of #3159 - this time from a native upstream branch rather than from my own fork.
--
Though this PR is just about moving one line of the schema (which is only relevant for AJV validation) one level up in its tree and the real issue at hand is that I'm working against marshmallow_jsonschema's rules (see this comment: https://github.com/ludwig-ai/ludwig/pull/2906#discussion_r1119576691), this change got me thinking about how we might want to deal with post-generation schema changes in the future.
I thought about tackling this a couple of different ways:
* some kind of post-generation decorator that can be added to a schema
* define a suite of schema transformations (like we already do for backwards compatibility)
* should we maintain separate schema transformations for usage with AJV?
* …
=> fix: [REBASE] Hoist uniqueItemProperties to top of feature JSON schema

tests/integration_tests/scripts/run_train_aim.py, tests/integration_tests/scripts/run_train_comet.py, tests/integration_tests/scripts/run_train_wandb.py, tests/integration_tests/test_model_save_and_load.py, tests/ludwig/augmentation/test_augmentation_pipeline.py
We should try and fine a way to do this at a global level for all tests, probably by mocking `get_output_directory` in some form.
=> Use tmpdir for more files generated during tests

ludwig/config_validation/validation.py, ludwig/schema/__init__.py, ludwig/schema/combiners/utils.py, ludwig/schema/decoders/utils.py, ludwig/schema/defaults/ecd.py, ludwig/schema/defaults/gbm.py, ludwig/schema/defaults/utils.py, ludwig/schema/encoders/utils.py, ludwig/schema/features/augmentation/utils.py, ludwig/schema/features/base.py, ludwig/schema/features/loss/utils.py, ludwig/schema/features/preprocessing/utils.py, ludwig/schema/hyperopt/__init__.py, ludwig/schema/hyperopt/scheduler.py, ludwig/schema/lr_scheduler.py, ludwig/schema/optimizers.py, ludwig/schema/preprocessing.py, ludwig/schema/split.py, ludwig/schema/trainer.py, ludwig/schema/utils.py
Redo of #3147  - this time from a native upstream branch rather than from my own fork.
--
* Removes unnecessary staticmethod decorators on JSON type mappings
* Removes `get_preprocessing_jsonschema`
* Adds a default `json_type_mapping` to `DictMarshmallowField`
=> fix: [REBASE] Misc. JSON schema fixes

ludwig/config_validation/checks.py, tests/ludwig/config_validation/test_checks.py
When using a comparator combiner, every input feature needs to be present in either `entity_1` or `entity_2`.
This PR adds an auxiliary check for that.
=> Add auxiliary validation for all features to be present in comparator combiner entities

ludwig/schema/common_fields.py, ludwig/schema/encoders/base.py, tests/ludwig/config_validation/test_checks.py
A dense encoder with 0 `num_layer`s doesn't make sense. This PR adds the option for specifying a `non_zero` argument in `common_fields.NumFCLayersField`.
=> Add `non_zero` to `common_fields.NumFCLayersField`

ludwig/schema/decoders/base.py
Following up on
- https://github.com/ludwig-ai/ludwig/pull/3151
- https://github.com/ludwig-ai/ludwig/pull/3217
Disabling needs to happen both at the decoder and schema config levels.
=> follow up: unregister passthrough decoder for all features

ludwig/config_validation/checks.py, ludwig/features/sequence_feature.py, ludwig/features/text_feature.py, ludwig/schema/features/base.py, ludwig/schema/features/preprocessing/sequence.py, ludwig/schema/features/preprocessing/text.py, ludwig/schema/metadata/configs/features.yaml, ludwig/schema/model_types/base.py, ludwig/schema/model_types/utils.py, requirements.txt, tests/integration_tests/test_experiment.py, tests/integration_tests/test_preprocessing.py, tests/ludwig/schema/test_model_config.py
This PR implements a new config param for text and sequence features, `sequence_length`, a nullable positive integer.
`sequence_length` defaults to `None`. This means that the sequence length for a given feature will be inferred from the dataset. The inferred sequence length will be capped at `max_sequence_length`, which defaults to `256`.
If `sequence_length` is not `None`, then the sequence length for a given feature will be the specified value and samples will be padded and truncated as needed. If the specified value for `sequence_length` is greater than `max_sequence_length`, then experiment will fail fast with an error message recommending that you set `max_sequence_length` to a value greater than or equal to `sequence_length`.
=> Implements `sequence_length` param

ludwig/features/timeseries_feature.py, ludwig/schema/features/preprocessing/timeseries.py, tests/integration_tests/test_timeseries_feature.py
Closes #3236.
Follow-up: apply missing value strategy to NaNs at a per-row level for timeseries and vector types.
=> Replace NaN in timeseries rows with `padding_value`

ludwig/backend/ray.py
If we don't persist, it causes multiple re-reads of binary files for each `map_objects` operation which makes reading binary files really slow, and may cause unwanted memory spikes that leads to a large amount of disk spillage.
=> Persist Dask Dataframe after binary image/audio reads

ludwig/encoders/category_encoders.py, tests/ludwig/config_validation/test_checks.py
When we specify a `onehot` encoder for category features and have dense layers down the line, we get the following error
```
RuntimeError: mat1 and mat2 must have the same dtype
```
This PR makes sure to convert the outputs of the `onehot` encoder to `float32`
=> fix: transform `onehot` encoder outputs to float32 tensor

ludwig/features/sequence_feature.py, ludwig/features/text_feature.py, ludwig/schema/encoders/sequence_encoders.py, ludwig/schema/features/base.py, ludwig/schema/features/preprocessing/sequence.py, ludwig/schema/features/preprocessing/text.py, ludwig/schema/metadata/configs/features.yaml, ludwig/schema/model_types/base.py, ludwig/schema/model_types/utils.py, requirements.txt, tests/integration_tests/test_experiment.py, tests/integration_tests/test_preprocessing.py, tests/ludwig/schema/test_model_config.py
Adds the following two PRs:
https://github.com/ludwig-ai/ludwig/pull/3205: https://github.com/ludwig-ai/ludwig/commit/e3a9416d640821b88494adce63f7f5db882296b5
https://github.com/ludwig-ai/ludwig/pull/3221: https://github.com/ludwig-ai/ludwig/commit/75b1941b65bb0a14c7a594e8a25e8fee13ecae2f
These two PRs will enable users to fix the sequence length of text features using the new `sequence_length` parameter, which is particularly useful when using the `sequence` combiner (https://github.com/ludwig-ai/ludwig/issues/3220).
=> Cherry-pick 0.7: `sequence_length` capability

ludwig/utils/backward_compatibility.py, tests/ludwig/utils/test_backward_compatibility.py
Title :) 
Essentially `encoder`, `decoder` and `loss` are not valid keys for GBMs.
=> Removes invalid keys from GBM defaults in the schema

ludwig/schema/encoders/text_encoders.py
Also, fix the `allow_none` annotation for Longformer.
=> Update gpt text encoder `afn` parameter default to what's listed in HF docs.

ludwig/automl/base_config.py, ludwig/data/split.py, ludwig/utils/automl/type_inference.py, ludwig/utils/strings_utils.py, tests/ludwig/automl/test_base_config.py, tests/ludwig/data/test_split.py
- Fixes issue with datetime splitting on timestamp type columns
- Fixes issue with automl type inference for datetime types
- Fixes issue with automl type inference for datetimes formatted as strings
=> Fixed handling of datetime types in input parquet files

ludwig/utils/data_utils.py
Fix for the following failure
`RuntimeError: Caught exception during model preprocessing: Object of type bool_ is not JSON serializable`
with the following config
```
{'defaults': {'binary': {'preprocessing': {'missing_value_strategy': 'fill_with_mode'}}},
'input_features': [{'name': 'binary_1', 'type': 'binary'}],
'model_type': 'ecd',
'output_features': [{'decoder': {'idx2str': ['lwrVkpk',
'ztHj',
'dQxBJ',
'mLFhKPHrTn',
'iBjnr',
'Pb',
'qyiL',
'VEQv',
'zLol',
'SBpN'],
'vocab_size': 10},
'name': 'category_output_1',
'type': 'category'}],
'trainer': {'train_steps': 1}}
```
The `np.bool_` exists in `training_set_metadata` after the data has been preprocessed and is being cached.
=> Handle `np.bool` to JSON `NumpyEncoder`

ludwig/utils/backward_compatibility.py, tests/ludwig/utils/test_backward_compatibility.py
Had to rebase this PR because of the ongoing credential issues with my fork.
=> fix: [REBASE] Add config transformation that removes extra `type` param if it exists in the defaults config

ludwig/utils/tokenizers.py, requirements.txt
This PR unpins `transformers` in the requirements and ensures we are using [the HuggingFace default method of downloading single files](https://huggingface.co/docs/huggingface_hub/v0.13.3/guides/download).
=> Unpin `transformers`

ludwig/schema/features/base.py, ludwig/schema/features/binary_feature.py, ludwig/schema/features/category_feature.py, ludwig/schema/features/number_feature.py, ludwig/schema/features/sequence_feature.py, ludwig/schema/features/set_feature.py, ludwig/schema/features/text_feature.py, ludwig/schema/features/timeseries_feature.py, ludwig/schema/features/utils.py, ludwig/schema/features/vector_feature.py, ludwig/schema/model_types/utils.py
Separate `output_config_registry` into `ecd_output_config_registry` and `gbm_output_config_registry`.
=> fix: Add separate output config registries for ECD and GBM

ludwig/decoders/sequence_tagger.py, ludwig/features/base_feature.py, ludwig/features/feature_utils.py, ludwig/features/text_feature.py, tests/integration_tests/test_experiment.py
This is necessary to enable prediction/inference using models trained with the ray backend, which uses `get_prediction_set()` to determine which tensors are returned from the OutputFeature's `PredictModule`.
=> Add `PROBABILITIES` and `PREDICTIONS` to the prediction set for the sequence tagger decoder.

ludwig/callbacks.py, ludwig/distributed/base.py, ludwig/distributed/ddp.py, ludwig/distributed/horovod.py, ludwig/modules/optimization_modules.py, ludwig/schema/metadata/configs/trainer.yaml, ludwig/schema/trainer.py, ludwig/trainers/trainer.py, tests/integration_tests/test_trainer.py
Benefits include:
- Lower network bandwidth overhead by reducing frequency of allreduce / gradient synchronization
- Increase effective batch size to smooth out variance when training very large models
=> Added `trainer.gradient_accumulation_steps` for increasing effective batch size

ludwig/schema/decoders/utils.py, ludwig/schema/encoders/utils.py, ludwig/schema/utils.py, tests/ludwig/schema/test_model_config.py
Note that this currently works due to backward compatibility logic, but we may remove this at some point in the future, so worth supporting it officially.
=> Allow providing encoders / decoder params as strings

ludwig/features/feature_utils.py, tests/integration_tests/test_experiment.py, tests/ludwig/data/test_split.py
- #3300 introduced a change that causes test failures in `tests/ludwig/features/test_feature_utils.py::test_compute_token_probabilities`. When handling list and tuple inputs, `feature_utils.compute_token_probabilities` checks that the inputs have a `"len"` attribute, but the attribute name should be `__len__`.
- `tests/integration_tests/test_experiment.py::test_sequence_tagger_text_ray` needed to be marked distributed
=> Fixes for CI failures

ludwig/data/dataframe/dask.py, ludwig/features/number_feature.py, tests/ludwig/utils/test_normalization.py
`iq` preprocessing for number features fails when using a ray/dask backend, with the following error:
```
RuntimeError: Caught exception during model preprocessing: 'numpy.float64' object has no attribute 'compute' (type: RayTaskError(RuntimeError), retryable: true)
```
The `InterQuartileTransformer` uses `np.percentile`, which computes the percentile directly without deferring to the dask backend to execute the computation. This seems like the right thing to do as it looks like unlike `column.mean()`, dask does not have a parallelized implementation of `np.percentile`.
This PR removes the call to `.compute()` in `InterQuartileTransformer.fit_transform_params()`, and adds tests to make sure that all preprocessing options in the registry succeed on both pandas and ray/dask backends.
=> Ensure that `iq` and all number feature preprocessing normalizations work on dask backends.

docker/ludwig-ray-gpu/Dockerfile, docker/ludwig-ray/Dockerfile
In https://github.com/ludwig-ai/ludwig/pull/3320, we update the docker images to use Python 3.9. 
In https://github.com/ludwig-ai/ludwig/pull/3324, we update the type hinting to match [what's accepted](https://docs.python.org/3/library/typing.html) in Python 3.9, we see the [following failure in the CI](https://github.com/ludwig-ai/ludwig/actions/runs/4626038215/jobs/8182367380) (failures for torchscript tests). By following the [torchscript typing guide](https://pytorch.org/docs/stable/jit_language_reference.html), it looks like only python 3.8-style type hints are accepted.
In this PR, we use Python 3.8 in the docker images.
=> Downgrade docker images to use Python 3.8

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_text_encoders.py
=> Filter auto_transformer kwargs based on forward signature

ludwig/api.py
This PR is in reference to #2859 (https://github.com/ludwig-ai/ludwig/issues/2859)
I've  added a `Union` in the static function `create_model` for the `config_obj`
=> Added union on ModelConfig and dict in create_model

ludwig/features/sequence_feature.py, tests/integration_tests/test_sequence_decoders.py
`SequenceOutputFeature.unflatten` would try to reshape its output using `self.decoder_obj.config.num_classes` and throw an `AttributeError`. This PR updates the sequence decoder integration tests and fixes the error by reshaping with `self.decoder_obj.config.vocab_size` instead.
=> Fix sequence decoder attribute error

ludwig/utils/automl/utils.py, tests/ludwig/utils/automl/test_utils.py
`get_dataset_info_from_source avg_words = source.get_avg_num_tokens(field) File "/src/predibase_engine/sources/dask_util.py", line 59, in get_avg_num_tokens return avg_num_tokens(self.sample[column]) File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/utils/automl/utils.py", line 36, in avg_num_tokens avg_words = round(nan_to_num(Series(unique_entries).str.split().str.len().mean())) File "/home/ray/anaconda3/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 124, in wrapper raise TypeError(msg) TypeError: Cannot use .str.split with values of inferred dtype 'bytes'. (type: RayTaskError(TypeError), retryable: true)`
=> Decode bytes to strings for DatasetInfo avg_words

.github/workflows/pytest.yml, .github/workflows/pytest_slow.yml, requirements_test.txt
A collection of CI fixes/improvements:
- For torch nightly tests, pin to `torch==2.1.0.dev20230418+cpu`. `2.0.0.dev20230213+cpu` is out of commission.
- Remove `pip install protobuf==3.20.1` workaround for https://github.com/databrickslabs/dbx/issues/257
- Remove horovod-related env variables.
```
env:
HOROVOD_WITH_PYTORCH: 1
HOROVOD_WITHOUT_MPI: 1
HOROVOD_WITHOUT_TENSORFLOW: 1
HOROVOD_WITHOUT_MXNET: 1
```
- Remove `--no-use-pep517` and remove `ConfigSpace` custom installation workaround for https://github.com/automl/ConfigSpace/issues/173
- Remove `dragonfly-opt` from requirements, which causes a numpy installation failure (https://github.com/ludwig-ai/ludwig/actions/runs/4737879639/jobs/8411146481)
=> Fix dependency install in CI

ludwig/trainers/trainer.py
Previous implementation causes `RuntimeError: Tensors must be CUDA and dense (type: RayTaskError(RuntimeError), retryable: true)`
=> Use `dist.barrier` instead of horovod legacy code

ludwig/backend/base.py, ludwig/backend/horovod.py, ludwig/backend/ray.py, ludwig/distributed/__init__.py, ludwig/modules/metric_modules.py, tests/integration_tests/test_trainer.py, tests/ludwig/backend/test_ray.py
Previously were seeing issues were DDP was getting picked up even though FSDP was being selected.
=> Fixed distributed strategy registration to be explicit

ludwig/trainers/trainer.py
Currently, if we're resuming model training from a checkpoint, we try to download artifacts from storage only on the coordinator process. DDP assumes all workers can read model params, so it's necessary to download in every worker process.
=> Allow checkpoint download on non-coordinator process

ludwig/trainers/trainer.py, ludwig/utils/batch_size_tuner.py
=> Clean up distributed batch size tuning logging

.github/workflows/pytest.yml, .gitignore, ludwig/api.py, ludwig/callbacks.py, ludwig/trainers/trainer.py, ludwig/utils/backward_compatibility.py, tests/integration_tests/test_experiment.py
This PR ensures
- We're not accessing keys that don't exist in the progress tracker dictionary.
- All keys of the progress tracker dictionary are available for initialization.
- All workers are synced on whether to resume or create a new progress tracker (due to inconsistencies in the output of `resume_files_exist`)
=> Ensure worker synchronization during resume

ludwig/datasets/loaders/mnist.py
Use downloaded path instead of relative train/test path.
Current MNIST example fails due to reading wrong paths of images.
```
[Errno 2] No such file or directory: '/Users/chongxiaoc/git/ludwig/examples/mnist/training/0/16585.png'
/Users/chongxiaoc/git/ludwig/ludwig/utils/image_utils.py:138: UserWarning: Failed to read image from PNG file. Original exception: Bytes object is empty. This could be due to a failed load from storage.
warnings.warn(f"Failed to read image from PNG file. Original exception: {e}")
/Users/chongxiaoc/git/ludwig/ludwig/utils/image_utils.py:149: UserWarning: Failed to read image from numpy file. Original exception: Cannot load file containing pickled data when allow_pickle=False
warnings.warn(f"Failed to read image from numpy file. Original exception: {e}") …
```
=> Fix MNIST datasets img path column

README.md
Correct Typo in `/Readme.md` for Torchscript
=> Correct TorchScript Typo in Readme

.github/workflows/pytest.yml, ludwig/distributed/ddp.py, ludwig/modules/normalization_modules.py, ludwig/modules/tabnet_modules.py, tests/integration_tests/test_experiment.py, tests/ludwig/modules/test_tabnet_modules.py
fixes the following error
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter …
```
=> Temporarily switch to `eval` mode when using `batch_size: 1`

examples/llm_finetuning/train_imdb_ray.py, ludwig/distributed/base.py, ludwig/distributed/ddp.py, ludwig/utils/checkpoint_utils.py
When loading the checkpoint, we assume it exists on each node, so we should make sure we save on each node.
This assumes we're not using a global filesystem like NFS. We could consider ways of checking this (like try writing files to the directory from each node and see if nodes can read each-other's files), but for now this should suffice for most use cases.
=> Fixed DDP checkpointing to save to local disk on each node

ludwig/automl/auto_tune_config.py, ludwig/constants.py, ludwig/explain/captum.py, ludwig/explain/captum_ray.py, ludwig/schema/lr_scheduler.py, ludwig/trainers/trainer_llm.py, tests/integration_tests/test_explain.py
Add a constant for `MINIMUM_BATCH_SIZE=1`, and use that as the basis for captum's batch size retry wrapper.
=> Ensure captum's halved batch size retry fn wrapper accepts the minimum batch size of 1.

.github/workflows/pytest.yml, examples/llm_finetuning/imdb_deepspeed_zero3.yaml, examples/llm_finetuning/imdb_deepspeed_zero3_ray.yaml, examples/llm_finetuning/train_imdb_ray.py, ludwig/backend/deepspeed.py, ludwig/backend/ray.py, ludwig/distributed/deepspeed.py, ludwig/encoders/text_encoders.py, ludwig/schema/encoders/text/peft.py, ludwig/schema/encoders/text_encoders.py, ludwig/schema/utils.py, tests/integration_tests/test_cached_preprocessing.py, tests/integration_tests/test_peft.py, tests/integration_tests/utils.py, tests/ludwig/config_validation/test_validate_config_misc.py
Using LoRA speeds up fine-tuning, allowing you to train with larger batch sizes and adjust fewer weights during training.
Usage:
```
encoder:
type: bert
trainable: true
tuner: lora
```
You can also specify additional parameters:
```
encoder:
type: bert
trainable: true
tuner:
type: lora
r: 16
alpha: 32
dropout: 0.1
bias_type: all
```
=> Added LoRA tuner for HuggingFace text encoders

ludwig/trainers/trainer_lightgbm.py, tests/integration_tests/test_gbm.py
LGBM Dataseta are incmpatible with features with JSON special characters in their names (e.g. `:`, `[`, `]`, `{`, `}`). Currently, we raise an exception when Dataset creation fails in this way. This update adds feature name sanitizers local to `LGBMTrainer` and `LGBMRayTrainer` that cleans the feature names for Dataset creation without altering the names globally.
=> Sanitize GBM feature names to remove JSON special characters

ludwig/backend/ray.py
This PR is contributed by developers of www.getdaft.io and increases performance of a preprocessing pipeline on the melbourne airbnb dataset by a factor of 2x in many cases.
In the local single-partition Ray cluster setup: Daft is a 50% speedup over the existing Ludwig code for URL downloading, and an overall 40% speedup for all of preprocessing.
In the distributed multi-partition Ray cluster setup: Daft is a 50% speedup over the existing Ludwig code for URL downloading, and an overall 40% speedup for all of preprocessing.
See [benchmarking doc](https://docs.google.com/document/d/1gu2Zi75v0SVVIVm8lqU8rLH9GZ9Mx4kCeyTLgMZrXsk/edit?usp=sharing) for more details.
**Fix daft.context.set_runner_ray**:
`daft.context.set_runner_ray(ray.util.get_node_ip_address(), ...)` is fixed to …
=> Daft reads PR for 0.1

ludwig/backend/deepspeed.py, ludwig/distributed/deepspeed.py, ludwig/trainers/trainer.py
Example:
```
strategy:
type: deepspeed
bf16:
enabled: true
```
=> [llm] Added support for bfloat16 with deepspeed

ludwig/utils/strings_utils.py, ludwig/utils/tokenizers.py
It seems like tokenizers may have the attribute, yet not have a value set for that attribute. We make these assumptions in the HFTokenizer class. This PR tests for those assumptions and adds falling back to pad token id = 0
=> Fix tokenizer pad and eos token assumption for HF tokenizers

ludwig/schema/utils.py, tests/ludwig/config_validation/test_validate_config_misc.py
What was going wrong here is that the default for param metadata was `None` which would directly get put into the schema, so unless you explicitly defined param metadata, it would come without param metadata and cause issues downstream. This basically sets the default param metadata value to an empty parameter metadata entry with all the default values for that data class.
=> Fix Missing Param Metadata

ludwig/models/predictor.py
This fixes an issue where the metric functions are on the wrong device during evaluation, and ensures that metrics, metric functions and the model are all on the same device.
=> Fix: Device placement for metrics during evaluation

ludwig/schema/generation.py, ludwig/schema/prompt.py, ludwig/schema/utils.py
Reasoning for adding a title param to `unload_jsonschema_from_marshmallow_class`: Basically, in UI, when there is a nested JSON object - so think the Retrieval being a field under prompt - the schema processor looks to create a specific section for the nested object so that it can display all it's properties. Without a title however, it just displays a random UI divider bar which looks weird / doesn't make sense. particular line adds that title so it's clear that the user is adding in parameters for the retrieval section. Broadly speaking, the addition of a title param to this function allows us to add titles in for this reason in other parts of the schema when necessary.
=> Order prompt schema and add title

ludwig/schema/utils.py
Forgot to remove the None imputation for param metadata on some of the schema utils. This fixes that.
=> Remove the other None Param Metadata imputation

ludwig/schema/metadata/configs/llm.yaml, ludwig/schema/model_types/llm.py
Param filtering was broken, I fixed but then realized model name doesn't have an expected impact so it gets filtered out. This adds it in so it doesn't.
=> Add model name param metadata

ludwig/data/preprocessing.py, ludwig/data/prompt.py, ludwig/schema/prompt.py, tests/integration_tests/test_preprocessing.py
For LLMs and other text models, it's common to treat multiple inputs as a single string of text to feed into the model as input, rather than construct separate "towers" for each feature. This PR provides a standard way to do this via the `prompt` config.
For ECD:
```
- name: context
type: text
preprocessing:
prompt:
template: The {color} {animal} jumped over the {size} {object}
```
For LLM:
```
prompt:
template: The {color} {animal} jumped over the {size} {object}
- name: context
type: text
```
Here, it is not required that `context` be a valid column of the input dataset, as it will be generated from the `prompt`. However, each of `color`, `animal`, `size`, and `object` are assumed to be columns of the input dataset.
=> Support combining multiple columns into a single text feature

requirements.txt, tests/ludwig/utils/test_data_utils.py
The HTML reader was broken due to a missing `html5lib` import. Our reader uses `pandas.read_html`, which calls `lxml` to parse HTML, which in turn calls `html5lib` to parse it. That library is not an explicit dependency for `lxml`, so it need to be installed separately. This PR adds `html5lib` to `requirements.txt` and adds a small test for `read_html`.
=> fix: Install html5lib and test html reads

ludwig/models/llm.py, ludwig/utils/llm_utils.py, tests/ludwig/utils/test_llm_utils.py
Fixes an issue with left padding removal when there is no padding in the input tensor. It previously assumed that would always happen, which was incorrect.
=> [LLM] Skip left padding removal when there is no left padding

README.md
Wrong quotes used, prevents anyone from copying and run command.
=> Update README.md, fixed some quotes

ludwig/schema/features/augmentation/utils.py
This is a high priority fix - the titles are important for other logic.
=> fix: Add titles for augmentation schema options

docker/ludwig-ray-gpu/Dockerfile, docker/ludwig-ray/Dockerfile, docker/ludwig/Dockerfile
- This adds the `--no-cache-dir` to pip installs within the Dockerfile. Without doing this, the pip cache adds around 2.5 GB uncompressed to the resulting containers.
=> Adding --no-cache-dir to dockerfile pip install

examples/llm_finetuning/train_imdb_ray.py
`llm_finetune` example is using out-dated json format.
This PR should fix it.
However, my testing env is using Ray 2.5 and still get failure in model training part.
=> [Example] Fix llm_finetune example json part

requirements_distributed.txt
Previously, we were defaulting to 0.8.3 which has a few bugs that are fixed in deepspeed 0.9.2. I'm temporarily pinning this version, and will test deepspeed 0.9.5 at a future point so we can unpin deepspeed.
=> Unpin deepspeed

README.md
corrected beat1 to beta1 in parameters of the trainer type : adamw 
in line 224 
in readme.md
=> typo in parameter of README.md

requirements.txt, requirements_distributed.txt
`tables`, afaict, isn't used anywhere directly in ludwig code.
```
python3 -m venv env
source env/bin/activate
pip install ludwig
```
Installation errors out:
```
...
Collecting tables
Using cached tables-3.8.0.tar.gz (8.0 MB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [11 lines of output]
<string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
ld: library not found for -lhdf5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
cpuinfo failed, assuming no CPU features: 'flags'
* Using Python 3.11.3 (main, Apr  7 2023, 21:05:46) …
```
=> Remove `tables` requirement as it causes issues installing ludwig in linux env.

ludwig/utils/batch_size_tuner.py
=> Fixed divide by zero when tuning batch size

ludwig/data/dataset/pandas.py, ludwig/distributed/deepspeed.py, ludwig/models/llm.py, ludwig/trainers/trainer.py, ludwig/utils/checkpoint_utils.py
Saving all weights was slowing down training and bloating disk usage, since we only need to save weights trained as part of the PEFT adapter.
Previous implementation was reloading the model without quantization, leading to weights being placed on CPU and erroring during eval.
=> Exclude frozen weights from checkpoints and fix evaluation using quantized LLMs

ludwig/models/llm.py, ludwig/schema/llms/model_parameters.py, ludwig/schema/model_types/llm.py, tests/integration_tests/test_llm.py, tests/ludwig/schema/test_model_config.py
This PR adds support for dynamic RoPE-scaling (rotary position embeddings) to extend the context length of LLM like LLaMA, GPT-NeoX, or Falcon. 
To optionally configure these parameters, you can set them under the `model_parameters` section of the Ludwig config.
```yaml
base_model: meta-llama/Llama-2-7b
model_parameters:
rope_scaling:
type: dynamic
factor: 2.0
- name: instruction
type: text
output_features:
- name: output
type: text
```
For more context on RoPE scaling, check out the following:
- https://kaiokendev.github.io/context
- https://www.reddit.com/r/LocalLLaMA/comments/14mrgpr/dynamically_scaled_rope_further_increases/
=> Add RoPE scaling to increase context length up to 8K for training or inference.

requirements_test.txt
Was experimenting with my ludwig installation, and I came across this error while trying to run a basic test:
```
Created a temporary directory at /tmp/tmphl05r644
Writing /tmp/tmphl05r644/_remote_module_non_scriptable.py
[2023-08-02 23:23:56,329] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
ImportError while loading conftest '/home/ksbrar/work/ludwig-2/tests/conftest.py'.
tests/conftest.py:35: in <module>
from ludwig.hyperopt.run import hyperopt
ludwig/hyperopt/run.py:11: in <module>
ludwig/api.py:40: in <module>
from ludwig.backend import Backend, initialize_backend, provision_preprocessing_workers
ludwig/backend/__init__.py:22: in <module>
from ludwig.backend.base import Backend, LocalBackend …
```
=> int: Pin `sqlalchemy` to `1.x.x` versions

ludwig/schema/encoders/text_encoders.py, ludwig/schema/metadata/configs/encoders.yaml, tests/ludwig/encoders/test_text_encoders.py
Fixes the following error:
```
'AutoTransformerConfig' object has no attribute 'use_pretrained'
```
when trying to train an custom transformer model from HF using a config that looks like this:
```
encoder:
type: auto_transformer
trainable: false
pretrained_model_name_or_path: huggyllama/llama-7b
preprocessing:
tokenizer: space_punct
max_sequence_length: null
```
=> Add use_pretrained attribute for AutoTransformers

requirements.txt
This dependency causes installation of ludwig v0.7.4 to fail.
=> Remove tables for Ludwig 0.7.

ludwig/schema/combiners/comparator.py, ludwig/schema/combiners/concat.py, ludwig/schema/combiners/project_aggregate.py, ludwig/schema/combiners/sequence.py, ludwig/schema/combiners/sequence_concat.py, ludwig/schema/combiners/tab_transformer.py, ludwig/schema/combiners/tabnet.py, ludwig/schema/combiners/transformer.py, ludwig/schema/combiners/utils.py, tests/integration_tests/test_custom_components.py
=> int: Rename original `combiner_registry` to `combiner_config_registry`, update decorator name

ludwig/api.py, ludwig/models/llm.py
Sample code:
```python
model = LudwigModel(config=config, logging_level=logging.INFO)
results = model.train(training_set=dataset)
model.predict(dataset=dataset[:1], generation_config={"max_new_tokens": 513})
```
I've added additional logging statements to make it easier for testers/users to verify behavior.
=> Add mechanic to override default values for generation during model.predict()

ludwig/features/date_feature.py, ludwig/utils/date_utils.py, tests/integration_tests/test_date_feature.py, tests/ludwig/features/test_date_feature.py, tests/ludwig/utils/test_date_utils.py
Currently, the date feature supports ISO date/time strings and custom date/time strings with a user-supplied format string. This adds support for preprocessing int and float second and millisecond POSIX timestamps.
=> [feat] Support for numeric date feature inputs

ludwig/features/text_feature.py, tests/integration_tests/test_experiment.py, tests/integration_tests/test_llm.py
This PR enables adds a new output column when calling `model.predict()` for text output features called `response`. It is the synthesized string representation of each of the tokens in the `predictions` column.
For non HF pretrained models, it simply concatenates with white spaces since the underlying vocabulary created is a per-word vocab, while for HF models with tokenizers, it does proper batch decoding to create the right output string.
The new output from the text features will have:
```
<feature_name>_predictions
<feature_name>_probabilities
<feature_name>_probability
<feature_name>_response
```
=> Add new sythesized `response` column for text output features during postprocessing

ludwig/models/llm.py
Previously: evaluation loss metric could be on a different device than inputs
Now: evaluation loss metric moved to same device as inputs
=> Move loss metric to same device as inputs

ludwig/config_validation/checks.py, tests/ludwig/config_validation/test_checks.py, tests/ludwig/schema/test_model_config.py
Previously: users could omit backend from their config when running LLM finetuning with quantization
Now: users are prompted to set backend to local explicitly when running LLM finetuning with quantization
=> Ensure user sets backend to local w/ quantization

ludwig/config_validation/checks.py, tests/ludwig/config_validation/test_checks.py, tests/ludwig/schema/test_model_config.py
This reverts commit 190f208b50c02640049d5b707dd4ea909806682a.
=> Revert "Ensure user sets backend to local w/ quantization (#3524)"

requirements.txt
When installing Ludwig in a new env, `transformers` will raise the following error
```
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```
`transformers` requires `pydantic` 1.x, however `pydantic` 2.x is being installed. More details can be found in [this issue](https://github.com/huggingface/transformers/pull/24596). This update pins `pydantic` to 1.x while `transformers` is being updated.
=> [bug] Pin pydantic to < 2.0

ludwig/features/date_feature.py, tests/ludwig/features/test_date_feature.py
Currently, date feature preprocessing supports `datetime.datetime` objects, ISO time strings, custom time strings, and int/float timestamps. `datetime.date` objects, however, are considered invalid and replaced with the fill value despite being valid date features. This update
- adds support for `datetime.date` objects to `DateFeatureMixin.date_to_list`
- adds a test for `datetime.date` support
=> [bug] Support preprocessing `datetime.date` date features

ludwig/distributed/ddp.py, ludwig/models/predictor.py, tests/integration_tests/test_automl.py
This update addresses the issue described in #3544, which saw a device mismatch when running evaluation on GPU.
Repros:
1. The original issue repros in `tests/integration_tests/test_automl.py::test_auto_train` when using GPU.
2. A similar error occurs during `tests/integration_tests/test_api.py::test_api_intent_classification` when using GPU.
Fixes:
1. Move the model to GPU in `ludwig.models.predictor.Predictor.batch_evaluation` when using GPU.
2. Move the model to GPU in `ludwig.models.predictor.Predictor.batch_prediction` when using GPU.
=> fix: Move model to the correct device for eval

requirements.txt
It seems like the latest `transformers` package has a bug. This can be fixed by either using `transformers` master, or downgrading to `4.31.0` which is stable and works correctly. 
This is the error we run into with 4.32.1:
```
site-packages/ludwig/api.py:1510), in LudwigModel.preprocess(self, dataset, training_set, validation_set, test_set, training_set_metadata, data_format, skip_save_processed_input, random_seed, **kwargs)
1508     return PreprocessedDataset(proc_training_set, proc_validation_set, proc_test_set, training_set_metadata)
1509 except Exception as e:
-> 1510     raise RuntimeError(f"Caught exception during model preprocessing: {str(e)}") from e
1511 finally:
1512     for callback in self.callbacks:
RuntimeError: Caught exception during model preprocessing: local variable …
```
=> Pin Transformers to 4.31.0

ludwig/contribs/wandb.py
Our current callback implementation only logs the dataset, but not any metrics. 
Confirmed that this branch works if you also downgrade `wandb` to `0.12.10`. We should spend time fixing our integration/making it compatible with the latest version of wandb, but for now, this fix should suffice. 
FYI, it's not clear what the issue is with the latest version (no code errors, just doesn't push metrics up to wandb). Here's the slack thread for context: https://ludwig-ai.slack.com/archives/C01PN6M2RSM/p1693941105546379
=> WandB: Add metric logging support on eval end and epoch end

tests/ludwig/combiners/test_combiners.py
This is a temporary work-around for Issue #3591.
Comment out corner cases that cause failure in tabtransformer combiner unit test.
Root cause appears to be a recent change in PyTorch `LayerNorm` implementation.  See cited issue for details.
=> FIX: Failure in TabTransformer Combiner Unit test

tests/integration_tests/parameter_update_utils.py
Running any test that calls `tests.integration_tests.parameter_update_utils.check_module_parameters_updated` in an environment with a GPU leads to a device mismatch error, with the model on GPU and the target tensor on CPU. This fixes the device mismatch by putting the target tensor on the model device in this function.
=> fix: Move target tensor to model output device in `check_module_parameters_updated`

ludwig/utils/llm_utils.py, ludwig/utils/tokenizers.py
Because CodeLlamaTokenizer does not have a `pad_token_id` set, this PR adds it to the list of tokenizers we set a pad_token explicitly for.
=> Add codellama to tokenizer list for set_pad_token

ludwig/schema/trainer.py
Our current batch size tuning logic for eval batch size is more geared towards ECD than LLM.
For LLMs, we want to create synthetic data and push the largest possible "most computationally expensive" batches through during batch size tuning, but right now we just use batches that exist in the dataset. More on this in the future.
For now, let's set the default eval_batch_size is 2.
=> Set default eval batch size to 2 for LLM fine-tuning

.github/workflows/pytest.yml, ludwig/api.py, ludwig/utils/trainer_utils.py, pytest.ini, tests/integration_tests/test_automl.py, tests/integration_tests/test_cached_preprocessing.py, tests/integration_tests/test_cli.py, tests/integration_tests/test_experiment.py, tests/integration_tests/test_explain.py, tests/integration_tests/test_gbm.py, tests/integration_tests/test_hyperopt.py, tests/integration_tests/test_hyperopt_ray.py, tests/integration_tests/test_hyperopt_ray_horovod.py, tests/integration_tests/test_postprocessing.py, tests/integration_tests/test_ray.py, tests/integration_tests/test_remote.py, tests/integration_tests/test_sequence_decoders.py, tests/ludwig/augmentation/test_augmentation_pipeline.py, tests/ludwig/combiners/test_combiners.py, tests/ludwig/data/dataframe/test_dask.py, tests/ludwig/models/test_training_determinism.py
Make Ludwig CI consistently green again.
With the changes in this PR, CI time is cut down from 1.5 hours (with timeouts) to 40 minutes.
- Looked through [commit history](https://github.com/ludwig-ai/ludwig/commits/master) and [CI history](https://github.com/ludwig-ai/ludwig/actions/workflows/pytest.yml?page=5) to determine a commit when tests still passed and a commit when tests failed.
- Narrowed down the culprit to [this change](https://github.com/ludwig-ai/ludwig/pull/3533/files#diff-cd8c36a7791c7d25958379fa9be0e56f0e8a8925f7ef73ea69ffa95a3c63833fL616-R616). This PR made some changes to batch size tuning mechanics for auto effective batch size. This PR made a change that also tunes eval batch size even if batch size is fixed.
- I've added a couple of docstrings to help clarify how auto …
=> [CI] Explicitly set eval batch size in determinism tests, introduce a new integration test group, and exclude slow tests.

ludwig/trainers/trainer.py
This allows training callbacks (i.e. `def on_batch_end(self, trainer, progress_tracker, save_path: str, sync_step: bool = True):`) to use `trainer.steps_per_epoch` to render step-level progress bars
=> Store steps_per_epoch in Trainer

.github/workflows/pytest.yml, ludwig/utils/tokenizers.py, tests/ludwig/utils/test_tokenizers.py
The `comma`, `underscore` and `characters` preprocessors are not currently TorchScriptable because they do not implement the TorchScript Module methods. As part of this PR, we now have a general `StringSplitTokenizer` that can be re-used across the various defaults we support. Unfortunately, since TorchScript only supports basic data types, `CharactersToListTokenizer` had to be written as a separate class instead of using Lamda Function.
Will help users run into this error less often:
```
ValueError: comma is not supported by torchscript. Please use one of {'sentencepiece', 'space_punct', 'clip', 
'gpt2bpe', 'bert', 'space'}.
```
This covered by the `tests/integration_tests/test_torchscript.py::test_torchscript_e2e_text` test because this PR updates `TORCHSCRIPT_COMPATIBLE_TOKENIZERS` to …
=> Updated characters, underscore and comma preprocessors to be TorchScriptable.

ludwig/models/llm.py, ludwig/trainers/trainer.py, tests/integration_tests/test_llm.py
After training or fine-tuning, the best model checkpoint is loaded for evaluation. When loading an 8-bit quantized model that was fine-tuned on GPU, the following errors occur:
1. With no handling, the call to load_state_dict [here](https://github.com/ludwig-ai/ludwig/blob/03a0da09f9d01141717f7caed462aa83cf891c26/ludwig/trainers/trainer.py#L887) raises `RuntimeError: Loading a quantized checkpoint into non-quantized Linear8bitLt is not supported. Please call module.cuda() before module.load_state_dict()"`
2. If 1. is handled, a number of unexpected keys are returned from load_state_dict and an AssertionError is raised
These issues can be reproduced by running `tests/integration_tests/test_llm.py::test_llm_finetuning_strategies` with 8-bit quantization. Both issues are the result of custom …
=> fix: Load 8-bit quantized models for eval after fine-tuning

ludwig/models/llm.py, ludwig/schema/metadata/configs/trainer.yaml, ludwig/schema/trainer.py, ludwig/trainers/trainer.py, tests/integration_tests/test_llm.py, tests/integration_tests/test_trainer.py
This PR adds support in the finetune trainer to optionally enabled `gradient_checkpointing`.
Gradient checkpointing works by recomputing the activations of the model during the backward pass, rather than storing them in memory during the forward pass. This is a tradeoff between compute and memory, as the activations need to be recomputed during the backward pass, but the memory footprint is reduced. This is set to false by default because it is not always beneficial to use gradient checkpointing, and it can sometimes slow down training.
Gradient checkpointing is disabled by default. To enable it, you can simply set `enable_gradient_checkpointing` to True.
```yaml
trainer:
enable_gradient_checkpointing: true
```
This is useful when training very large models that run into out of memory …
=> Add support for gradient checkpointing for LLM fine-tuning

requirements.txt
Recent support for CodeLlama is only available in 4.33.0, but this import lies on the critical import path in Ludwig:
```
tests/conftest.py:35: in <module>
from ludwig.hyperopt.run import hyperopt
ludwig/hyperopt/run.py:11: in <module>
ludwig/api.py:78: in <module>
from ludwig.models.registry import model_type_registry
ludwig/models/registry.py:5: in <module>
from ludwig.models.llm import LLM
ludwig/models/llm.py:22: in <module>
from ludwig.utils.llm_utils import (
ludwig/utils/llm_utils.py:7: in <module>
from transformers import (
E   ImportError: cannot import name 'CodeLlamaTokenizer' from 'transformers' (/opt/homebrew/anaconda3/envs/ludwig/lib/python3.11/site-packages/transformers/__init__.py)
```
=> Bump min support transformers to 4.33.0

ludwig/trainers/trainer.py
Adds a conditional block to make sure quantization config is set before inspecting attributes of the quantization config
=> [CI] Fix failing tests on master

ludwig/schema/llms/base_model.py, tests/integration_tests/test_llm.py
Previously, we would raise an error if a local path was passed base_model in our config. This PR adds a check that verifies if the local path is valid before checking if it is a valid HF path.
=> Eliminate short-circuiting for loading from local

ludwig/trainers/trainer.py
Check `self.model.model.device.type == 'cuda'` rather than `self.device.type` when moving 8-bit models to GPU for #3606. In Trainer, `self.device` holds the string `"cuda"`, so checking `self.device.type` raises an AttributeError. Since we work with `self.model.model` directly in the following code block, it makes sense to bypass the Trainer and LLM objects, and get the model device from the model itself.
=> fix: Check underlying model device type when moving 8-bit quantized models to GPU at eval

ludwig/schema/llms/generation.py, ludwig/schema/utils.py
These param ranges were overly restrictive. See https://huggingface.co/docs/transformers/internal/generation_utils for more details.
=> Fixed range validation for text generation penalty parameters

ludwig/api.py
Updated a comment for generate() under LudwigModel in api.py so that it would automatically reflect in the Ludwig docs.
=> Update comment for predict to update Ludwig docs

ludwig/models/llm.py, ludwig/utils/hf_utils.py, tests/integration_tests/test_llm.py
Quality of life improvement - we used to set use_fast to False since the tokenizer was not natively written so it would take 2-4 minutes to load, however in newer `transformers` versions there is first class support so we no longer have to do this.
=> QoL: Default to using fast tokenizer for Llama models

ludwig/schema/encoders/image/torchvision.py
Fixed a typo in `EfficientNet`'s model variant that broke training
=> fixed typo in EfficientNet's model variant from v2_ to v2_s

ludwig/api.py
Used this discussion page as a reference: https://discuss.pytorch.org/t/how-can-we-release-gpu-memory-cache/14530/27
Added a function to LudwigModel to free GPU memory. Compared to the function in the discussion page, I did not move the individual parameters in a loop but instead just moved the entire model to CPU (this is clearer logic to read and results in a small amount of extra GPU memory freed), and I did not call `del` or `gc.collect()` (these two calls did not seem to impact GPU memory).
Credit to @justinxzhao for writing and testing the code.
=> Add function to free GPU memory

ludwig/config_validation/checks.py, requirements.txt, tests/ludwig/schema/test_model_config.py
Quantization can only be used with a local backend. This PR modifies our existing checks since they were not robust enough to catch the 4 total cases we should be accounting for.
=> Add check to ensure selected backend works with quantization for LLMs 

ludwig/models/llm.py
Get rid of parameter loading loop for Peft config because it was unnecessary
I'm just removing an unnecessary piece of logic from my previous PR that allowed for loading pretrained adapter weights. I had previously loaded a bunch of parameters into the peft config from our defaults, but after reviewing my code, I realized that I had already eliminated the logic that required this loading in the first place. All I need is the name of the HF repo, so I just eliminated the loading loop.
=> Remove unnecessary peft config updating

docker/ludwig-gpu/Dockerfile
Update base image to Ubuntu 18.04 to 20.04 to resolve this error in the build for for docker image `ludwig-gpu`.
```
#12 7.755 Unpacking cuda-keyring (1.0-1) ...
#12 7.779 Setting up cuda-keyring (1.0-1) ...
#12 7.861 Warning: apt-key output should not be parsed (stdout is not a terminal)
#12 7.881 Executing: /tmp/apt-key-gpghome.JznHdaISEj/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC F60F4B3D7FA2AF80
#12 7.943 gpg: keyserver receive failed: Cannot assign requested address
```
With EOSS for 18.04, it appears some of of the Ubuntu resources are being decommissioned: https://askubuntu.com/questions/1481617/randomly-get-gpg-keyserver-receive-failed-cannot-assign-requested-address
=> FIX: docker build error for ludwig-gpu

requirements.txt
Daft requirement renders Windows install near impossible. Wheels are not available and build needs to have Strawberry Perl + Rust\Cargo and to be able to compile OpenSSL from source (and I've not been able to successfully do so).
Can we consider not requiring getdaft when in a Windows environment, to enable to use Ludwig, at least until wheels are available? (ref: https://github.com/Eventual-Inc/Daft/issues/235)
With this PR, Ludwig installs fine on Python 3.9 on Windows, and I am able to perform a titanic training
=> Exclude getdaft on Windows

requirements.txt
PRs: 
https://github.com/Eventual-Inc/Daft/pull/1386
https://github.com/Eventual-Inc/Daft/issues/235
=> Add daft back for windows since the wheels are now officially published

ludwig/features/text_feature.py
The issue was that the metric function wasn't being moved/placed on the right device, leading to a weird behavior for these metrics using the `response` prediction key because the inputs that are passed in are not tensors, they're lists of strings. However, it seems like these metric functions need to moved to CUDA (instead of staying on the CPU) so that when the metric_fn.compute() call is called to gather evaluation metric summaries, it does not run into this error:
```sh
RuntimeError: Tensors must be CUDA and dense
```
Tested successfully with:
1. Only CPU machine
2. Multi-GPU Quantized training (4 GPUs)
3. Multi-GPU DeepSpeed Stage 3 training (4 GPUs)
=> Place metric functions for BLEU and Rogue on correct devices when using multiple GPUs

ludwig/contribs/mlflow/__init__.py
Addresses the issue of duplicate metrics being logged for the same step in MLFlow.
Credit for code goes to @justinxzhao
=> Remove duplicate metrics

ludwig/trainers/trainer.py, tests/integration_tests/test_api.py
`self._train_loop()` trains over a full epoch of data or up to the last training step, whichever is sooner, so we should only increment epochs when `last_batch()` is `True` as a check within `self._train_loop()`.
This fixes a potential issue with the last epoch being 1 too high when the training runway concludes partway through an epoch.
=> Increment epochs based on last_batch() instead of at the end of the train loop.

ludwig/schema/llms/base_model.py
* This change adds the "shortcut" to the HuggingFace location for the new Mistral-7B model.
* Please note that using Mistral-7B requires the latest HuggingFace transformers library (e.g., `pip install --upgrade git+https://github.com/huggingface/transformers` is advisable for the near term, until official release is verified).
`api.md` is automatically generated from the docstrings in the code, so if you want to …
=> [FEATURE] Include Mistral-7B model in list of supported base models

ludwig/api.py, ludwig/models/base.py, ludwig/models/llm.py, ludwig/schema/llms/peft.py, ludwig/trainers/trainer.py, ludwig/utils/dataset_utils.py, tests/integration_tests/test_llm.py, tests/integration_tests/utils.py
This set of changes aides towards improving code elegance.
It consists of the following improvements in parts of the codebase:
* Solving IDE warnings;
* Adding type hints;
* Fixing broken docstrings;
* Fixing PEP8 warnings and setting up `noqa` and `type ignore` escapes.
Much work towards these improvements can be done; this serves only as a small set surrounding LLM related modules.
`api.md` is automatically …
=> [MAINTENANCE] Partially reconcile type hints, fix some warnings, and fix comments in parts of the codebase.

ludwig/models/llm.py
There was a Ludwig user that was running into the following error:`If eos_token_id is defined, make sure that pad_token_id is defined.` There was also this Ludwig issue: https://github.com/ludwig-ai/ludwig/issues/3661
This PR introduces a workaround that fixes this problem. This PR has been successfully tested with the following models:
gpt2
codellama/CodeLlama-7b-hf
meta-llama/Llama-2-7b-h
=> Fix eos_token and pad_token issue

tests/integration_tests/test_llm.py
This change fixes the issue that after "tests/integration_tests/test_llm.py::test_local_path_loading" would run, a spurious directory would remain in the top directory of the Ludwig repository.  The fix consists of removing this directory after the assertions are done (as the last step of the test).
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that …
=> [BUGFIX] Remove spurious test directory at the end of the test_llm.py::test_local_path_loading test run

ludwig/trainers/trainer.py, requirements.txt
This PR adds nvidia-smi logging to tensorboard (specifically, it logs how much memory is being used over time). The numbers are not exactly the same as those outputted by nvidia-smi in the command line (the tensorboard logs show larger numbers than those shown by nvidia-smi in the command line), but are quite close.
[EDIT] After further investigation, nvidia-smi logging is unnecessary. This PR now offers per-device tensorboard logging and adds a new metric -- total_memory_used -- which should be more or less equivalent to what nvidia-smi shows.
=> Add per-device logging to tensorboard

ludwig/visualize.py
Binary variable labels would previously be displayed as 0 and 1 in the confusion matrix during visualization instead of as the actual labels. This change fixes that problem so the labels are displayed properly.
=> Fix binary variables being visualized as 0 and 1

ludwig/backend/base.py, ludwig/data/dataframe/pandas.py
* Resolving linting warnings -- making some methods static and including the proper type hints.
=> [MAINTENANCE] Fix the linting warnings in two backend component classes.

ludwig/trainers/trainer.py
https://github.com/ludwig-ai/ludwig/pull/3668 inadvertently moved the `on_epoch_end` callback to be invoked after the last batch has been processed, but before evaluation.
While technically still valid, this is a change from the previous behavior of `on_epoch_end` being called after evaluation, which may come as a surprise to users assuming evaluation results being present in `on_epoch_end`.
Note: `on_eval_end` is the recommended callback for handling fresh eval metrics.
=> Move on_epoch_end and epoch increment to after run_evaluation loop.

ludwig/api.py
Remove model_load_path from experiment because it does not line up with how Ludwig users should use `model.experiment()`.
See:
https://github.com/ludwig-ai/ludwig/issues/3705
=> Remove model_load_path from experiment

ludwig/backend/base.py
* Due to the problem of cycles within the Python annotation (e.g., a typehint could be used first before its declaration), we often have to enclose a typehint  within the quotes (and have to add a "# noqa F821" at the end).  However, if we add the import `from __future__ import annotations` at the top of the module, then we can use the typehint explicitly.  (Please see `https://peps.python.org/pep-0563/` for the details.).  Additional benefits include the need to import fewer types from `typing`, since the standard Python types can be used for typehints (e.g., `list[int]` instead of `List[int]`, etc.) and the ability to enclose all types that are being imported for the typehinting purposes only to be packaged under the `typing.TYPE_CHECKING` condition.
- a …
=> [FEATURE] Allow typehints without the quotes.

ludwig/models/llm.py
Otherwise it's far too noisy because it prints out for each `eval_batch_size` batch size which is very noisy
=> QoL: Only log generation config being used once at inference time

ludwig/backend/base.py, ludwig/data/dataset/base.py, ludwig/data/dataset/pandas.py
* Adding typehint annotations in backend and data components.
* Fixing a number of `mypy` errors (many more remain).
Note: this involved removing `create_trainer()` from `LocalTrainingMixin` and putting it directly into `LocalBackend` so as to satisfy the interface requirements of the `Backend` class.
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that …
=> [MAINTENANCE] Adding typehint annotations in backend and data components and fixing mypy errors.

ludwig/trainers/trainer.py
Otherwise these statements get logged for each of the worker processes which makes the logs unnecessarily noisy. They should really just come from the coordinator process / local rank 0.
=> QoL: Limit top-level trainer logging messages such as saving model or resuming model training to main coordinator process

ludwig/api.py, ludwig/config_validation/checks.py, ludwig/data/preprocessing.py, ludwig/explain/captum.py, ludwig/schema/metadata/configs/preprocessing.yaml, ludwig/schema/preprocessing.py, tests/integration_tests/test_preprocessing.py, tests/ludwig/config_validation/test_checks.py
Adds sample_size as a global preprocessing parameter, allowing users to specify exactly how many samples they want to train on instead of having to calculate the sample_ratio. Adds two integration tests to verify sample_size works as intended.
=> Add sample_size as a global preprocessing parameter

README.md
Adds 3 new notebooks:
1. For Llama-2-7b
2. For Llama-2-13b
3. For Mistral-7b using the blogpost Alex and I recently co-authored: https://predibase.com/blog/fine-tuning-mistral-7b-on-a-single-gpu-with-ludwig
I wanted to call them out explicitly here so that they're easy to get to from the early part of the README, and for SEO purposes
=> Add new fine-tuning notebooks to README

ludwig/models/llm.py, ludwig/schema/model_types/base.py, ludwig/schema/model_types/utils.py, ludwig/utils/llm_utils.py, tests/ludwig/schema/test_model_config.py, tests/ludwig/utils/test_llm_utils.py
TLDR; This fixes a bug in `model.evaluation()` that caused underreporting of performance metrics in a majority of cases. By setting max_new_tokens to the largest possible value _needed_, we ensure that the metric number from `model.evaluate()` are a good representation of true model performance.
---
This PR updates the config validation setter methods to ensure that the `generation.max_new_tokens` parameter in the model configuration is set correctly based on the maximum sequence length of the output features. This ensures accurate token generation for LLM model types. It also includes handling for different cases and provides informative logging for configuration changes. 
Specifically:
1. If the user sets max_new_tokens in generation to a value != the default value, it is respected as …
=> Dynamically set `max_new_tokens` based on output feature length, GMSL and model window size

ludwig/trainers/trainer.py
Fix for #3726 
```
2023-10-13T09:40:16Z [job] torch.cuda.device(i).utilization(),
2023-10-13T09:40:16Z [job] AttributeError: 'device' object has no attribute 'utilization'
```
API utilization from docs: https://pytorch.org/docs/stable/generated/torch.cuda.utilization.html#torch.cuda.utilization 
Tested on a GPU and this works correctly
=> Fix issue while logging cuda device utilization to tensorboard

requirements_distributed.txt
- Set a stricter limit on the `ray` version, so `2.4.0` doesn't cause anyone else any issues.
=> Limit ray versions to keep 2.4 out of the picture.

ludwig/constants.py, ludwig/distributed/base.py, ludwig/schema/trainer.py, tests/integration_tests/test_trainer.py
This small change provides two quality-of-life improvements:
* Enable more of the type hints to be used without the quotation marks.
* For common configuration strings, use defined constants (instead of hardcoded values).
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run …
=> [MAINTENACE] Improve typehints and use constants instead of common hardcoded string values.

ludwig/data/batcher/test_batcher.py, ludwig/data/dataset/pandas.py
We previously calculated a dataset's size from the length of whatever the "dataset" parameter was that was passed in. However, this parameter could have been a filepath, meaning that the dataset.size parameter would be set incorrectly, potentially causing index out of bound errors if the actual length of the dataset was shorter than the length of the filepath string.
This PR fixes this problem by calculating the size after the filepath has been processed into a dataset.
=> Fix calculation of dataset size

tests/integration_tests/test_automl.py
When the test `tests/integration_tests/test_automl.py::test_auto_train` is executed, the `"hyperopt"` directory remains in the main repository directory.  We clean this directory up by passing the `output_directory` argument to `auto_train()`.  By making this `output_directory` a relative path from the `tmpdir` fixture, it will be automatically deleted upon the completion of the test.
`api.md` is automatically …
=> [BUGFIX] Make sure that the "hyperopt" directory in the local repository path is deleted after test run is completed

ludwig/config_validation/checks.py, tests/ludwig/config_validation/test_checks.py
This is a problem since we always merge the tokens from the output feature at the end of the input feature + prompt tokens before making the forward pass through the LLM at fine-tuning time, so this would end up creating 2 instances of the output feature tokens incorrectly. 
This PR tries to mitigate this earlier by raising an error at config validation time.
=> Raise error if output feature name is in the prompt template

ludwig/models/llm.py, tests/ludwig/utils/test_error_handling_utils.py
Retries when this transient error occurs while downloading an LLM from HF Hub
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out. 
```
Also adds a suite of new tests to ensure that the default_retry decorator that exists in Ludwig works as intended.
=> Retry LLM model downloads from HF Hub with exponential backoff when there is a Read timeout

ludwig/trainers/trainer.py
As part of #3690, the end of epoch logic in `Trainer._train_loop` was refactored to run after evaluation. This move also caused the epoch increment to happen after evaluation and after metrics logging, which made the reported epoch off by one.
This update moves the epoch increment before evaluation while leaving the remaining end of epoch logic after evaluation.
=> Increment the epoch before running evaluation

ludwig/modules/metric_modules.py, requirements.txt
While trying to figure out why my air-gapped installation and deployment of Ludwig was failing to detect my cached copy of the `punkt` tokenizer for `nltk`, I came across https://github.com/Lightning-AI/torchmetrics/issues/1779 which got merged into `torchmetrics==1.0.0`... but Ludwig was avoiding that version.  So I forcibly installed `torchmetrics==1.2.0` (latest) in my image (after installing Ludwig), ignored `pip`'s words of caution, and managed to run some LoRA-based fine-tuning without a hitch!  Since that code path worked okay with the updated library, I'm submitting this PR to remove the pin and leaning on CI to help identify if there are issues on other code paths or if it's truly safe to release.
=> Uncap the torchmetrics version, so we can get fixes in 1.0+.

requirements.txt
The version `2023.10.0` or the `fsspec` library was released on 10/21/2023.  Unfortunately, it breaks the `builder.py::as_dataset()` method of the HuggingFace "datasets" library version in use with the error `NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.` being raised.  Hence, we restrict the `fsspec` version for the time being.
`api.md` is automatically generated from the …
=> [MAINTENANCE] Restrict "fsspec" to not include the latest version "2023.10.0"

ludwig/datasets/loaders/dataset_loader.py, ludwig/datasets/loaders/hugging_face.py
* This change resolve the method signature inconsistency between `HFLoader` and its parent class `DatasetLoader` concerning the `load()` method, and its usage in "tests/ludwig/datasets/test_datasets.py::test_hf_dataset_loading".
* Method arguments are documented for `HFLoader.load()` and `DatasetLoader.load()`.
* Return typehints for `DatasetLoader` and `HFLoader` fixed to accurately reflect the types of return values.
* New style typehints are introduced, reducing the amount of `typing` imports required.
* Minor cleanup (e.g., make methods `static` using `@staticmethod` where appropriate; deleting unused variables).
- a reproducible test for your PR (code, config and data …
=> [MAINTENACE] Fixing method overload violations; providing typehints and method argument documentation

ludwig/models/llm.py, ludwig/models/predictor.py, ludwig/utils/llm_utils.py, tests/ludwig/utils/test_llm_utils.py
The previous implementation of this function was modifying the target and prediction tensors in place, which is incorrect. It didn't matter at training time because the modified tensors are what we needed to calculate metrics.
However, at prediction time, we aggregate the prediction tensors and this causes the prediction tensor shapes during aggregation to have the wrong shape/size. Specifically in this code block here: https://github.com/ludwig-ai/ludwig/blob/master/ludwig/models/predictor.py#L256
- Line 256 returns the a dictionary with the right tensors shapes
- Line 257 transforms the dictionary structure and preserves the right tensor shapes
- Line 258 updates the metrics, but the issue comes from the fact that we realign tensors to have the correct shape …
=> Fix: Prevent memory from ballooning during post-training evaluation

requirements.txt
Adds an upper-bound to the version of `getdaft`, since Daft introduces a backward-incompatible change in v0.2.0 that deprecates passing in fsspec filesystems into its APIs.
To pass credentials, Daft now includes a `IOConfig` API that can be used.
=> Pin getdaft<0.2 in requirements

ludwig/distributed/deepspeed.py
This PR ensures that DeepSpeed does not throw an error on resume when loading adapter checkpoints.
Adapter checkpoints only contain a subset of the model's weights. This means that strict checkpoint loading throws a RuntimeError that may look like the following: 
```
> /home/ray/anaconda3/lib/python3.8/site-packages/ludwig/trainers/trainer.py(839)train()
-> self.resume_weights_and_optimizer(training_checkpoints_path, checkpoint)
/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/trainers/trainer.py(1466)resume_weights_and_optimizer()
-> CheckpointManager.load_latest_checkpoint(checkpoint, model_weights_progress_path, self.device)
/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/utils/checkpoint_utils.py(332)load_latest_checkpoint()
-> checkpoint.load(last_ckpt, device) …
```
=> fix: adapter checkpoint loading on resume

ludwig/trainers/trainer.py
When a model was resumed from a checkpoint, the progress bar shown would start from 0, giving the user the impression that training was starting from scratch. This PR fixes that. 
NOTE: the internal step counter was correct and is unaffected by this change.
=> fix LudwigProgressBar rendering on model resume

ludwig/model_export/base_model_exporter.py, ludwig/model_export/onnx_exporter.py, tests/ludwig/model_export/test_onnx_exporter.py
- a simple set of classes to do onnx export of pytorch models
=> OnnxExporter

ludwig/contribs/mlflow/__init__.py, ludwig/models/predictor.py, ludwig/trainers/trainer.py, ludwig/trainers/trainer_llm.py, ludwig/utils/trainer_utils.py, tests/ludwig/utils/test_trainer_utils.py
Adds LLM predictions to MLFlow during evaluation. Local behavior shows inputs, outputs, and prompts added to a csv file in the MLFlow logs.
=> Add k eval predictions to mlflow for LLM fine-tuning

ludwig/contribs/mlflow/__init__.py, ludwig/trainers/trainer_llm.py
- Swaps API to use `log_dict` instead of `log_table` since `log_dict` also works with MLFlow 1.x but `log_table` was only introduced in MLFlow 2.4
- Removes trailing newline spaces while logging k examples
=> Fix MLFlow logging for sample outputs during evaluation.

README.md
We need explicit reference to the comprehensive `CONTRIBUTOR.md` file in `README.md` so that users can easily find it.
=> [MAINTENANCE] Provide links to contributor guide in README.md

ludwig/api.py, ludwig/models/llm.py, ludwig/utils/llm_quantization_utils.py
This PR adds support for converting a quantized 4-bit base LLM model (in either `nf4` or `fp4` data types via bitsandbytes) into an upscaled float16 variant.
To use this function, it's as simple as:
1. Create a Ludwig config where quantization is set and bits = 4
2. Instantiate the LudwigModel class
3. Call `model.save_dequantized_base_model(save_path)`
You can also call this function after model training. The only caveat is that you will have to call `LudwigModel.load("/saved/artifact/path")` to reload the model with the trained adapter.
---
```python
import yaml
config = """
base_model: meta-llama/Llama-2-7b-hf
quantization:
bits: 4
...
"""
config = yaml.safe_load(config)
model = LudwigModel(config)
... # Optionally call model.train(), …
```
=> Add support for dequantizing 4-bit bitsandbytes base models into fp16

ludwig/modules/metric_modules.py
Fixes the following warning:
```
FutureWarning: Importing `CharErrorRate` from `torchmetrics` was deprecated and will be removed in 2.0. Import `CharErrorRate` from `torchmetrics.text` instead.
```
=> [Maintenance] Fix deprecation warning for CharErrorRate

ludwig/visualize.py
Currently, Ludwig visualization seems to be slightly broken when passing in test_statistics. We try to compare metrics that contain dict values instead of floats, causing the code to break.
This adds the dict metrics to our list of ignored metrics during visualization.
=> Remove dicts from comparison metrics during visualization

ludwig/trainers/trainer.py
Bypass MLFlow to log LLM outputs because of complications regarding the different MLFlow methods (log_dict does not interact well with our current MLFlow endpoint).
This is what the directory structure looks like:
=> Log LLM test set evaluation outputs to CSV files under the model log directory, stamped by checkpoint number.

ludwig/api.py, ludwig/utils/hf_utils.py, ludwig/utils/upload_utils.py, tests/ludwig/utils/test_hf_utils.py
This is useful for uploading any local files to huggingface hub. In particular, I use this for saving dequantized base model weights. Usage is very simple!
```python
from ludwig.utils.hf_utils import upload_folder_to_hfhub
upload_folder_to_hfhub(repo_id="", folder_path="")
```
This will create a repository on huggingface hub if it doesn't exist, and upload all files in the local folder to huggingface hub at that repo id.
There are a variety of **optional** **parameters** that can be specified:
- repo_type (str, optional): The type of the repository ('model', 'dataset', or 'space'). Defaults to 'model'.
- private (bool, optional): If True, the repository will be private; otherwise, it will be public. Defaults to False.
- path_in_repo (str, optional): The relative path within the repository …
=> Add utility function for uploading local folders to huggingface hub

ludwig/schema/llms/peft.py, ludwig/schema/metadata/configs/llm.yaml, tests/integration_tests/test_llm.py
Paper: https://arxiv.org/pdf/2205.05638.pdf
Adds support for a new PEFT strategy called IA3, which adds 2 learned vectors to the V and Q projections in attention heads, as well as a learned vector to the feed-forward network. The idea is that these learned vectors can help rescale the attention values and feed-forward network values. l_k, l_v, and l_ff are all initialized with ones so that the overall function computed by the model does not change when they are added.
IA3 makes mixed-task batches possible because each sequence of activations in the batch can be separately and cheaply multiplied by its associated learned task vector (in some ways, very similar to how you can train different rank decomposed matrices with LoRA for each task). In the event that a model will only be used on a …
=> Add support for IA3 PEFT Strategy

requirements.txt
Transformers 4.36 was released today and seems to bring with it some strange issues during the backward pass at training time that need to be addressed. 
Pinning for now as we investigate how to make Ludwig compatible with the latest version of transformers
=> Pin Transformers to < 4.36

ludwig/utils/fs_utils.py, ludwig/utils/upload_utils.py, tests/ludwig/utils/test_upload_utils.py
* This change updates Ludwig to handle changes introduced in HuggingFace PEFT 0.7.0: Adapter weights are now stored in the ".safetensors" format, instead of the PyTorch default Pickle ".bin" format.  This change caused Ludwig to error when uploading the trained model to HuggingFace, because Ludwig verifies acceptable file extensions.  With this change, both are allowed for now; however, there is a "TODO" to formalize the deprecation policy, and subsequently discontinue supporting ".bin" format.
* The new test module for testing upload functionality is created and contains the initial tests for the new model file format.
* Enhancements in type hinting and improvements to exception types in "upload_utils.py" is also included with this change.
* Please note that even though HuggingFace PEFT …
=> [MAINTENANCE] Support Adapter Model ".safetensors" File Format During HF Upload

ludwig/models/llm.py, ludwig/utils/llm_utils.py
This is a small PR to move two methods out of the LLM object and into utils so they can be reused for text encoders. The two methods/functions are:
- `initialize_adapter` - wraps a pretrained model with a PEFT model, with support for new and pretrained adapters
- `to_device` - moves a pretrained model to device with logic to shard the model over multiple GPUs.
=> Move reusable LLM model methods to utility functions

ludwig/models/llm.py
This will prevent the quantization config from unnecessarily getting written to disk like it was before (doesn't actually cause any issues though):
```
"_name_or_path": "meta-llama/Llama-2-7b-chat-hf",
"architectures": [
"LlamaForCausalLM"
],
"attention_bias": false,
"bos_token_id": 1,
"eos_token_id": 2,
"hidden_act": "silu",
"hidden_size": 4096,
"initializer_range": 0.02,
"intermediate_size": 11008,
"max_position_embeddings": 4096,
"model_type": "llama",
"num_attention_heads": 32,
"num_hidden_layers": 32,
"num_key_value_heads": 32,
"pretraining_tp": 1,
"quantization_config": {
"bnb_4bit_compute_dtype": "float16",
"bnb_4bit_quant_type": "nf4",
"bnb_4bit_use_double_quant": true,
"llm_int8_enable_fp32_cpu_offload": false,
"llm_int8_has_fp16_weight": false,
"llm_int8_skip_modules": null, …
```
=> Remove quantization config before saving dequantized weights to disk

ludwig/models/llm.py, ludwig/schema/llms/base_model.py, ludwig/schema/model_types/utils.py, ludwig/utils/llm_utils.py
In Transformers 4.36, the transformers library added support for Phi-1 and Phi-1.5 models from Microsoft. However, there are two caveats with using this model:
1. The original models, `microsofot/phi-1` and `micosoft/phi-1.5` don't work out of the box since they require `remote_code` to be trusted because the tensor operations are implemented through `einops` instead of PyTorch. Instead, in the original PR that adds support for Phi based models, they add two models that are supported (https://github.com/huggingface/transformers/pull/26170/files#diff-88cb36bfb13c1dc5f52bb952b74697a1c79e286a1a57e4ed3f20ecd5e9f8749bR25): 
- `susnato/phi-1_dev`
- `susnato/phi-1_5_dev`
This is the recommendation from official phi model docs on huggingface as well: …
=> Add support for Phi-1 and Phi 1.5

ludwig/encoders/text_encoders.py, ludwig/models/llm.py, ludwig/schema/encoders/text_encoders.py, ludwig/utils/checkpoint_utils.py, ludwig/utils/llm_utils.py, tests/integration_tests/test_llm.py, tests/ludwig/encoders/test_llm_encoders.py
This adds a text encoder for ECD that wraps a pretrained LLM and passes the model's hidden state downstream to the combiner. We reuse large portions of the LLM model type's utitilies, refactored as utility functions rather than `LLM` methods.
The encoder subclasses `SequenceEncoder` and implements custom behavior for working with LLMs, with pieces borrowed from `LLM`. Whereas the `LLM` model type is focused on text generation, the encoder is focused on 1) passing hidden state downstream for predictive tasks and 2) packaging the adapter with the rest of the ECD architecture. Major methods include
- `__init__`: Loads the pretrained model and adapter from config
- `forward`: Takes tokenized text as input and returns the hidden state of the last layer
- `_save_to_state_dict`: Normally, …
=> Add LLM Text Encoder

requirements.txt
Follow on from #3832 to also pin huggingface-hub to latest version.
=> enh: Updating requirements to pin `huggingface-hub>=0.19.0`

requirements.txt
They just issued a patch release for our bug, so we can unpin. There's also no reason to pin huggingface-hub since Ludwig will install the right version based on `transformers`.
=> Unpin transformers in favor of 4.36.2

ludwig/schema/trainer.py
Updates LLM trainer defaults to use parameters that work well out of the box so that they don't need to be set in the trainer config!
=> Update LLM trainer defaults

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_llm_encoders.py
When using an adapter, the LLMEncoder uses custom `state_dict()` ans `load_state_dict()` logic to only save/load adapter parameters, however loading would fail when using strict mode due to
- The base model's parameters being excluded from `state_dict` (`missing_keys`)
- The adapter parameters being recorded under different names under the hood by peft (`unexpected_keys`)
None of these keys are missing or unexpected under the custom logic, though, so the lists of missing and unexpected keys must be updated to reflect our expected state. This PR adds a post-load hook that updates the `missing_keys` and `unexpected_keys` lists to reflect our custom logic, and it re-enables a unit test that checks loading adapter state.
=> fix: Handle missing and unexpected keys during LLMEncoder state dict load

ludwig/schema/llms/peft.py
The adapter config objects have `name` and `description` classmethods that are used in the docs. `IA3Config` did not include implementations, so LLM config reference pages in the docs were not being rendered.
=> fix: Add `name` and `description` classmethods to `IA3Config`

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_llm_encoders.py
Followup to #3841. When loading the state dict with fully-qualified parameter names, the post-load hook was unable to properly compare missing keys with local model parameter names. For example, when attempting to remove the key `encoder.model.base_model.model.model.embed_tokens.weight` from the missing keys list, the hook would only be have access to the parameter name `model.base_model.model.model.embed_tokens.weight`.
This adds a parameter name prefix computation to the hook and updates the load_state_dict unit tests to include a wrapper for validating that fully-qualified names are loaded correctly.
=>  fix: Handle missing and unexpected keys during LLMEncoder state dict load, part 2

ludwig/schema/llms/base_model.py, ludwig/schema/model_types/utils.py
PEFT 0.7.1 doesn't have a default LoRA target module mapping: https://github.com/huggingface/peft/blob/8665e2b5719faa4e4b91749ddec09442927b53e0/src/peft/utils/constants.py#L49
This PR adds support to default to `q_proj` and `v_proj` for mixtral and mixtral instruct in the instance that the `target_modules` aren't explicitly specified for mixtral.
=> Add default LoRA target modules for Mixtral and Mixtral instruct

ludwig/distributed/base.py, ludwig/models/predictor.py, ludwig/trainers/trainer.py, requirements.txt
A few weeks ago, we merged https://github.com/ludwig-ai/ludwig/pull/3830 to temporarily get around an issue of fine-tuning with gradient checkpointing that was introduced with Transformers 4.36. The original issue can be seen here: https://github.com/huggingface/transformers/issues/28023
Since then, they've released a patch release (Transformers 4.36.2) that fixes the original issue for all model types, including Llama-2, Mixtral, Phi etc. However, it seems like the overall interaction between the new transformers version and our hacky fix leads to memory ballooning because we manually map each module to the correct mode, and in the process, set some modules to train mode when they shouldn't be which causes the memory to balloon. 
This PR is no longer needed if transformers is set to use …
=> Revert hack that leads to OOM during fine-tuning

ludwig/cli.py, ludwig/export.py, ludwig/utils/carton_utils.py, requirements_serve.txt, tests/integration_tests/test_carton.py
As previously discussed with @tgaddair, this PR adds support for exporting Ludwig models to [Carton](https://carton.run/).
https://github.com/VivekPanyam/carton/issues/162
[Carton](https://carton.run/) is a library with the goal of allowing users to run any ML model from any programming language.
It currently supports C, C++, Rust, and Python with support for other languages in progress (NodeJS, OCaml, C#). See the link above or the repo at https://github.com/VivekPanyam/carton for more details.
This PR is heavily based on the `export_neuropod` functionality already implemented in Ludwig. It mirrors the implementation and integration tests.
Added an integration test and verified that it passes locally.
- Add `export_carton` to the documentation
- Confirm that the integration test is …
=> Add support for exporting models to Carton

requirements.txt
Required for transformers 4.36
```
The conflict is caused by:
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
ludwig 0.9.dev0 depends on tokenizers>=0.13.3
ludwig[test] 0.9.dev0 depends on tokenizers>=0.13.3
transformers 4.36.2 depends on tokenizers<0.19 and >=0.14
ludwig 0.9.dev0 depends on tokenizers>=0.13.3
ludwig[test] 0.9.dev0 depends on tokenizers>=0.13.3
transformers 4.36.1 depends on tokenizers<0.19 and >=0.14
ludwig 0.9.dev0 depends on tokenizers>=0.13.3
ludwig[test] 0.9.dev0 depends on tokenizers>=0.13.3
transformers 4.36.0 depends on tokenizers<0.19 and >=0.14
```
Tokenizers 0.14 is linked to huggingface hub < 0.17, but transformers 4.36 requires huggingface hub >= 0.19
=> [Maintenance] Bump minimum tokenizers to 0.15

ludwig/utils/algorithms_utils.py, tests/ludwig/utils/test_algorithm_utils.py
There was a main script in the algorithm_utils file for testing. I removed it and created a unit test for it.
=> Convert test main script in algorithm_utils to unit test

ludwig/hyperopt/run.py
Currently a bug in the main Ludwig hyperopt codepath where it assumes the config is an object, but the passed in config also allows the config to be a "str". If it is a str, then we assume it's a path and load the config from disk. Unfortunately, our check to make sure that the 'hyperopt' section of the config is present is incorrect. 
This was reported in #3850 and closes this issue.
=> Allow hyperopt config to be loaded from a file

ludwig/trainers/trainer.py, ludwig/trainers/trainer_llm.py
If the textual data in the validation dataset contains non-ASCII characters, saving the results to storage may encounter errors, such as:
```
UnicodeEncodeError: 'ascii' codec can't encode character '\u2260' in position 2699: ordinal not in range(128)
```
The fix consists of defensively converting the contents to the `UTF-8` format.
This error was not observed in isolated GPU environments such as while using EC2 outside of Colab, but this change assure stable behavior in all environments.
=> [BUGFIX] Guard against UnicodeEncodeError when saving validation results in Google Colab environment

docker/ludwig-ray-gpu/Dockerfile, docker/ludwig-ray/Dockerfile, requirements.txt
Fixes an issue with the previous docker image build where torchdata 0.7.1 doesn't seem to play nicely when installed with cuda118 because of libssl errors. 
Torch 2.1.0 ships with torchdata 0.7
=> Docker image fixes part 2: pin to torch==2.1.0, add dependency for urllib<2

ludwig/encoders/text_encoders.py, ludwig/models/ecd.py, tests/ludwig/encoders/test_llm_encoders.py
The LLM model type initializes the adapter weights and quantization at training time using `LLM.prepare_for_training`. When `LLMEncoder` was added, ECD model did not have a corresponding `prepare_for_training` method, so adapter initialization occurred at encoder initialization. This PR adds `ECD.prepare_for_training`, which brings `LLMEncoder` adapter initialization to parity with LLM models.
=> Add custom `prepare_for_trianing` logic to ECD model for LLM encoder adapter initialization

docker/ludwig-gpu/Dockerfile, docker/ludwig-ray-gpu/Dockerfile, docker/ludwig-ray/Dockerfile, docker/ludwig/Dockerfile, ludwig/backend/ray.py, ludwig/data/dataset_synthesizer.py, ludwig/features/audio_feature.py, ludwig/utils/audio_utils.py
We need to add `libsox-dev` because it's needed for torchaudio 2.1.0 which ships with torch 2.1.0. It fixes this error:
```
load requires sox extension which is not available. Please refer to the stacktrace above for how to resolve this.
```
This also requires updating the way we use the torchaudio backend, which is now an argument that's passed into the load/save methods as opposed to using an instance of the backend object directly.
=> [Maintenance] Docker Image Fix part 3: fix torchaudio 2.1.0 dependencies by installing `libsox-dev` and update API

ludwig/api.py, ludwig/utils/llm_utils.py
This PR introduces a new boolean flag called `streaming` to the LudwigModel.generate() API which allows users to see streaming output when performing zero-shot inference on single or multiple samples. 
https://github.com/ludwig-ai/ludwig/assets/106701836/50fc01db-837b-4689-8e8a-8da491481da1
```python
import yaml
import logging
config = yaml.safe_load(
"""
base_model: meta-llama/Llama-2-7b-chat-hf
quantization:
bits: 4
- name: instruction
type: text
output_features:
- name: output
type: text
generation:
max_new_tokens: 64
temperature: 0.1
trainer:
type: none
backend:
type: local
"""
)
model = LudwigModel(config, logging_level=logging.INFO)
output = model.generate("What is the meaning of life?", …
```
=> Add streaming support for zero shot inference

ludwig/trainers/trainer.py
Fixes the following warnings in newer versions of Torch (>= 2.1.0)
```
/home/ray/anaconda3/lib/python3.8/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint:
please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be 
updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that 
you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
```
and 
```
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
```
=> Set use_reentrant to False for gradient checkpointing

.github/workflows/pytest.yml
We had a nightly failure: `https://github.com/ludwig-ai/ludwig/actions/runs/7545437935/job/20541040550?pr=3883`.
=> [BUGFIX] Pinning torch nightly to January 13, 2024 to avoid AttributeError

.github/workflows/upload-pypi.yml
=> Using Trusted Publishers for uploading to PyPi.

ludwig/utils/llm_utils.py, requirements.txt
It works nicely, no need to use the `susnato` version, but we need to pin transformers to the commit that introduce the GQA implementation in transformers: https://github.com/huggingface/transformers/commit/55090585619d7ab880d9a7d7c8b327a746f7cc40
=> Add support for official `microsoft/phi-2`

ludwig/utils/llm_utils.py, requirements.txt
Reverting since it breaks our Docker image builds. Need to debug that but will come back to it soon.
=> Revert "Add support for the official `microsoft/phi-2` model (#3880)"

ludwig/utils/tokenizers.py
Follow up from https://github.com/ludwig-ai/ludwig/commit/9eb113b7b407ab5dd0e7c1f69f715fb8af8ca85e 
Ensures that all of the tokenizers for the models listed in https://github.com/ludwig-ai/ludwig/blob/master/ludwig/schema/llms/base_model.py#L20 have the correct initialization.
=> Ensure correct padding token for Phi and Pythia models

tests/integration_tests/test_llm.py, tests/ludwig/encoders/test_llm_encoders.py
This adds adalora to the list of adapters available to `LLMEncoder` and adds adalora to the existing test suite.
=> Enable AdaLoRA tests for LLM adapter

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_llm_encoders.py
`LLMEncoder` fine-tuning is currently blocked by two issues:
- `RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float.`
- As a result of #3874, the final layer of the base model is no longer frozen until training time, potentially leading to an "unused parameters" error
This PR adds fixes for both issues:
- `LLMEncoder` output is now explicitly cast to `torch.float32`
- The final layer of the base model is always frozen in `LLMEncoder.__init__`
=> Cast `LLMEncoder` output to `torch.float32`, freeze final layer at init.

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_llm_encoders.py
This adds support for IA3 adapters to `LLMEncoder` and updates the `LLMEncoder` tests to cover it.
=> Enable IA3 adapters in `LLMEncoder`

requirements.txt, requirements_distributed.txt
=> Pin deepspeed to < 0.13 and pandas to < 2.2.0

ludwig/models/embedder.py, ludwig/models/retrieval.py, ludwig/trainers/trainer.py, ludwig/trainers/trainer_llm.py, ludwig/utils/batch_size_tuner.py, tests/integration_tests/test_llm.py, tests/integration_tests/test_trainer.py
This PR extends Ludwig's batch size tuning functionality to LLMs.
For each batch size, we generate synthetic data in the following way:
We consider three values:
(1) The sum of the max_sequence_lengths of the input feature and the output feature
(2) The global_max_sequence_length
(3) The model's context length
If (1) is the smallest, then we generate synthetic inputs and outputs with the corresponding max_sequence_lengths.
If (2) is the smallest, then we generate synthetic inputs and outputs with length global_max_sequence_length/2 + 1.
If (3) is the smallest, then we generate synthetic inputs and outputs with length context_len/2 + 1.
=> Add batch size tuning for LLMs

ludwig/schema/model_types/utils.py, ludwig/utils/llm_utils.py
These modules maximize performance, also the current LoRA target modules for Phi-2 are wrong on the PEFT repo.
See #3910
=> Add default LoRA target modules for Phi-2

ludwig/schema/llms/generation.py, ludwig/schema/metadata/configs/llm.yaml
Implements support for [Prompt Lookup Decoding](https://github.com/apoorvumang/prompt-lookup-decoding) by exposing a new generation config parameter called `prompt_lookup_num_tokens`. Compatible with transformer version >= 4.37.0.
In scenarios where the prompt is long and the output generated might re-use a lot of common ngrams, this can speedup token generation by near 2x - 2.4x. However, in scenarios where that may not be the case, such as open-ended questions, it leads to a 10% decrease in tokens per second.
https://drive.google.com/file/d/1E8qq8HnJBhL7GOuFDuMdih_GY1aAVwEC/view?usp=sharing
```python
import yaml
import logging
config = yaml.safe_load(
"""
base_model: meta-llama/Llama-2-7b-chat-hf
quantization:
bits: 4
- …
```
=> Add support for prompt lookup decoding during generation

requirements.txt
Seems like the latest Pyarrow release is incompatible with Ray 2.3.1: https://github.com/ludwig-ai/ludwig/actions/runs/7679371027/job/20930200980
=> Pin pyarrow to < 15.0.0

ludwig/trainers/trainer.py, ludwig/utils/config_utils.py, tests/ludwig/utils/test_config_utils.py
Using `LLMEncoder` with 8-bit quantization can lead to the same error addressed by #3606. This happens because the quantization check does not account for quantization config nested in the encoder block. This adds a utility for retrieving all quantization information from a config, including accounting for multiple quantized encoders, and updates the trainer to use this utility.
=> fix: Add Nested quantization check

ludwig/utils/config_utils.py, tests/ludwig/utils/test_config_utils.py
`ludwig.utils.config_utils.get_quantization` returns the value of `quantization.bits` for LLM model types (either `int` or `None` type), but for ECD it returns a list of values to account for multiple LLM encoders. To simplify checking the quantization, `get_quantization` now returns a list in every case.
=> fix: Always return a list of quantization bits values from `get_quantization`

ludwig/trainers/trainer.py
Got the following error when training Mixstral-7b in a multi-GPU setting:
```
tensor at position 96:
saved metadata: {'shape': torch.Size([142]), 'dtype': torch.int64, 'device': device(type='cuda', index=1)}
recomputed metadata: {'shape': torch.Size([143]), 'dtype': torch.int64, 'device': device(type='cuda', index=1)}
tensor at position 97:
saved metadata: {'shape': torch.Size([142]), 'dtype': torch.int64, 'device': device(type='cuda', index=1)}
recomputed metadata: {'shape': torch.Size([143]), 'dtype': torch.int64, 'device': device(type='cuda', index=1)}
...
```
This can be resolved by setting reentrant to True ensures
> Reentrant checkpoint always recomputes function in its entirety during the backward pass.
Source: https://pytorch.org/docs/stable/checkpoint.html
So shape mismatches …
=> fix: set `use_reentrant` to `True` to fix `Mixtral-7b` bug

ludwig/schema/llms/peft.py, tests/integration_tests/test_llm.py
We are disabling `AdaptionPrompt` temporarily, until incompatibility with the `forward()` signature in HuggingFace PEFT is fixed.
=> Disabling AdaptionPrompt till PEFT is fixed.

ludwig/models/llm.py, ludwig/utils/llm_utils.py, tests/integration_tests/test_llm.py, tests/ludwig/utils/test_llm_utils.py
Prior to this change, we used pad token at the end of target tensor. This was okay because many of the new LLMs trained with pad token == eos token. With Gemma, there is a separate eos token. The issue now is that, during generation, Gemma cannot produce an eos token, so generation never stops. We now use eos token during fine-tuning so that LLMs are guaranteed to learn how to stop during the generation step.
=> fix: use eos token in target tensor for instruction-tuning

ludwig/datasets/configs/imdb_genre_prediction.yaml
Pulled the dataset file manually from the download link, and here are the columns:
```Rank,Title,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Genre_is_Drama```
=> fix: Update imdb_genre_prediction dataset yaml to match dataset

ludwig/schema/decoders/image_decoders.py, ludwig/schema/features/preprocessing/image.py, ludwig/schema/metadata/configs/encoders.yaml, tests/ludwig/utils/test_image_utils.py
This is a follow up to PR 3913. 
It adds unit tests for the image utils functions added by that PR.
=> Add unit tests for image utils unet functions

.github/workflows/pytest.yml
We get an error while installing PyTorch nightly:
```
ERROR: HTTP error 403 while getting https://download.pytorch.org/whl/nightly/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (from https://download.pytorch.org/whl/nightly/cpu/nvidia-cuda-nvrtc-cu12/)
2024-02-12T19:11:26.3258455Z ERROR: Could not install requirement nvidia-cuda-nvrtc-cu12==12.1.105 from https://download.pytorch.org/whl/nightly/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (from torch) because of HTTP error 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/nightly/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl for URL https://download.pytorch.org/whl/nightly/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (from …
```
=> [MAINTENANCE] Comment Out PyTorch Nightly Test

ludwig/schema/trainer.py, ludwig/trainers/trainer_llm.py, ludwig/utils/batch_size_tuner.py, tests/integration_tests/test_llm.py
One can now set `eval_batch_size` to `auto` for LLMs when using the local backend during fine-tuning. This may help select a larger eval batch size to help reduce time spent during evaluation.
=> Add support for eval batch size tuning for LLMs on local backend

ludwig/features/image_feature.py
In image_feature.py, image bytes instance type is handled by all the _read_image_ routines, except for preprocessing. 
added the same bytes instance logic to the _finalize_preprocessing function.
tested the mnist example, with image paths as well as image bytes objects.
=> Allow image bytes type during preprocessing

ludwig/features/text_feature.py, tests/ludwig/features/test_text_feature.py
Following code changes fixes the bug identified in #3985
=> Minor change to fix the incorrect response truncation

CONTRIBUTING.md, README.md
* All Slack links are replaced with links referring to the "Predibase / LoRAX / Ludwig" community on Discord.
* There is a sibling [documentation pull request.](https://github.com/ludwig-ai/ludwig-docs/pull/358)
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run `mkdocs/code_docs_autogen.py`, which …
=> [MAINTENANCE] Replace Slack links with Discord links.

ludwig/data/preprocessing.py, ludwig/encoders/image/base.py, ludwig/models/base.py, ludwig/models/llm.py, ludwig/utils/automl/utils.py, ludwig/utils/image_utils.py, ludwig/utils/server_utils.py, ludwig/utils/visualization_utils.py, requirements_viz.txt, setup.cfg
* We must pin `matplotlib` to `"<3.9.0"`, because the latter (released on 5/15/2024), cause API incompatibilities:
```
-------- generated xml file: /home/runner/work/ludwig/ludwig/pytest.xml --------
=========================== short test summary info ============================
ERROR tests/integration_tests/test_visualization.py - AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'
ERROR tests/integration_tests/test_visualization_api.py - AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
==== 2 skipped, 4[93](https://github.com/ludwig-ai/ludwig/actions/runs/9151376924/job/25157299861?pr=3981#step:7:94)3 deselected, 2 warnings, 2 errors in 357.57s (0:05:57) ===== …
```
=> [MAINTENANCE] Most Recent Version of matplotlib breaks ptitprince and seaborn method calls.

ludwig/encoders/image/base.py
* Make the implementation for the fix of the `ViTEncoder` to ensure that the `transformers.ViTModel` returns the `output_attentions` more elegant (and cuts on the amount of code).
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run `mkdocs/code_docs_autogen.py`, which will create …
=> [MAINTENANCE] Refactor and clean up.

ludwig/schema/common_fields.py
The options for the EmbeddingInitializerField are displayed twice in the documentation. 
This is due to the fact that both the field in the Ludwig repro and the build logic in the documentation append the options list to the description string in this particular case.
The problem has been solved by removing this logic from the field. The documentation takes over the task of appending this information.
See issue in [documentation repo](https://github.com/ludwig-ai/ludwig-docs/issues/366).
There should be a discussion about what the right path is. At the moment, different fields handle the task differently. Sometimes the documentation is supposed to assemble the string, sometimes the field does it itself.
=> Fixed options dublicate in documentation for EmbeddingInitializerField
