ludwig-ai/ludwig

mkdocs/docs/faq.md
=> Fix typo faq.md

Dockerfile
Adding a Dockerfile for running Ludwig on a CPU using the Tensorflow base image.
As soon as I get home, I will try to create a Dockerfile for using a GPU.
=> Add Dockerfile for running Ludwig on a CPU

ludwig/data/preprocessing.py, ludwig/features/image_feature.py, tests/integration_tests/test_experiment.py
Current method to check for HDF5/JSON file wouldn't work if the extension is in upper / mixed case. PR to overcome the same :) !
Fixes uber/ludwig/issues/64
Thanks,
Hem
=> File-extension replacement

docs/api/index.html
=> fixes typo

ludwig/experiment.py, ludwig/train.py
=> Fix inconsistent issue when calling get_experiment_description.

docs/user_guide/index.html, mkdocs/docs/user_guide.md
Fixing some typos in user guide
=> Fix typos in user_guide

README.md, requirements.txt, setup.py
Hello, I updated the setup.py and requirements.txt files to include scikit-image version number. I ran into this issue while setting up and I thought to send a PR for this.
=> Minor text changes

ludwig/utils/data_utils.py
=> Fix incorrect logging in read_csv

ludwig/data/preprocessing.py
Test plan:
python -m ludwig.predict --only_predictions --data_csv ~/Documents/ludwig/datasets/ludwig-prediction-example/test.csv --model_path results/experiment_run_127/model
=> Fix predict for images

docs/user_guide/index.html, mkdocs/docs/user_guide.md
`ludwig visualize` doc update for `-r` argument: should be `-d` instead and point at csv file.
=> ludwig visualize -r argument doc update

ludwig/cli.py, ludwig/contrib.py, ludwig/contribs/__init__.py, ludwig/contribs/comet.py
This PR:
* Provides faster access to contrib instances
* Passes args to sub-command hooks
* Restructures code layout in contribs
=> Fast access to Contrib instance; restructure contribs

ludwig/cli.py, tests/integration_tests/test_experiment.py
1. Improves testing time by reducing the size of the data used
2. Improves startup time by avoiding a blanket import in cli.py
all tests pass.
=> Improves testing time and startup time

tests/integration_tests/test_experiment.py
Speeds up integration tests
1.  Number of datapoints is reduced to 25 (further reductions didn't show much value) 
2. Some unncessary tests are reduced - tests which were using features/encoders that are already tested
3. Image sizes are reduced to 8x8 from 10x10
Testing time drops by ~20% overall on my laptop. All tests pass (repeated trials)
=> Speedup integration tests

ludwig/api.py
Adds data_dict to the train method in api.py
=> Adds data_dict to the train method in api.py

.deepsource.toml, ludwig/contrib.py, ludwig/utils/defaults.py, ludwig/utils/image_utils.py, tests/integration_tests/test_api.py, tests/integration_tests/test_experiment.py, tests/integration_tests/utils.py
I forked and ran analysis on this repository and found some interesting issues in the code. You can take a look at the results [here](https://deepsource.io/gh/jaipradeesh/ludwig/issues/).
I've gone ahead and fixed a few issues 😁.
To continue running analysis on every PR, just follow these simple steps:
1. **Merge this PR.** I've added a customised `.deepsource.toml` for this repo which you can use directly.
2. **Sign up on DeepSource** and grant access to this repository [here](https://deepsource.io/signup/).
3. **Activate analysis** [here](http://deepsource.io/gh/uber/ludwig).
You can take a look at the [Getting Started docs](https://deepsource.io/docs/guides/quickstart.html) for the steps.
Signed-off-by: Jai <jai@deepsource.io>
=> Fix issues to improve code quality

ludwig/data/preprocessing.py
fixes a minor bug in pre-processing. we were using data_csv instead of data_train_csv
=> Fixes a bug in preprocessing

tests/fixtures/filenames.py, tests/integration_tests/test_experiment.py
And some refactoring for one of the test utils
=> Fixes one of the tests, which is saving .hdf5, .json files to disk.

docs/index.html, mkdocs/custom/landing.html
Fixed broken footer link to 'Getting Started'.
=> Fix footer link to Getting Started in index.html

mkdocs/docs/examples.md
witdth and height should be under preprocessing
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run …
=> Update one-shot siamese network example

mkdocs/docs/user_guide.md
encoder description cnn_rnn gives error
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run …
=> Changed encoder description cnn_rnn to cnnrnn

mkdocs/docs/user_guide.md
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run `mkdocs/code_docs_autogen.py`, which will create …
=> Added audio features documentation

mkdocs/docs/examples.md
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run `mkdocs/code_docs_autogen.py`, which will create …
=> Added example for audio features

mkdocs/docs/getting_started.md
May also want to make these changes to README.md at top level.
=> Typo, Linus -> Linux

README.md
=> fix(doc): fix readme images path

mkdocs/docs/examples.md
replaced speaker verification example with easily reproducible example for spoken digit speech recognition. 
Should get around ~96% accuracy on test set.
=> Added concrete example for fbank / audio

ludwig/serve.py, tests/integration_tests/test_server.py
Now we can perform server healthchecks by sending `GET` requests to its root path `/`. We also test that a get request to the `/` path returns status code 200.
Addresses #480 .
=> Healthchecking server

mkdocs/docs/user_guide.md
=> Fixed spelling mistake

mkdocs/docs/user_guide.md
=> Fixed horovodrun commands to remove extra mpirun args

ludwig/api.py, ludwig/collect.py, ludwig/data/dataset_synthesyzer.py, ludwig/experiment.py, ludwig/predict.py, ludwig/train.py, ludwig/utils/misc.py
Improving skips by adding two new skip_save_training_description and skip_save_training_statistics. Also now full_training will not create a directory if all skips are true.
This solves #491.
=> Improving skip parameters

Dockerfile
Fixes Issue #541
The change updated the Dockerfile build instructions to reference the recently create `requirements_text.txt` file when install python dependencies for ludwig. 
This the docker build log file with the change:
[successful_docker_build_fix_spacy.txt](https://github.com/uber/ludwig/files/3746633/successful_docker_build_fix_spacy.txt)
=> fix: docker build error for missing spacy module

mkdocs/docs/examples.md
Fixes small spelling mistake in the markdown for the documentation.
=> Fix spelling for "Analytics".

ludwig/data/preprocessing.py
Fix typo in preprocessing.py 
optoin should be option
=> Fix typo in preprocessing.py

ludwig/experiment.py
Fix all of typos in experiment.py
=> Fix typo in experiment.py

Dockerfile
Fix #552 
Added install for git to the Dockerfile.
Successfully build docker image.  Here is log file from the build:
```
Jim-MacBook-Pro:jim ludwig[509]$ docker build -t ludwig_test .
[+] Building 678.0s (8/8) FINISHED
=> [internal] load build definition from Dockerfile                                                                                   0.1s
=> => transferring dockerfile: 453B                                                                                                   0.0s
=> [internal] load .dockerignore                                                                                                      0.0s
=> => transferring context: 2B                                                                                                        0.0s
=> [internal] load …
```
=> fix: Issue #552 missing git error in docker build

mkdocs/docs/developer_guide.md, mkdocs/docs/user_guide.md
* Developer guide changes for howto add integration
* User guide changes for existing integrations, link to external sites
=> Documentation for contributed integrations

examples/README.md, examples/mnist/advance_model_training.py, examples/mnist/simple_model_training.py, examples/titanic/multiple_model_training.py, examples/titanic/simple_model_training.py
* Updated documentation
* Clean-up code to comply with PEP8 guidelines for exception handling
=> Code clean-up for API examples

mkdocs/docs/examples.md
Change the preprocessing syntax in Siamese network example
Changing second image to the same as the first image has
=> Change preprocessing at Siamese example

mkdocs/docs/developer_guide.md
I missed an injection point added in #514
=> Added docs for missing injection point

ludwig/models/model.py, ludwig/models/outputs.py
This implements a fix to issue #328 
I know it's ugly and might be prettier, but if checks pass it's a valid solution that can be improved upon.
I already tested the cases where it happened to me, and it's not doing that anymore. Hope it passes CI tests.
=> Fix CLI output table column ordering

.travis.yml, ludwig/models/combiners.py, ludwig/models/model.py, ludwig/models/modules/convolutional_modules.py, ludwig/models/modules/recurrent_modules.py
@w4nderlust   This is a test of sending results of my work.  Initially I tried pushing my changes directly to `uber/ludwig` but it failed because I did not have write permission to `uber/ludwig`.  
I'm now trying to submit my changes through a PR for branch `tf2_porting` branch in my fork`jimthompson5802/ludwig`.  The target for this PR is `uber/ludwig' branch 'tf2_porting`.  If this works, then I can just add commits to this PR.
The Docker image I use for my development environment is built with the updated `requirements.txt` on the `tf2_porting` branch, which contains 
```
tensorflow==2.1
tensorflow-addons
```
With this initial set of commits, `train` completes and some, not all, of the data are saved for TensorBoard.  For my test, I'm using the Titanic Survivor example.  Here is the …
=> Tf2 porting

README.md
[docs/enhancement} - uber/ludwig - README.md
=> [docs/enhancement} - uber/ludwig - README.md

ludwig/models/model.py
https://github.com/uber/ludwig/issues/650
=> fix(model/save_savedmodel): don’t override output

mkdocs/docs/user_guide.md
Fix typos in sequence decoder docs
=> Fix typo in docs

ludwig/models/modules/loss_modules.py
I've removed redundant code in loss_module and added them to a new function set_parameters.
Signed-off-by: Kushal Prakash <k.prakash@student.tudelft.nl>
=> Refactored loss_module file

ludwig/features/image_feature.py, ludwig/models/modules/convolutional_modules.py, ludwig/models/modules/image_encoders.py
As title. Some details are missing - will address in future PRs, left a few TODOs.
Tested end-to-end training with MNIST dataset.
=> Refactor Stacked2DCNN to work with tf 2.0

ludwig/models/modules/convolutional_modules.py
Split out ConvLayer2D from the stack.
=> ConvLayer2D

ludwig/models/modules/fully_connected_modules.py
=> Add FCLayer and refactor FCStack to use it

ludwig/models/modules/sequence_decoders.py
This should finish off the Tagger decoder
* todo for feedforward attention
* add time series support
* add regularizer specification
=> TF2 porting: tagger decoder cleanup

ludwig/utils/hyperopt_utils.py, tests/integration_tests/test_hyperopt.py, tests/ludwig/utils/test_hyperopt_utils.py
=> Add tests for Hyperopt Strategies & Executors

ludwig/models/modules/convolutional_modules.py, ludwig/models/modules/image_encoders.py
=> ResNet TF2 porting

ludwig/cli.py, ludwig/constants.py, ludwig/hyperopt.py, ludwig/utils/hyperopt_utils.py, ludwig/utils/misc.py, mkdocs/docs/developer_guide.md, mkdocs/docs/user_guide.md
=> Add Hyperopt to User & Developer Guide

ludwig/features/vector_feature.py, ludwig/models/modules/generic_decoders.py
Porting the vector feature to TF2
=> TF2 porting: vector feature

tests/ludwig/models/modules/test_encoder.py
update EmbedEncoder to SequenceEmbedEncoder in tests
pytest failing without this
=> update EmbedEncoder to SequenceEmbedEncoder in tests

ludwig/features/bag_feature.py, ludwig/models/modules/bag_encoders.py, ludwig/models/modules/embedding_modules.py
=> Bag input feature tf2 porting

ludwig/api.py, ludwig/models/model.py, tests/integration_tests/test_visualization.py
While working on fixing some unit tests, I noticed an inconsistency in how objects are returned from `model.predict()` and `model.batch_evaluation()` methods when compared to how calling modules are coded.  A recent change I implemented returns a single object representing predicted values or a tuple containing two objects representing predictive values and test metrics.  The type of return is determined by settings of `only_predictions` and `evaluate_performance` parameters.  
I noticed that higher level calling modules assumed a return of a tuple with two objects.  Because of the prior change, unit tests that worked before now fail.
This PR reworks the return signatures for both `model.batch_evaluation()` and `model.predict()` to always return a tuple.  If the test metric object is not …
=> TF2 porting: Make Ludwig prediction related apis return signature consistent & fix visualization unit test

ludwig/features/vector_feature.py, ludwig/models/modules/sequence_decoders.py
Resolved errors in 
* `test_experiment.py::test_experiment_mutliple_seq_seq` 
* `test_experiment.py::test_visual_quesstion_answering` 
Resolution to these tests is pending:
* `test_experiment.py::test_experiment_vector_feature_1`
* `test_experiment.py::test_experiment_vector_feature_2`
Current pytest log
```
pytest  /opt/project/tests/integration_tests/test_experiment.py
platform linux -- Python 3.6.9, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
plugins: forked-1.2.0, xdist-1.33.0, pycharm-0.6.0, typeguard-2.9.1
collected 351 items
../../../tests/integration_tests/test_experiment.py …
```
=> TF2 porting:  Fix test_experiment unit tests

.travis.yml, ludwig/api.py, ludwig/models/modules/generic_decoders.py, tests/integration_tests/test_model_save_and_load.py, tests/ludwig/utils/scripts/run_horovod_utils.py, tests/ludwig/utils/test_horovod_utils.py
- Fixed model saving API
- Fixed set features
- Run Horovod utils tests in separate process to workaround dill / cloudpickle interaction
=> Added additional tests for explicit model save and load

ludwig/constants.py, ludwig/train.py, ludwig/utils/hyperopt_utils.py, ludwig/utils/tf_utils.py, tests/integration_tests/test_hyperopt.py, tests/ludwig/utils/test_hyperopt_utils.py
Update Hyperopt Tests for TF2 Porting & PySOTStrategy.
=> WIP: Update Hyperopt Tests for TF2 Porting & PySOTStrategy

requirements_hyperopt.txt
See: https://github.com/pypa/setuptools/issues/2048#issuecomment-605429013
=> Fix bayesmark direct url to use PEP 508 synatax

ludwig/hyperopt/execution.py
Not closing and joining the pool at the end of hyperopt led to the next test starting while the previous test still had running processes, which resulted in the second test not having any available GPU resources / hanging.
=> Close and join the parallel executor pool when hyperopt finishes

ludwig/decoders/sequence_decoders.py, requirements.txt
This PR relies on https://github.com/tensorflow/addons/pull/2070.
=> Updated beam search to use dynamic_decode

ludwig/predict.py
=> fix: 'NoneType' object is not subscriptable

ludwig/constants.py, ludwig/data/preprocessing.py
=> feat: drop_row missing strategy

ludwig/contribs/comet.py
https://github.com/uber/ludwig/blob/master/ludwig/models/trainer.py#L421
fix renaming in PR
=> fix(contribs/comet): there're only *_metrics in progress tracker, not *_stats

ludwig/models/trainer.py
Fixes `test_hyperopt.py` failures introduced in https://github.com/uber/ludwig/commit/ccb700e93ff2a155d9a85a616f0e84b44e0ffdc5.
=> Fixed issue with accessing dict as a list

ludwig/encoders/text_encoders.py, ludwig/features/bag_feature.py, ludwig/features/category_feature.py, ludwig/features/sequence_feature.py, ludwig/features/set_feature.py, ludwig/features/text_feature.py, ludwig/models/ecd.py, ludwig/utils/strings_utils.py
First pass at a complete integration of HF encoders. Supports integration of 16 encoders.
=> HF Transformers Integration

ludwig/models/trainer.py
support enabling TF2 Eager Execution mode with the Ludwig `--debug` flag.
=> TF2 porting: enable eager execution mode with --debug flag

tests/integration_tests/test_savedmodel.py
=> Load LudwigModel in test_savedmodel before creating saved model

ludwig/models/new_ludwig_model.py, ludwig/models/predictor.py, ludwig/models/trainer.py, tests/integration_tests/test_collect.py
- Save model definition inside `NewLudwigModel.train` as `Trainer` lacks awareness of model definition.
- Added helper methods to load model from model definition and check model initialization.
=> Fixed collect_weights and collect_activations

ludwig/contribs/wandb.py, ludwig/experiment.py, ludwig/features/image_feature.py, ludwig/models/new_ludwig_model.py, tests/integration_tests/scripts/run_train_comet.py, tests/integration_tests/scripts/run_train_wandb.py
- Fixed `experiment_cli` to return experiment directory from `NewLudwigModel`.
- Fixed usage of `dataset` with image features.
- Fixed comparison to Pandas DF in `evaluate`.
=> Fixed comet and wandb tests

ludwig/api.py, ludwig/experiment.py, tests/integration_tests/test_kfold_cv.py
=> Removed api.kfold_cross_validate as the function exists in experiment.py

ludwig/api.py, ludwig/features/audio_feature.py, ludwig/features/set_feature.py, ludwig/features/vector_feature.py, ludwig/models/ecd.py, ludwig/serve.py, ludwig/utils/neuropod_utils.py, tests/integration_tests/test_model_save_and_load.py, tests/integration_tests/test_neuropod.py, tests/integration_tests/test_reducers.py, tests/integration_tests/test_savedmodel.py, tests/integration_tests/test_server.py
- Fixed `test_neuropod`
- Fixed `test_reducers`
- Fixed `test_saved_model`
- Fixed `test_server`
- Fixed `test_model_save_and_load`
=> Fixed inference related tests

ludwig/data/preprocessing.py, tests/integration_tests/test_experiment.py
This PR adds the unit test for dictionary dataset with images
=> TF2: update unit test to add image dictionary dataset

Dockerfile, Dockerfile_dev
=> Updated Dockerfiles for TensorFlow 2

ludwig/utils/strings_utils.py
Getting this error for `bool` types:
```
AttributeError: 'bool' object has no attribute 'lower’
```
This is the fix
=> fix(strings_utils): bool 2 str

ludwig/models/trainer.py
=> Disable running eagerly by default

ludwig/hyperopt/execution.py
Change import of constants
unit test successfully runs locally
```
platform linux -- Python 3.6.9, pytest-6.0.2, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
plugins: forked-1.3.0, pycharm-0.7.0, xdist-2.1.0, typeguard-2.9.1
collected 10 items
../../tests/integration_tests/test_hyperopt.py::test_hyperopt_executor[executor0-sampler0] PASSED                                    [ 10%]
../../tests/integration_tests/test_hyperopt.py::test_hyperopt_executor[executor0-sampler1] PASSED                                    [ 20%]
../../tests/integration_tests/test_hyperopt.py::test_hyperopt_executor[executor0-sampler2] PASSED                                    [ 30%]
../../tests/integration_tests/test_hyperopt.py::test_hyperopt_executor[executor1-sampler0] …
```
=> TF2: fix hyperopt unit

ludwig/api.py, ludwig/experiment.py, ludwig/hyperopt/run.py, ludwig/hyperopt/utils.py, ludwig/hyperopt_cli.py, ludwig/train.py, ludwig/utils/misc_utils.py, tests/integration_tests/test_hyperopt.py, tests/integration_tests/test_kfold_cv.py, tests/integration_tests/test_validation_metrics.py
Modified LudwigModel init signature to use model_definition for both dict and file
=> Refactoring: single model_definition in LudwigModel init signature

ludwig/api.py, ludwig/experiment.py, ludwig/hyperopt/execution.py, ludwig/models/ecd.py, ludwig/train.py, tests/integration_tests/test_api.py, tests/integration_tests/test_experiment.py
=> Added back tf.random.set_seed and added determinism test

ludwig/visualize.py, tests/conftest.py, tests/integration_tests/test_hyperopt.py, tests/integration_tests/test_visualization_api.py
Added vis api for `hyperopt_report()` and related unit test
Added unit test for `hyperopt.run.hyperopt()`
=> TF2: add hyperopt_report vis api and related unit tests

ludwig/api.py, ludwig/data/preprocessing.py, ludwig/evaluate.py, ludwig/predict.py, tests/integration_tests/test_savedmodel.py
Adding back split parameter in predict and evaluate (both functions and cli)
=> Adding back split parameter

ludwig/visualize.py
start of visualization cli docstring review
=> TF2: docstring review for visualization cli

ludwig/collect.py, ludwig/experiment.py
refactor: collect_activations to add missing split parameter
doc: updated docstring experiment and collect_activations for missing parameter
=> TF2: add missing parameters for experiment and collect_activations

ludwig/utils/strings_utils.py
fixed HF tokenizer truncation bug
=> added truncation to HF tokenizer

ludwig/datasets/fever/__init__.py, ludwig/datasets/fever/config.yaml, ludwig/datasets/goemotions/__init__.py, ludwig/datasets/goemotions/config.yaml, ludwig/datasets/mixins/download.py, ludwig/datasets/mixins/process.py, ludwig/datasets/ohsumed/config.yaml, ludwig/datasets/reuters/config.yaml, ludwig/utils/strings_utils.py, tests/ludwig/datasets/test_datasets.py
added Fever Data and Go Emotions and new mixins to support multi-file downloads.
=> added fever and goemotions and new mixins

ludwig/decoders/sequence_decoders.py, ludwig/features/bag_feature.py, ludwig/features/sequence_feature.py, ludwig/features/set_feature.py, ludwig/features/vector_feature.py, tests/integration_tests/test_savedmodel.py
This PR contains an improvement for the SavedModel tests that reveals a problem with set and other data types.
When solved, will fix #960
=> Fix SavedModel for multiple data types

ludwig/data/preprocessing.py, ludwig/features/set_feature.py, ludwig/modules/loss_modules.py, ludwig/modules/metric_modules.py, tests/integration_tests/test_experiment.py
=> Fixed losses ported from tf1

ludwig/data/preprocessing.py
=> Fix logger typo

ludwig/data/preprocessing.py, tests/integration_tests/test_model_training_options.py
fix: specification of dataset name for cache checksum
* Add cache checksum unit test
* fix internal error for preprocessing with checksum calculation
=> Add unit test for cache checksum function

ludwig/constants.py, ludwig/data/preprocessing.py, ludwig/utils/data_utils.py, ludwig/utils/misc_utils.py, tests/integration_tests/test_model_training_options.py
Adds a checksum in the training set metadata to check if the hdf5 cache is still valid
=> Cache checksum

ludwig/api.py, ludwig/train.py, tests/integration_tests/test_cli.py
=> Fixed usage of model_load_path with Horovod

ludwig/datasets/sst2/sst_utils.py, ludwig/datasets/sst5/__init__.py
added some comments to sst dataset
=> added comments to sst2

examples/hyperopt/README.md
capabililies -> capabilities
uing -> using
=> Fix typo in examples/hyperopt/README.md

ludwig/visualize.py
Update parameter abbreviation for `output_feature_name` to match recent visualization document update
related to documentation update PR https://github.com/ludwig-ai/ludwig-docs/pull/20
=> update parameter alias to match visualization cli documentation updates

requirements.txt
See: https://github.com/pandas-dev/pandas/issues/38367
=> Pin pandas<1.1.5 until pivot table issue is resolved

tests/integration_tests/test_neuropod.py
In this pull request, I propose to change the use of lambda functions in `test_neuropod.py` by list comprehension to gain a little more readability.
=> Substitute the use of lambda functions by list comprehension

requirements.txt
=> Pin xlrd<2 to unblock CI

.travis.yml, requirements.txt
=> Bump TensorFlow and tfa-nightly for 2.4.0 release

ludwig/api.py, ludwig/decoders/generic_decoders.py, ludwig/models/trainer.py, ludwig/modules/loss_modules.py, ludwig/modules/recurrent_modules.py, ludwig/utils/data_utils.py, ludwig/utils/html_utils.py, ludwig/utils/neuropod_utils.py, ludwig/utils/visualization_utils.py, tests/conftest.py, tests/integration_tests/test_sequence_features.py
This pull request aims to refactor some `if` statements that can be joined and delete variables that were created but not used.
=> Refactor if statements and unused variables

ludwig/hyperopt/sampling.py, tests/integration_tests/test_hyperopt.py
This PR updates the RandomSampler and PySOTSampler to handle categorical values of type list. Also updates the hyperopt tests to check this functionality
=> updating hyperopt sampling functions to handle list values

ludwig/datasets/agnews/__init__.py, ludwig/datasets/agnews/config.yaml, ludwig/datasets/irony/__init__.py, ludwig/datasets/irony/config.yaml
This PR adds both the [Reddit Irony Dataset](https://www.aclweb.org/anthology/P14-2084/) and the AGNews Corpus Dataset
=> Irony dataset + AGNews Dataset

ludwig/encoders/text_encoders.py, requirements_text.txt, tests/integration_tests/utils.py
This PR makes the necessary changes to support the HuggingFace Transformers 4.2.0 release. Note: the HF flaubert and xlnet models are not compatible with TF graphs and are thus not included in this PR.  The following issues have been raised to addresses the aforementioned issues: [xlnet issue ](https://github.com/huggingface/transformers/issues/9614) and [flaubert issue](https://github.com/huggingface/transformers/issues/9641)
=> Transformers 4.2.1 Integration

ludwig/datasets/sst2/config.yaml, ludwig/datasets/sst2/sst_utils.py, ludwig/datasets/sst5/config.yaml
updating broken SST2/SST5 dataset links
=> Update SST2 Dataset Link

ludwig/serve.py
Example of allowing any origins:
```
ludwig serve -m ~/data/titanic/model2 -p 8002 --allowed_origins "*"
```
Example of allowing specific origins:
```
ludwig serve -m ~/data/titanic/model2 -p 8002 --allowed_origins http://localhost http://localhost:8000
```
=> Added allowed_origins to serving to support cross-origin requests

ludwig/datasets/sst2/__init__.py, ludwig/datasets/sst2/sst_utils.py, ludwig/datasets/sst3/__init__.py, ludwig/datasets/sst3/config.yaml, ludwig/datasets/sst5/__init__.py
This PR dds the subtrees option to SST datasets
=> Added functionality to obtain subtrees in the SST dataset

ludwig/combiners/combiners.py, tests/integration_tests/test_combiners.py
=> Adding comparator combiner

ludwig/data/preprocessing.py
This PR is my fix to issue #1132
=> check dask dataframe at preprocessing

ludwig/datasets/ames_housing/__init__.py, ludwig/datasets/electricity/__init__.py, ludwig/datasets/electricity/config.yaml, ludwig/datasets/flickr8k/__init__.py, ludwig/datasets/irony/__init__.py, ludwig/datasets/mixins/kaggle.py, ludwig/datasets/sst2/__init__.py, ludwig/datasets/temperature/__init__.py, ludwig/datasets/temperature/config.yaml, ludwig/datasets/yosemite/__init__.py, ludwig/datasets/yosemite/config.yaml
Adds three time series datasets (electricity, temperature, yosemite). Also some minor cleanup in the datasets/ folder.
=> Add timeseries datasets

ludwig/datasets/adult_census_income/__init__.py, ludwig/datasets/adult_census_income/config.yaml, ludwig/datasets/forest_cover/__init__.py, ludwig/datasets/forest_cover/config.yaml, ludwig/datasets/rossmann_store_sales/__init__.py, ludwig/datasets/rossmann_store_sales/config.yaml, ludwig/datasets/titanic/__init__.py
Adds Forest Cover Type, Adult Census Income and Rossmann Store Sales datasets
=> Forest Cover Type, Adult Census Income and Rossmann Store Sales datasets

docker/README.md
Added `README.md` for the docker images
=> doc: initial docker readme doc

.github/workflows/pytest.yml
See https://github.com/tensorflow/tensorflow/issues/49467.
=> Pin tensorflow-nightly for horovod compatibility

.github/workflows/pytest.yml
Fixed by https://github.com/horovod/horovod/issues/2924.
=> Unpin tf-nightly

ludwig/constants.py, ludwig/data/cache/manager.py, ludwig/data/dataset/pandas.py, ludwig/data/dataset/parquet.py, ludwig/data/preprocessing.py, tests/integration_tests/test_cache_manager.py
=> Fixed CacheManager to correctly handle test_set and validation_set

.github/workflows/docker.yml, .github/workflows/pytest.yml, requirements.txt
This PR introduces a self-hosted Amazon EC2 runner to build large Docker images that don't fit in disk within the provided GitHub runners.
=> Updated tensorflow-addons and CI system

ludwig/models/trainer.py
=> Made should_shuffle configurable in Trainer

ludwig/features/numerical_feature.py, ludwig/modules/embedding_modules.py, ludwig/modules/normalization_modules.py
Fixed Keras imports that were breaking regularization for embedding modules
=> Fixed Keras imports

requirements_ray.txt
See: https://github.com/ray-project/ray/issues/16692
=> Pin tensorboardX<2.3

ludwig/datasets/bnp_claims_management/__init__.py, ludwig/datasets/bnp_claims_management/config.yaml, ludwig/datasets/mercedes_benz_greener/__init__.py, ludwig/datasets/mercedes_benz_greener/config.yaml, ludwig/datasets/santander_value_prediction/__init__.py, ludwig/datasets/santander_value_prediction/config.yaml, ludwig/datasets/synthetic_fraud/__init__.py, ludwig/datasets/synthetic_fraud/config.yaml
=> Add 4 tabular datasets

ludwig/automl/base_config.py, ludwig/automl/data_source.py, ludwig/automl/defaults/concat_config.yaml, ludwig/automl/defaults/tabnet_config.yaml, ludwig/automl/defaults/transformer_config.yaml, ludwig/automl/utils.py, ludwig/features/image_feature.py, ludwig/utils/image_utils.py
Sets the `infer_image_dimensions` flag to `True` (default is False) for autoML
=> Add image dimension inference to automl

requirements.txt, requirements_audio.txt, requirements_horovod.txt, requirements_image.txt
To support the TF to Torch port.
This adds PyTorch dependencies to Ludwig dependencies requirement*.txt file
=> Update Ludwig dependency specifications for pytorch support

ludwig/automl/base_config.py, ludwig/automl/utils.py, tests/ludwig/automl/test_base_config.py
=> Fix excluded field detection

ludwig/combiners/combiners.py
Fixes this issue in `combiner.py`
=> fix: TypeError in calculating combiner output dimension

ludwig/modules/fully_connected_modules.py
imports for BatchNorm1d and BatchNorm2d were missing.
=> fix: add missing imports

ludwig/encoders/image_encoders.py, ludwig/features/image_feature.py, ludwig/modules/convolutional_modules.py, ludwig/modules/mlp_mixer_modules.py, ludwig/utils/image_utils.py, ludwig/utils/torch_utils.py
WIP PR for migrating image features from TF to PyTorch
=> Torch image features

ludwig/automl/defaults/concat_config.yaml, ludwig/automl/defaults/tabnet_config.yaml, ludwig/automl/defaults/transformer_config.yaml
This PR updates the default model config parameter ranges based on learned heuristics. It also removes any setting of combiner params such that initial params are set to the default settings.
=> [automl] update model config parameter ranges

requirements.txt
This is until Ludwig is refactored to be compatible.
=> Pin sklearn < 1.0

ludwig/encoders/sequence_encoders.py, ludwig/features/audio_feature.py, ludwig/modules/attention_modules.py, tests/integration_tests/test_audio_feature.py, tests/integration_tests/test_sequence_encoders.py
- Port Audio Input Feature to Torch
- Add unit test for audio input feature
=> Tf to torch audio feature

ludwig/encoders/date_encoders.py, ludwig/features/date_feature.py, ludwig/modules/embedding_modules.py, ludwig/modules/fully_connected_modules.py, ludwig/utils/torch_utils.py, tests/ludwig/encoders/test_date_encoders.py, tests/ludwig/features/test_date_feature.py
- Added unit tests for DateEmbed and DateWave in test_date_encoders.
- Added unit tests in test_date_features.
=> Port date_feature and date_encoders to PyTorch

ludwig/encoders/text_encoders.py, tests/ludwig/encoders/test_text_encoders.py
For BERTEncoder:
- Add unit tests
- Allow using an untrained model.
=> Added tests and optional pretraining for text features

.github/workflows/pytest.yml, .github/workflows/test-results.yml
This makes #1414 work for PRs from fork repos as well. Unfortunately, this can only be tested once merged to master.
=> Publish test results for fork repos as well

ludwig/modules/metric_modules.py, requirements.txt
Bug fix in `tests/integration_tests/test_model_save_and_load.py::test_model_save_reload_api`
=> [torch] Bug fixes for integration tests

ludwig/combiners/combiners.py, ludwig/encoders/sequence_encoders.py, ludwig/modules/convolutional_modules.py, tests/integration_tests/test_experiment.py
This requires fixing an output_shape implementation in sequence_encoders.
=> Clean up sequence concat combiner test_experiment unit tests.

ludwig/encoders/image_encoders.py, tests/ludwig/modules/test_encoder.py
Note `test_sequence_encoders` still failing for `StackedCNNRNN`.
cc @ShreyaR
=> Fixed test_encoders

.github/workflows/pytest.yml
=> Remove tf-to-torch test

tests/integration_tests/test_contrib_wandb.py
- This PR establishes a temp directory for wandb
N/A
=> Add temp directory to W&B tests

ludwig/visualize.py
The code replaces the typo `confision` by `confusion` :)
=> Fix little typo

setup.py
Update version identifier for PyTorch porting.
=> Doc: Update version id for PyTorch migration

ludwig/globals.py
Update global LUDWIG_VERSION to reflect PyTorch migration work
=> doc: update global version to pytorch development identifier

ludwig/automl/base_config.py, ludwig/automl/data_source.py, ludwig/automl/utils.py, ludwig/utils/strings_utils.py, tests/ludwig/automl/test_base_config.py, tests/ludwig/utils/test_strings_utils.py
Co-authored-by: Anne Holler <anne@vmware.com>
=> Update Ludwig AutoML Feature Type Selection (#1485)

requirements_serve.txt
=> Remove unused pydantic dependency

ludwig/utils/eval_utils.py, ludwig/utils/strings_utils.py, tests/ludwig/utils/test_strings_utils.py
=> Add 1.0 and 0.0 as bool-like strings and pass kwargs to roc eval_utils.

ludwig/utils/type_utils.py
Herewith the previous error given by the code during training:
File "\ludwig\utils\type_utils.py", line 10, in <module>
if dd is not None:
NameError: name 'dd' is not defined
=> Fix exception in file type_utils.py

ludwig/automl/automl.py, ludwig/automl/base_config.py, ludwig/automl/defaults/base_automl_config.yaml, ludwig/automl/defaults/combiner/concat_config.yaml, ludwig/automl/defaults/combiner/tabnet_config.yaml, ludwig/automl/defaults/combiner/transformer_config.yaml, ludwig/automl/defaults/text/bert_config.yaml, ludwig/hyperopt/execution.py
Co-authored-by: Anne Holler <anne@vmware.com>
=> Add experiment heuristics to automl module (variant of Avanika PR 1362) (#1507)

CONTRIBUTING.md
Roughly modeled off of huggingface's contributing guidelines: https://github.com/huggingface/datasets/blob/master/CONTRIBUTING.md
=> Add basic contributing guidelines, with a pointer to the developer guide.

ludwig/api.py, ludwig/callbacks.py, ludwig/contribs/__init__.py, ludwig/contribs/whylogs/__init__.py, ludwig/data/preprocessing.py, requirements.txt, requirements_test.txt, tests/integration_tests/test_whylogs.py, tests/integration_tests/utils.py
=> Added whylogs integration and connected to metadata preprocessing

ludwig/automl/automl.py
This document outlines the reasons for making this change:
https://docs.google.com/document/d/130tZ_RN8fyqoIS09njKkQZOxUgqd08Qjyf5OKieJXGg/edit#
=> Update AutoML tabular model type choice to remove heuristic for concat

requirements.txt, requirements_image.txt
https://github.com/pytorch/pytorch/issues/65473
cc @carlogrisetti
=> Pin torch==1.9.1 and torchvision==0.10.1 on Windows

ludwig/modules/attention_modules.py, ludwig/modules/embedding_modules.py, ludwig/utils/misc_utils.py
Fixes tests in:
- `tests/integration_tests/test_visualization.py` -- some tests are fixed using the changes introduced in @jeffreyftang's PR https://github.com/ludwig-ai/ludwig/pull/1533. Other tests are fixed with the changes to `embedding_modules`.
=> [torch] Fix GPU tests for test_visualizations

tests/integration_tests/test_regularizers.py
2 input/output combos are still breaking. Investigating them.
=> Fixed regularizers tests except 2 input/output combos

ludwig/backend/ray.py, ludwig/data/dataset/ray.py, ludwig/hyperopt/execution.py, ludwig/models/trainer.py, requirements_ray.txt
Also fixes API compatibility for Ray 1.9.
=> Remove TensorDType conversion for all scalar types

requirements.txt
https://github.com/httplib2/httplib2/blob/master/CHANGELOG
```
File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/backend/base.py", line 22, in <module>
from ludwig.data.dataframe.pandas import PANDAS
File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/data/dataframe/pandas.py", line 21, in <module>
import tensorflow as tf
File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
from tensorflow.python.tools import module_util as _module_util
File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 48, in <module>
from tensorflow.python import keras
File "/home/ray/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
from tensorflow.python.keras import …
```
=> Pin httplib2=0.20.3

ludwig/encoders/date_encoders.py, ludwig/utils/torch_utils.py, tests/ludwig/encoders/test_bag_encoders.py, tests/ludwig/encoders/test_date_encoders.py, tests/ludwig/encoders/test_set_encoders.py, tests/ludwig/features/test_sequence_features.py
Fixed tests in:
- tests/integration_tests/test_experiment.py
- tests/ludwig/encoders/test_set_encoders.py
- tests/ludwig/encoders/test_date_encoders.py
- tests/ludwig/encoders/test_bag_encoders.py
=> [torch] Fixed tests in test_experiment.py

ludwig/combiners/combiners.py, ludwig/data/preprocessing.py, ludwig/utils/strings_utils.py, tests/ludwig/utils/test_strings_utils.py
This will be super useful to get the first sequence decoder PR diffs to have as least noise as possible.
=> Formatting for other sequence-related files.

tests/ludwig/encoders/test_category_encoders.py
Adds unit tests for:
- CategoricalEmbedEncoder
- CategoricalSparseEncoder
=> Adds unit test for categorical encoders

tests/ludwig/features/test_category_feature.py, tests/ludwig/features/test_set_feature.py
Adds a shape-based sanity check test for set input features. Fixes the wrong input feature type used in category feature test.
=> Add set feature shape test; fix typo in category feature shape test

ludwig/combiners/combiners.py, ludwig/modules/reduction_modules.py, ludwig/utils/torch_utils.py, tests/ludwig/modules/test_reduction_modules.py
- Also adds doc strings to torch_utils.py
- Adds SequenceReducer max_sequence_length parameter
- Adds SequenceReducer embedding_size optional parameter
=> Makes SequenceReducer a LudwigModule, adds reduction_modules_test.py

tests/ludwig/features/test_numerical_feature.py
-a simple unit test that utlizes the functionality around numerical_feature
- there is still work to be done in a new PR that will add normalization and zscore, still digging into that
- followed similar structure to other tests
Documented in tests
=> Test numerical feature

ludwig/encoders/sequence_encoders.py, ludwig/modules/reduction_modules.py, tests/ludwig/encoders/test_sequence_encoders.py
- Adds test_sequence_encoder
- Updates sequence encoders to support all reduce sequence modes (concat, attention...)
=> Adds sequence encoder test, updates sequence encoders to support all sequence reduce modes

tests/ludwig/encoders/test_category_encoders.py
Should fix test_category_encoders.py failing on GPU.
=> Place test tensors on device in test_category_encoders.py

ludwig/automl/automl.py, ludwig/automl/base_config.py, ludwig/automl/defaults/base_automl_config.yaml, requirements_hyperopt.txt
As titled.  Cross-port from tf-legacy.
=> Add random_seed to auto_train API to improve repeatability

ludwig/backend/ray.py, ludwig/features/base_feature.py, ludwig/models/predictor.py, ludwig/modules/metric_modules.py, ludwig/utils/horovod_utils.py
=> Fixed metrics aggregation for ray

ludwig/hyperopt/execution.py
Cross-port of https://github.com/ludwig-ai/ludwig/pull/1660
=> [cross-port from tf-legacy] Improve Ludwig resilience to Ray Tune issues

ludwig/models/predictor.py, ludwig/models/trainer.py
Context here: https://discuss.pytorch.org/t/out-of-memory-error-during-evaluation-but-training-works-fine/12274/11
Two changes incorporated from that threads:
- Use `torch.no_grad()` during eval to prevent gradient accumulation
- Pull training loop out into a separate function to prevent holding onto references
=> Added torch.no_grad() during eval to prevent OOM

ludwig/datasets/forest_cover/__init__.py, ludwig/datasets/higgs/__init__.py
With this change, I was able to get forest_cover and higgs to download into ludwig cache raw and be processed.
=> Handle downloading gzip files

.github/workflows/pytest.yml
See: https://github.com/machulav/ec2-github-runner/issues/91
=> Upgrade EC2 Runner to v2.3.0

examples/wmt15/config_large.yaml, examples/wmt15/config_small.yaml, examples/wmt15/train_nmt.py, ludwig/api.py, ludwig/data/preprocessing.py, ludwig/datasets/wmt15/__init__.py, ludwig/datasets/wmt15/config.yaml
Also, tweak print_boxed statements.
=> Add WMT15 (text -> text) as a kaggle dataset, with sample modeling code.

ludwig/datasets/connect4/__init__.py, ludwig/datasets/connect4/config.yaml, ludwig/datasets/naval/__init__.py, ludwig/datasets/naval/config.yaml, ludwig/datasets/numerai28pt6/__init__.py, ludwig/datasets/numerai28pt6/config.yaml, ludwig/datasets/protein/__init__.py, ludwig/datasets/protein/config.yaml
Tested with corresponding AutoML scripts added to
https://github.com/ludwig-ai/experiments/tree/main/automl/validation/...
=> Add support for additional tabular datasets to use to validate AutoML

ludwig/datasets/connect4/__init__.py, ludwig/datasets/connect4/config.yaml, ludwig/datasets/naval/__init__.py, ludwig/datasets/naval/config.yaml, ludwig/datasets/numerai28pt6/__init__.py, ludwig/datasets/numerai28pt6/config.yaml, ludwig/datasets/protein/__init__.py, ludwig/datasets/protein/config.yaml
Tested with corresponding AutoML scripts added to
https://github.com/ludwig-ai/experiments/tree/main/automl/validation/...
=> [cross-port from tf-legacy] Add support for additional tabular datasets to use to validate AutoML

ludwig/data/cache/manager.py, ludwig/models/trainer.py
Crossport from master. Recursively clearing the cache for master was addressed in https://github.com/ludwig-ai/ludwig/pull/1691.
=> [tf-legacy] Recursively clear the cache (for parquet files which can be directories).

docker/ludwig-ray-gpu/Dockerfile, requirements_dask.txt
See: https://github.com/dask/dask/issues/8636
=> Pin dask<2022.1.1 and fixed ray gpu docker's pytorch version

ludwig/modules/metric_modules.py, ludwig/utils/horovod_utils.py
Attached some screenshots below of the comparison with `torchmetrics`' AUROC metric, and the maximum delta is around 0.005.
=> Added faster AUROC

ludwig/automl/auto_tune_config.py, ludwig/automl/automl.py, ludwig/automl/utils.py, ludwig/models/ecd.py
Cross port of https://github.com/ludwig-ai/ludwig/pull/1759
=> [crossport from tf-legacy] Update tune_for_memory code

ludwig/api.py, ludwig/collect.py, ludwig/evaluate.py, ludwig/experiment.py, ludwig/hyperopt/run.py, ludwig/hyperopt_cli.py, ludwig/models/predictor.py, ludwig/models/trainer.py, ludwig/predict.py, ludwig/preprocess.py, ludwig/train.py, tests/ludwig/utils/test_schema.py
Also, fix minor syntax issues in `api.py` docstrings, which is preventing codegen from generating valid `md` in ludwig-docs.
=> Remove references to tfdbg, which doesn't exist in torch, and remaining references to keras.

ludwig/automl/utils.py, ludwig/hyperopt/execution.py
Set AutoML trial stop timeout:
Validated on agnews dataset
Catch/report/continue on any exception getting best checkpoint:
Saw this problem one time; wanted code to be more robust to it and to report info to help diagnosis.
=> Ray Tune: Set AutoML trial stop timeout; Catch/report/continue on any exception getting best checkpoint

ludwig/automl/automl.py
As titled.  Tested by https://github.com/ludwig-ai/experiments/tree/main/automl_image/validation/mnist
Cross-port of https://github.com/ludwig-ai/ludwig/pull/1773
=> Add basic path for image AutoML

ludwig/datasets/goemotions/__init__.py, ludwig/datasets/yelp_review_polarity/__init__.py
Found these problems when attempting to test AutoML on datasets used in LBT paper.
=> Fix problems loading text datasets

.gitignore
Also, clean up old docs in the gitignore.
=> Add ludwig_arm64/, .parquet, and .meta.json to gitignore.

README.md, README_KR.md, examples/mnist/simple_model_training.py, examples/titanic/simple_model_training.py, ludwig/features/image_feature.py, tests/integration_tests/test_visualization_api.py
=> Fixes links to ludwig docs in README.md and code

ludwig/datasets/base_dataset.py
Corresponds with change to ludwig-docs.
=> Add and expand docstrings in base_dataset.py

ludwig/cli.py, ludwig/datasets/mixins/load.py, ludwig/utils/torch_utils.py
Also adds some assorted docstrings.  No functional changes.
=> Adds `datasets` subcommand to usage message of Ludwig CLI

examples/kfold_cv/prepare_classification_data_set.py, examples/kfold_cv/regression_example.ipynb, ludwig/automl/base_config.py, ludwig/automl/utils.py, ludwig/combiners/combiners.py, ludwig/data/preprocessing.py, ludwig/datasets/kdd_dataset.py, ludwig/features/base_feature.py, ludwig/utils/eval_utils.py, ludwig/utils/strings_utils.py, ludwig/visualize.py, tests/ludwig/utils/test_defaults.py, tests/ludwig/utils/test_strings_utils.py
Also, rename functions/comments from "numerical" -> "number".
=> [AutoML] Handle integer casting for float-like numbers like "1.0" for number features

ludwig/api.py, ludwig/constants.py, ludwig/train.py, ludwig/utils/print_utils.py
Added a warning in CLI that asks you if you're sure you want to run ludwig train even though you have a hyperopt section present. The user is prompted with a [Y/n] decision in the command line. This change only affects cli since interacting with the api could interfere with Predibase operations.
=> Hyperopt warning

ludwig/datasets/bbcnews/__init__.py, ludwig/datasets/bbcnews/config.yaml, ludwig/datasets/imdb/__init__.py, ludwig/datasets/imdb/config.yaml
Tested by code added to the experiments repo.
=> Additional text classification datasets

ludwig/utils/strings_utils.py
Fix a misspelled word in `create_vocabulary`.
=> Fix minor typo

requirements.txt
=> Adds aiohttp to requirements.txt

examples/class_imbalance/README.md
Fixes typos in the example/class_imbalance/README.md
No open issues
Changes only in readme
=> Fix typos in class_imbalance example

ludwig/models/trainer.py
Fix for https://github.com/ludwig-ai/ludwig/issues/1871
Validated using manual repro of problem in debugger.
=> Move eval end callback trigger after model_weights save to ensure complete/consistent tune checkpoint 

ludwig/backend/base.py, ludwig/data/cache/manager.py, ludwig/data/dataset/ray.py, ludwig/data/preprocessing.py, ludwig/utils/data_utils.py, tests/integration_tests/test_cache_manager.py, tests/ludwig/utils/test_data_utils.py
Allows using custom filesystem credentials to read and write between the cache.
=> Added cache_credentials backend property

ludwig/backend/_ray112_compat.py, ludwig/backend/ray.py
https://github.com/ray-project/ray/pull/22564
=> Add fix for multi-node Horovod on Ray issue

ludwig/models/ecd.py
Tested with AutoML tune_for_memory option.
=> Address missing cpu() before numpy()

ludwig/features/number_feature.py
Add comments for the change required to resolve Issue #1911
=> doc: add comments re: change in normalize() function 

ludwig/api.py, ludwig/constants.py, ludwig/encoders/text_encoders.py, ludwig/globals.py
This PR adds a fix that enables loading locally saved pretrained weights for huggingface transformers.
Fixes issue mentioned in [slack](https://ludwig-ai.slack.com/archives/C01PN6M2RSM/p1648096456252769).
=> Added patch for loading cached huggingface transformer weights

requirements_dask.txt, requirements_distributed.txt, requirements_horovod.txt, setup.py
This PR consolidates the requirements for distributed training/eval in a manner similar to #1939.
=> Deletes requirements_[dask|horovod|ray].txt, adds requirements_distributed.txt

.github/workflows/pytest.yml
Workaround for https://github.com/pytorch/vision/issues/5873.
To be reverted once the upstream fix is made to pytorch.
=> Pin torch nightly in CI

ludwig/data/dataset_synthesizer.py, ludwig/features/audio_feature.py, ludwig/utils/audio_utils.py
=> Revert "Torchaudio Refactor"

ludwig/utils/strings_utils.py, ludwig/utils/types.py, tests/integration_tests/test_preprocessing.py
=> strip strings before creating single token vocab

ludwig/constants.py, ludwig/data/dataset_synthesizer.py, ludwig/features/audio_feature.py, ludwig/utils/audio_utils.py, requirements.txt
Refactor audio feature flow for torchaudio support.
=> Torch audio refactor

requirements.txt, requirements_distributed.txt
https://github.com/ray-project/ray/issues/22310
=> fix: Pin pyarrow=6.0.1

ludwig/automl/defaults/combiner/tabnet_config.yaml, ludwig/combiners/combiners.py
Results obtained from: https://github.com/ludwig-ai/experiments/blob/main/automl/validation/higgs/hyperopt_statistics.json.tabnet
=> Update tabnet defaults from best higgs and criteo configs

CONTRIBUTING.md
Fixes a broken link in CONTRIBUTING.md
click on Developer Guide in CONTRIBUTING.md line 92
=> Fix broken developer guide link in CONTRIBUTING.md

tests/integration_tests/test_custom_components.py
Small fix, didn't catch this during a prior PR. Thanks @jimthompson5802 !
=> fix: change bad import leftover from refactoring loop.

ludwig/automl/base_config.py, ludwig/automl/data_source.py, ludwig/automl/utils.py, ludwig/utils/audio_utils.py, ludwig/utils/image_utils.py, tests/ludwig/automl/test_base_config.py
naive inference by audio file extension
=> Add AutoML inference for audio

ludwig/api.py, ludwig/backend/ray.py, ludwig/models/predictor.py, ludwig/models/trainer.py, ludwig/modules/embedding_modules.py, ludwig/utils/torch_utils.py, tests/integration_tests/test_collect.py, tests/integration_tests/test_regularizers.py, tests/ludwig/combiners/test_combiners.py, tests/ludwig/encoders/test_bag_encoders.py, tests/ludwig/encoders/test_category_encoders.py, tests/ludwig/encoders/test_date_encoders.py, tests/ludwig/encoders/test_h3_encoders.py, tests/ludwig/encoders/test_sequence_encoders.py, tests/ludwig/encoders/test_set_encoders.py, tests/ludwig/features/test_audio_feature.py, tests/ludwig/features/test_bag_feature.py, tests/ludwig/features/test_binary_feature.py, tests/ludwig/features/test_category_feature.py, tests/ludwig/features/test_number_feature.py, tests/ludwig/features/test_sequence_features.py, tests/ludwig/features/test_set_feature.py, tests/ludwig/features/test_timeseries_feature.py, tests/ludwig/modules/test_embedding_modules.py, tests/ludwig/modules/test_encoder.py, tests/ludwig/modules/test_fully_connected_modules.py, tests/ludwig/modules/test_initializer_modules.py, tests/ludwig/modules/test_reduction_modules.py
Mechanical change: clean up code & facilitate future changes that may allow support for alternative pytorch gpu devices.
=> Factor pytorch device setting code

.github/workflows/pytest.yml
https://github.com/pytorch/vision/issues/6103
=> Unpin torchvision

ludwig/data/dataset/ray.py, ludwig/data/preprocessing.py, ludwig/utils/data_utils.py
maintain parity with the `HDF5Preprocessor` here: https://github.com/ludwig-ai/ludwig/blob/d9d2592548332582cbb910460e2c8471f009b3e8/ludwig/data/preprocessing.py#L1013
=> Add DATA_TRAIN_HDF5_FP in training_set_metadata for ParquetPreprocessor

ludwig/api.py, ludwig/backend/base.py, ludwig/backend/ray.py, ludwig/schema/__init__.py, ludwig/schema/trainer.py, ludwig/schema/utils.py, ludwig/trainers/base.py, ludwig/trainers/trainer_lightgbm.py, ludwig/utils/misc_utils.py, tests/integration_tests/test_gbm.py
Still needs some local testing
=> First pass at trainer schema separation.

ludwig/backend/ray.py
Otherwise they'll be lost in transit and reads may fail.
=> Explicitly pass data credentials when reading binary files from a RayBackend

ludwig/data/postprocessing.py
can potentially use `open_file` for local saving too?
=> Support saving numpy predictions to remote FS

ludwig/benchmarking/utils.py
A collection of utility functions for the benchmarking tool.
=> benchmarking utils

.github/workflows/pytest.yml, ludwig/api.py, ludwig/globals.py, ludwig/models/trainer.py, ludwig/modules/metric_modules.py, ludwig/utils/checkpoint_utils.py, ludwig/utils/fs_utils.py, setup.py, tests/integration_tests/test_trainer.py, tests/ludwig/modules/test_metric_modules.py
The new release of Ludwig 0.5.5 contains bug fixes
=> Bump Ludwig From v0.5.4 -> v0.5.5

README.md
=> typos: Update README.md

ludwig/backend/ray.py
=> Respect the resource requests in RayPredictor

ludwig/automl/automl.py, ludwig/utils/defaults.py, ludwig/utils/neuropod_utils.py, ludwig/utils/tokenizers.py, ludwig/utils/triton_utils.py
=> Allow writing init_config results to remote filesystems

ludwig/export.py, tests/integration_tests/test_cli.py, tests/integration_tests/test_mlflow.py
=> Fixed export_mlflow command to not assume an existing registered_model_name

ludwig/contribs/aim.py
Fixes: #2357
* Updating AimCallback to add init for optional repo.
* Fixed numpy serialization for config objects.
* Removed print statements, added logging for progress tracker.
```
from ludwig.datasets import titanic
from ludwig.contribs.aim import AimCallback
callback = AimCallback()
model = LudwigModel(config="./titanic_config.yaml", callbacks=[callback])
training_set, test_set, _ = titanic.load(split=True)
model.train(
training_set=training_set,
test_set=test_set,
experiment_name="simple_experiment",
model_name="simple_model",
)
```
Metrics are captured to the `.aim` folder relative to where the code above was run, and visualized with cli: 
```
aim up
```
=> fix: Fixes to serialization, and update to allow set repo location.

ludwig/contribs/mlflow/__init__.py, tests/integration_tests/test_mlflow.py
Skip artifact logging for MLFlowCallback with an initialization parameter
=> Optional artifact logging for MLFlow

ludwig/schema/__init__.py, ludwig/utils/backward_compatibility.py, tests/ludwig/utils/test_backward_compatibility.py
Picked from:
- https://github.com/ludwig-ai/ludwig/pull/2484
- https://github.com/ludwig-ai/ludwig/pull/2481
=> Cherry-pick backwards-compatibility fixes

ludwig/automl/automl.py, ludwig/hyperopt/execution.py, tests/integration_tests/test_automl.py, tests/integration_tests/test_hyperopt.py
=> Fixed usage of checkpoints for AutoML in Ray 2.0

ludwig/hyperopt/execution.py
=> Enable hyperopt to be launched from a ray client

ludwig/hyperopt/execution.py
This fixes an issue where `get_best_model_path` was returning a `TrialCheckpoint` object instead of a `str` object. After investigating this, it seemed to be tied to Ray 1.12 and 1.12.1, where the `as_directory()` method doesn't exist and defaulting to yielding the `checkpoint` which just returned the object instead of the path. This was causing a few tests to fail (https://github.com/ludwig-ai/ludwig/issues/2526)
=> Fix get_best_model in hyperopt for Ray 1.12

ludwig/schema/encoders/image_encoders.py, ludwig/schema/encoders/text_encoders.py, ludwig/schema/trainer.py, ludwig/schema/utils.py, ludwig/utils/defaults.py, tests/integration_tests/test_custom_components.py, tests/ludwig/marshmallow/test_fields_misc.py, tests/ludwig/utils/test_defaults.py
This helps ensure that the loading of old models are robust to changes to default parameter values.
Titanic example.
Before:
```python
'input_features': [   {   'column': 'Pclass',
'encoder': {'type': 'dense'},
'name': 'Pclass',
'proc_column': 'Pclass_mZFLky',
'tied': None,
'type': 'category'},
{   'column': 'Sex',
'encoder': {'type': 'dense'},
'name': 'Sex',
'proc_column': 'Sex_mZFLky',
'tied': None,
'type': 'category'},
{   'column': 'Age',
'encoder': {'type': 'passthrough'},
'name': 'Age',
'preprocessing': {   'missing_value_strategy': 'fill_with_mean'},
'proc_column': 'Age_DF6VxJ',
'tied': None,
'type': 'number'},
{   'column': 'SibSp',
'encoder': {'type': 'passthrough'},
'name': 'SibSp',
'proc_column': 'SibSp_mZFLky',
'tied': None,
'type': 'number'},
{   'column': 'Parch',
'encoder': …
```
=> Comprehensive configs: Explicitly list and save all parameter values for input and output features in configs. 

ludwig/visualize.py
f1 currently fails if total # classes exceeds `top_n_classes` (which =100 in this example)
=> fix: Limit frequency array to top_n_classes in F1 viz

ludwig/hyperopt/execution.py, ludwig/trainers/trainer.py, requirements_distributed.txt, requirements_hyperopt.txt, tests/integration_tests/test_hyperopt_ray.py
This allows us to perform distributed hyperopt even when the user has not configured a remote storage location.
Also bumps the min supported Ray version to 1.13.0.
=> Use Ray Air Checkpoint to sync files between trial workers

docker/ludwig-ray/Dockerfile
Update `ludwig-ray` to pull pytorch wheel from `https://download.pytorch.org/whl/cpu`
=> update docker with torch wheel

ludwig/schema/encoders/image_encoders.py, ludwig/schema/encoders/text_encoders.py, ludwig/schema/features/preprocessing/binary.py, ludwig/schema/trainer.py, ludwig/schema/utils.py, ludwig/utils/defaults.py, tests/integration_tests/test_custom_components.py, tests/ludwig/marshmallow/test_fields_misc.py, tests/ludwig/utils/test_defaults.py
Original PRs: https://github.com/ludwig-ai/ludwig/pull/2460,  https://github.com/ludwig-ai/ludwig/pull/2482
=> Cherrypick: Comprehensive Configs

.github/workflows/pytest.yml, ludwig/api.py, ludwig/utils/fs_utils.py, ludwig/utils/misc_utils.py, tests/integration_tests/test_remote.py, tests/integration_tests/utils.py
Also adds tests to ensure that s3 works as a remote storage layer.
=> Fixed issue when uploading output directory artifacts to remote filesystems

ludwig/schema/optimizers.py
=> bug: fix relative import in optimizers.py

ludwig/api.py, ludwig/utils/data_utils.py, ludwig/utils/metric_utils.py, ludwig/utils/visualization_utils.py, ludwig/visualize.py, tests/integration_tests/test_visualization_api.py
- Adds frequency and units to training stats
- Adds dataclasses: TrainingResults, TrainingStats, PreprocessedDataset
- training_statistics.json has evaluation frequency added, so visualize learning curves from saved model uses the right units in x axis label
=> Changes learning_curves to use "step" or "epoch" as x-axis label.

.github/workflows/pytest.yml, tests/README.md
Also skips cache and upload actions when running in act environement.
=> Documents running local tests with act

ludwig/data/preprocessing.py
Check dataset sizes after preprocessing, warn if validation or test set is too small to compute metrics.
=> Dataset size checks in preprocess_for_training

ludwig/collect.py, tests/integration_tests/test_cli.py
=> Actually print the torchinfo summary in print_model_summary()

ludwig/trainers/trainer_lightgbm.py
batch_size=None to ensure map_batches doesn't change num_blocks
=> Fix GBM ray nightly test

tests/integration_tests/test_hyperopt.py, tests/integration_tests/test_hyperopt_ray.py, tests/ludwig/hyperopt/test_hyperopt.py
Hyperopt tests are some of the longest-running distributed Ludwig tests. This PR optimizes the Ludwig config or hyperopt parameter spaces so that the tests run more quickly.
=> Optimize search space for hyperopt tests to decrease test durations

ludwig/backend/__init__.py, ludwig/backend/base.py
Also adds class method `LocalBackend.shared_instance()` as alternative to `LOCAL_BACKEND` global variable.
=> @DeveloperAPI annotations for backend module

ludwig/trainers/base.py, ludwig/trainers/trainer_lightgbm.py
=> BaseTrainer: add empty barrier()

ludwig/combiners/combiners.py
Adds API annotations to combiners
=> Adds @DeveloperAPI annotations to combiner classes

ludwig/trainers/trainer_lightgbm.py
For distributed GBMs, data sharding is done by number of blocks of the ray dataset. Ray dataset blocks are distributed across the parallel GBM workers.
This PR explicitly partition a RayDataset so that it has at least as many blocks as the total number of parallel workers.
=> Added ray datasets repartitioning in cases of multiple train workers

docker/README.md
Replaces TF2 with PyTorch, minor wording and typos.
=> Updates ludwig docker readme

ludwig/datasets/configs/sarcastic_headlines.yaml, ludwig/datasets/loaders/sarcastic_headlines.py
Adding sarcastic news headlines to Ludwig datasets
=> Drishi sarcasmdataset 1

ludwig/utils/defaults.py, ludwig/utils/fs_utils.py, ludwig/utils/image_utils.py, ludwig/utils/misc_utils.py, ludwig/utils/neuropod_utils.py, ludwig/utils/print_utils.py, ludwig/utils/system_utils.py, ludwig/utils/torch_utils.py, ludwig/utils/trainer_utils.py, ludwig/utils/triton_utils.py
This PR adds DeveloperAPI annotations to some of Ludwig's utility modules.
=> [Annotations] Add DeveloperAPI annotations to Ludwig utils - Part 1

ludwig/api.py
Cherry-pick #2772 into release branch.
=> move preprocess callbacks inside model.preprocess (#2772)

ludwig/utils/automl/data_source.py, ludwig/utils/automl/field_info.py, ludwig/utils/automl/type_inference.py, ludwig/utils/automl/utils.py
Makes all autoML util functions and dataclasses DeveloperAPI.
=> [Annotations] Annotate AutoML utils

ludwig/datasets/loaders/dataset_loader.py
This PR removes dead code and improves type annotations for Ludwig's DatasetLoader public API to make it easier for users to add new datasets.
=> Improve type hints and remove dead code for DatasetLoader module

README.md
Inspired by another open-source project I saw :) This will look something like this once merged in! Added it to the bottom of our README. Might be worth also pulling the same URL into our docs.
=> Add Ludwig contributors to README

requirements.txt
```
File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/api.py", line 40, in <module>
from ludwig.backend import Backend, initialize_backend, provision_preprocessing_workers
File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/backend/__init__.py", line 22, in <module>
from ludwig.backend.base import Backend, LocalBackend
File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/backend/base.py", line 28, in <module>
from ludwig.backend.utils.storage import StorageManager
File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/backend/utils/storage.py", line 4, in <module>
from ludwig.utils import data_utils
File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/utils/data_utils.py", line 41, in <module>
from sklearn.model_selection import KFold
File …
```
=> Pin scikit-learn<1.2.0

ludwig/api.py, ludwig/backend/ray.py, ludwig/constants.py, ludwig/encoders/image_encoders.py, ludwig/encoders/registry.py, ludwig/encoders/text_encoders.py, ludwig/trainers/trainer.py, ludwig/utils/config_utils.py, ludwig/utils/heuristics.py, tests/integration_tests/test_ray.py, tests/integration_tests/test_trainer.py
Introduces heuristics for `learning_rate: auto`
```
if feature with large encoders (text, image, audio, sequence, timeseries):
if HF encoder: 
if trainable: false: 0.00002
else 0.00001
else: 0.0001
else: 0.001
```
=> Replace `learning rate: auto` with feature type and encoder-based heuristics

ludwig/features/vector_feature.py, tests/integration_tests/test_experiment.py
=> Automatically infer vector_size for vector features when not provided

ludwig/utils/visualization_utils.py
Quick fix in cases where there are a lot of x-axis labels and the horizontal axis doesn't scale well. 
Before:
After:
=> Rotate Brier Plot X-axis labels to 45 degree angle

.github/workflows/docker.yml, docker/ludwig-gpu/Dockerfile
=> Fix ludwig-gpu image

tests/regression_tests/benchmark/test_model_performance.py
=> Skipped mercedes_benz_greener.ecd.yaml benchmark test

ludwig/schema/encoders/text_encoders.py
=> MT5 reduce_output can't be cls_pooled - set to sum by default

ludwig/schema/encoders/text_encoders.py, requirements.txt
=> Change default reduce_output strategy to sum for CamemBERT

ludwig/schema/metadata/configs/decoders.yaml
Looks like we missed a param. Here's the fix.
=> Fix Internal Only Param

ludwig/explain/captum.py, tests/integration_tests/test_explain.py
- Correctly reduce image attributions
- Only normalize attributions for visualization
=> Explain fixes

tests/regression_tests/benchmark/test_model_performance.py
Issue filed here: https://github.com/ludwig-ai/ludwig/issues/3019
=> Skip Sarcos dataset during benchmark tests

ludwig/schema/encoders/text_encoders.py, ludwig/schema/metadata/configs/encoders.yaml, ludwig/schema/metadata/configs/features.yaml, ludwig/schema/metadata/configs/loss.yaml, ludwig/schema/metadata/configs/trainer.yaml, ludwig/schema/trainer.py
Changes made here:
- HuggingFace encoder param ordering and expected impact
- Propagate metadata descriptions for HuggingFace params
- General expected impact calibration
- Some description updates
=> Schema Polishing

requirements_serve.txt, tests/ludwig/utils/test_server_utils.py
https://github.com/encode/starlette/blob/d7558515020f4c0a96b199880c181a40678b18d5/docs/release-notes.md#0210
starlette==0.22.0 in turn is required by fastapi==0.89.0
=> add httpx as required by starlette>=0.21.0

ludwig/modules/lr_scheduler.py, tests/ludwig/modules/test_lr_scheduler.py
=> Fix LR reduce on plateau interaction with base LR decay

ludwig/data/preprocessing.py
=> Quick fix for cached logging

ludwig/utils/visualization_utils.py
=> Round confusion matrix numbers to 3 decimal places

ludwig/trainers/trainer.py, ludwig/trainers/trainer_lightgbm.py
This is already handled in `ludwig/schema/model_types/base.py`
=> Remove duplicate validation field validation.

ludwig/utils/visualization_utils.py, ludwig/visualize.py, tests/integration_tests/test_visualization.py, tests/integration_tests/test_visualization_api.py
Normal PR Curve API
PR Curve API using test statistics
=> Add Precision Recall curves to Ludwig

ludwig/schema/encoders/text_encoders.py
upstream issue filed with HuggingFace https://github.com/huggingface/transformers/issues/21626
=> XLNet: disable "uni" attention type

ludwig/features/image_feature.py, ludwig/schema/features/augmentation/utils.py, ludwig/schema/features/image_feature.py, ludwig/schema/utils.py, tests/ludwig/augmentation/test_augmentation_pipeline.py, tests/ludwig/schema/test_model_config.py
Add test case for saving and loading a model with augmentation
=> Fixed serialization and deserialization of augmentation configuration

.github/workflows/pytest.yml
```
ludwig/schema/model_types/base.py:27: in <module>
from ludwig.utils.backward_compatibility import upgrade_config_dict_to_latest_version
ludwig/utils/backward_compatibility.py:68: in <module>
from ludwig.features.feature_registries import get_base_type_registry, get_input_type_registry, get_output_type_registry
ludwig/features/feature_registries.py:33: in <module>
from ludwig.features.audio_feature import AudioFeatureMixin, AudioInputFeature
ludwig/features/audio_feature.py:22: in <module>
import torchaudio
/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/torchaudio/__init__.py:15: in <module>
from torchaudio.backend import get_audio_backend, list_audio_backends, set_audio_backend
/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/torchaudio/backend/_ …
```
=> Pin torch nightly to Feb 13, 2023

ludwig/utils/visualization_utils.py
Should scale reasonably well now
=> Resize confusion matrix properly

ludwig/explain/captum.py, ludwig/explain/captum_ray.py, ludwig/explain/explainer.py, ludwig/explain/explanation.py, ludwig/explain/gbm.py, tests/integration_tests/test_explain.py
- `Explainer` API now returns both global and row-level explanations via the new `ExplanationsResult` dataclass
- Stores aggregated attributions in `global_explanation`. Token attributions are averaged and the top 100 tokens are included in the `global_explanation`.
=> [Explain] always return global and row-level explanations

ludwig/schema/metadata/configs/features.yaml
=> Make fill_value a medium impact parameter in preprocessing

requirements_distributed.txt
https://github.com/ray-project/ray/issues/22310 has been resolved.
=> Unpin pyarrow

ludwig/decoders/generic_decoders.py, tests/ludwig/modules/test_lr_scheduler.py, tests/regression_tests/model/test_old_models.py
Ludwig Issue: https://github.com/ludwig-ai/ludwig/issues/3150
=> Disable passthrough decoder for all feature types

ludwig/config_validation/validation.py, ludwig/schema/model_types/base.py
Redo of https://github.com/ludwig-ai/ludwig/pull/3136 - this time from a native upstream branch rather than from my own fork.
=> int: [REBASE] Remove unnecessary JSON schema code

ludwig/utils/hf_utils.py, tests/ludwig/encoders/test_text_encoders.py
Example failure: https://github.com/ludwig-ai/ludwig/commit/a6ea300506ac72ef73643d3da70ad778617dd826
=> Fix @slow hf tests

.github/workflows/pytest.yml, requirements.txt
This PR pins `torchaudio`, closing https://github.com/ludwig-ai/ludwig/issues/3245
=> Pin `torchaudio`

.github/workflows/pytest.yml, requirements.txt
Closes https://github.com/ludwig-ai/ludwig/issues/3247.
=> Pin `torchvision` and `torchtext`

ludwig/schema/metadata/configs/combiners.yaml, ludwig/schema/metadata/configs/encoders.yaml, ludwig/schema/metadata/parameter_metadata.py
The goal of this PR to track at the encoder and combiner level the expected hardware requirements for the purposes of improving AutoML and documentation.
=> Added compute tiers to parameter metadata

tests/ludwig/utils/test_hf_utils.py
Follow up to comment missed on https://github.com/ludwig-ai/ludwig/pull/3211/
=> Add test for falling back to HF model that's not in the ludwig pretrained dir

ludwig/combiners/combiners.py, tests/ludwig/combiners/test_combiners.py
Fix for the following failure
`TypeError: 'LudwigFeatureDict' object is not subscriptable`
on the following config (just an example. Also fails with other combiners)
```
{'combiner': {'dropout': 0.23429196302654826,
'norm': 'batch',
'num_fc_layers': 2,
'output_size': 128,
'type': 'project_aggregate'},
'input_features': [{'encoder': {'idx2str': ['shPZ',
'tktQ',
'nvZSdg',
'jdddezacG',
'OaP',
'uPbBjZGPoj',
'RzrsXi',
'GLZWCEDiWu',
'Xi',
'dsrekI'],
'vocab_size': 10},
'name': 'category_1',
'type': 'category'},
{'name': 'number_1', 'type': 'number'},
{'name': 'binary_1', 'type': 'binary'}],
'model_type': 'ecd',
'output_features': [{'decoder': {'idx2str': ['bFuiUG',
'yANeMZgjRc',
'ARDdfzasO',
'Vluy',
'IhE',
'vv',
'jYi',
'YtOaymtGo',
'wzTGEyr',
'aJg'],
'vocab_size': 10},
'name': …
```
=> Update all combiners to use `.get` to access `LudwigFeatureDict` contents

ludwig/globals.py, setup.py
To merge after https://github.com/ludwig-ai/ludwig/pull/3283
=> Update version to 0.7.4

ludwig/utils/data_utils.py, tests/ludwig/utils/test_data_utils.py
Following up on: https://github.com/ludwig-ai/ludwig/pull/3266#discussion_r1146947974
=> test: Parameterize dataset read chunking test

requirements.txt
Pandas 2.0 introduces breaking changes that need to be addressed. Pin `pandas < 2.0` until fixes are in.
=> Pin pandas < 2.0

tests/regression_tests/benchmark/test_model_performance.py
See: https://github.com/ludwig-ai/ludwig/issues/3344
=> Skip ames tests

requirements_distributed.txt
```
FAILED tests/integration_tests/test_sequence_decoders.py::test_sequence_decoder_predictions[True-generator-text-text_feature] - AttributeError: 'str' object has no attribute 'reshape'
FAILED tests/integration_tests/test_sequence_decoders.py::test_sequence_decoder_predictions[True-generator-sequence-sequence_feature] - AttributeError: 'str' object has no attribute 'reshape'
FAILED tests/integration_tests/test_sequence_decoders.py::test_sequence_decoder_predictions[True-tagger-text-text_feature] - AttributeError: 'str' object has no attribute 'reshape'
FAILED tests/integration_tests/test_sequence_decoders.py::test_sequence_decoder_predictions[True-tagger-sequence-sequence_feature] - AttributeError: 'str' object has no attribute 'reshape'
FAILED …
```
=> Pin dask<2023.4.0

ludwig/schema/lr_scheduler.py
=> Description Fix

.github/workflows/pytest.yml
https://github.com/pytorch/pytorch/issues/100002 closed
=> Remove `expecttest` temporary install

ludwig/data/dataframe/dask.py, tests/ludwig/data/dataframe/test_dask.py
This was incidentally removed in #3351.
=> Add special handling for empty ray datasets.

.github/workflows/pytest.yml, ludwig/backend/datasource.py, ludwig/contribs/mlflow/__init__.py, ludwig/data/dataset/ray.py, ludwig/hyperopt/execution.py
Reverting for now, as the dataset size computation is incorrect, leading to training in only a small fraction of the data. This is affecting all training jobs, so we will need to land this immediately to unblock.
=> Revert "Ray nightly compatibility (#3275)"

ludwig/models/retrieval.py, ludwig/vector_index/__init__.py, ludwig/vector_index/base.py, ludwig/vector_index/faiss.py
Short term goal is to improve error messages like those seen in #3427 when deps aren't installed. Longer term, this opens up an easy path to onboard additional vector index solutions.
=> Added vector index interface and fixed import errors

ludwig/config_validation/validation.py
At some point this was deleted 😓
=> int: Add back `required` for input and output features to the Ludwig JSON schema

docker/ludwig-gpu/Dockerfile
=> upgrade ludwig-gpu docker image to pytorch 2.0.0

.github/workflows/pytest.yml
Also disables horovod installation and tests for torch nightly CC: #3468
=> Unpin torch nightly CI.

requirements_llm.txt
https://github.com/TimDettmers/bitsandbytes/issues/667
=> Pin bitsandbytes<0.41.0

ludwig/schema/metadata/configs/preprocessing.yaml, ludwig/schema/preprocessing.py
Useful preprocessing feature for LLM fine-tuning.
=> Add parameter metadata for global_max_sequence_length

ludwig/globals.py, setup.py
=> Update ludwig version to 0.8.1

ludwig/api.py, ludwig/config_validation/checks.py, ludwig/features/date_feature.py, ludwig/features/text_feature.py, ludwig/models/llm.py, ludwig/schema/combiners/comparator.py, ludwig/schema/combiners/concat.py, ludwig/schema/combiners/project_aggregate.py, ludwig/schema/combiners/sequence.py, ludwig/schema/combiners/sequence_concat.py, ludwig/schema/combiners/tab_transformer.py, ludwig/schema/combiners/tabnet.py, ludwig/schema/combiners/transformer.py, ludwig/schema/combiners/utils.py, ludwig/trainers/trainer_llm.py, ludwig/utils/date_utils.py, tests/integration_tests/test_custom_components.py, tests/integration_tests/test_date_feature.py, tests/integration_tests/test_experiment.py, tests/integration_tests/test_llm.py, tests/ludwig/config_validation/test_checks.py, tests/ludwig/datasets/test_dataset_configs.py, tests/ludwig/features/test_date_feature.py, tests/ludwig/schema/test_model_config.py, tests/ludwig/utils/test_date_utils.py
=> Release 0.8.1 latest

README.md
Explicitly set backend type to local, and add cosine decay, and adds a task description for instruction fine-tuning that was previously missing.
=> README: Update LLM fine-tuning config

ludwig/modules/lr_scheduler.py, ludwig/schema/lr_scheduler.py, ludwig/schema/metadata/configs/trainer.yaml, tests/ludwig/modules/test_lr_scheduler.py
=> DRAFT: Revert "Add Cosine Annealing LR scheduler as a decay method (#3507)"

requirements.txt
=> Unpin Transformers for CodeLlama support

requirements.txt
Seem to be some patch releases: https://github.com/huggingface/transformers/releases
=> Pin minimum transformers version to `4.33.2`

ludwig/schema/llms/generation.py
Because we set a default temperature of 0.1 and do_sample=False is incompatible with temperature, we should just set do_sample to True by default.
=> Set do_sample default to True

.github/workflows/pytest.yml, tests/ludwig/data/test_dataset_synthesizer.py, tests/ludwig/features/test_audio_feature.py, tests/ludwig/models/test_training_determinism.py, tests/regression_tests/model/test_old_models.py
=> FIX: Failure in audio feature related test

tests/ludwig/utils/test_image_utils.py
=> FIX: error with nightly CI tests for test_resize_image

tests/ludwig/schema/test_model_config.py
Forgot to skip this test when we merged #3688
=> fix: Failing test for backend with quantization

README.md
=> Add Ludwig Star History to README

ludwig/api.py
In an effort to land https://github.com/ludwig-ai/ludwig-docs/pull/303/files, and re-enable the automatic api docs updates.
=> Use sphinx for all docstrings in api.py

requirements_distributed.txt
See https://github.com/microsoft/DeepSpeed/issues/4473
=> Unpin deepspeed following fix in v0.11.1

ludwig/api.py, ludwig/trainers/trainer.py
Logged information comes from [torch.cuda](https://pytorch.org/docs/stable/cuda.html).
=> Log additional per-GPU information in model metadata files and GPU utilization on tensorboard.

.vscode/settings.json
Context: https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions
=> QOL: Update recommended vscode settings.

ludwig/config_validation/checks.py, requirements_llm.txt
https://github.com/ludwig-ai/ludwig/issues/3724
=> Pin PEFT to PEFT master for Mistral-7B support

CONTRIBUTING.md, tests/integration_tests/test_llm.py
In the present author's experience, Ludwig installation has not gone smoothly (under `Anaconda` with Python 3.10.13) without additional steps and omissions.  This change recommends these steps and work-around procedures.
`api.md` is automatically generated from the docstrings in the code, so if you want to change something in that file, first modify `ludwig/api.py` docstring, then run …
=> [MAINTENANCE] Update contributor instructions with additional steps that may be needed for installation to succeed.

ludwig/schema/decoders/base.py
Adds config for a binary TART decoder to the existing decoder schemas.
=> Add TART decoder config object

ludwig/models/predictor.py, ludwig/schema/metadata/configs/trainer.yaml, ludwig/schema/trainer.py, tests/ludwig/evaluation/test_evaluation.py
Add eval_steps under trainer this time instead of preprocessing
=> Add eval_steps as a flag

ludwig/schema/llms/peft.py, ludwig/schema/metadata/configs/llm.yaml, tests/integration_tests/test_llm.py
Also changes the default alpha to `2 * r`.
=> Added target_modules to LoRA config

CODEOWNERS
👥 Repository-Level Code Owners Update
This PR focuses on updating the repository-level CODEOWNERS file. Repository-level code owners are designated for the entire codebase, ensuring that at least one of them approves any pull request.
Changes include:
- Defining default code owners for the entire repository.
- Ensuring that approval from at least one code owner is required for PRs.
Please review the updated CODEOWNERS file to confirm that the assignments align with our team structure and ownership responsibilities.
🚀 Impact:
This update strengthens our code review process, requiring approval from repository-level code owners for all changes. It reinforces collaboration and code quality standards.
=> Introduce CODEOWNERS to ensure at least 1 approval by Ludwig maintainers / the Predibase team

ludwig/trainers/trainer.py, ludwig/utils/trainer_utils.py
Small refactor to make getting total expected checkpoints available for use elsewhere
=> refactor get_total_expected_checkpoint into a function

ludwig/schema/llms/base_model.py, ludwig/schema/model_types/utils.py, ludwig/utils/llm_utils.py
Model was pushed here 21 hours ago 🥳 https://huggingface.co/susnato/phi-2
=> Add support for Phi 2

ludwig/schema/features/base.py
I think there is a bug/typo in the FeatureCollection class
=> fix: correct typo in FeatureCollection

ludwig/api.py, ludwig/schema/utils.py, ludwig/utils/misc_utils.py
Scrub credentials from artifacts
=> Scrub credentials from model_hyperparameters.json and description.json

requirements.txt
In line with the minimum torch version our GHA actions currently test!
=> [Maintenance] Bump minimum torch version to 2.0.0

.github/workflows/pytest.yml, requirements.txt
=> [Maintenance] Remove torchdata pin for nightly install

ludwig/globals.py, setup.py
=> Update ludwig version to 0.9.2

.github/workflows/upload-pypi.yml
=> Ludwig release steps pypi

.github/workflows/pytest.yml
=> [Maintenance] Remove torch nightly pin

ludwig/globals.py, setup.py
This is part of release process.
=> Update ludwig version to 0.9.3

ludwig/globals.py, setup.py
=> Update Ludwig development version.

ludwig/globals.py, setup.py
=> Update ludwig version to v0.10.1

ludwig/globals.py, setup.py
=> [MAINTENANCE] Update Ludwig development version.

ludwig/schema/llms/peft.py, ludwig/schema/metadata/configs/llm.yaml, requirements_llm.txt, tests/integration_tests/test_llm.py
Both of these options are configurable using the regular lora adapter, but have different duties! They can be enabled together but have strengths in different circumstances.
When set to True, we use Rank-Stabilized LoRA which sets the adapter scaling factor to `lora_alpha/math.sqrt(r)`, since it was proven to work better. Otherwise, it will use the original default value of `lora_alpha/r`.
In equation form:
- Normal LoRA layers: `W0X + (lora_alpha/r)(BAX)` where W0 is the base model, BA are the lora weight matrices and X is the input from the embedding layer/previous transformer layer.
- LoRA layers with RSLoRA enabled: `W0X + (lora_alpha/sqrt(r))(BAX)`
In particular, this is useful when using larger ranks since it prevents the gradient from collapsing as rank increases, which may result …
=> Add support for RSLoRA and DoRA

ludwig/modules/metric_modules.py, tests/ludwig/evaluation/test_evaluation.py
=> Temporarily disable expensive text metrics

requirements.txt
=> [MAINTENANCE] Use latest version of psutil library.

ludwig/globals.py, setup.py
=> Update ludwig version to v0.10.2

ludwig/globals.py, setup.py
=> update latest version for development

ludwig/schema/llms/peft.py
Oops, I forgot to actually pass it into the adapter config so they never got used. That's my bad
=> Actually add support for RSLoRA and DoRA

ludwig/globals.py, setup.py
=> Update Ludwig version to v0.10.3.

ludwig/globals.py, setup.py
=> Update Development Version to Correspond to Release-0.10.3

ludwig/visualize.py
- fixed typo.
comparision -> comparison
=> Docs: update visualize.py

ludwig/globals.py, setup.py
=> Update ludwig version to v0.10.4

.github/workflows/pytest.yml, ludwig/globals.py, requirements_test.txt, setup.py
=> Update the trunk version to "0.10.4.dev"
